// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e9f968b120b46161 "Odin Project", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
 * brandName?: string // Brand Name
}} Props

 */
import { routes } from "./chunks/chunk-3DUKK5YU.js";

// virtual:brand-header
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/nNvBUXUdJFSCYSuQGxD0/ZJNsaPxvRXHStKFpk8Gm/jOC1i2Kqw.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/E0DNmfMZHbHZom3aye6U/AD1iGc5nBgAhP4jZTZKv/JSL1oF6g1.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;JetBrains Mono-bold",
	"FS;JetBrains Mono-extrabold",
	"FS;JetBrains Mono-extrabold italic",
	"FS;JetBrains Mono-bold italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/BTOY6STFL42WXJYET4IAFJ4R4NWQMPYV/SIRJV64UEOICTYN5EECZFJJ3ML2D6HVV/ATU2C7QZBG7GCVXROP265OYM5E55WHMK.woff2",
				weight: "700",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/W2QLP4CHXEAE2UDQ4JZRQSCVGRWTODXQ/IZHRABAMPPUXMZ2PD72AYR3CARBXVTMT/VCHFQIE7HVVHWFPYX3UJFHLWZNFBWMY2.woff2",
				weight: "800",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/CYELXKES646LNQMHDBMMNBTFTS5XYQRB/H7NE6NFMXJ4EIQOOQK2QDHNFWQHSJ62F/HIEFT57NYSYQJX2RC4H6NZCOYVHPMBAL.woff2",
				weight: "800",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/4UER7KOM5ELODXZSILS67WJ47ZOE75JQ/6CQXJGOZP6EVG2LPOOVWXH2KM6JHNSRY/UTZ3OSIQCH2DNRJBPY7UY3LB6YDOZNJX.woff2",
				weight: "700",
			},
		],
	},
];
var css = [
	`.framer-AIfo9 .framer-styles-preset-jehuhb:not(.rich-text-wrapper), .framer-AIfo9 .framer-styles-preset-jehuhb.rich-text-wrapper h1 { --framer-font-family: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 180px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 800; --framer-font-weight-bold-italic: 800; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.04em; --framer-line-height: 1.1em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-cc3662e6-3397-466e-9cb2-289050ebc7cb, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }`,
	`@media (max-width: 1199px) and (min-width: 810px) { .framer-AIfo9 .framer-styles-preset-jehuhb:not(.rich-text-wrapper), .framer-AIfo9 .framer-styles-preset-jehuhb.rich-text-wrapper h1 { --framer-font-family: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 120px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 800; --framer-font-weight-bold-italic: 800; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.04em; --framer-line-height: 1.1em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-cc3662e6-3397-466e-9cb2-289050ebc7cb, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-AIfo9 .framer-styles-preset-jehuhb:not(.rich-text-wrapper), .framer-AIfo9 .framer-styles-preset-jehuhb.rich-text-wrapper h1 { --framer-font-family: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 48px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 800; --framer-font-weight-bold-italic: 800; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.04em; --framer-line-height: 1.1em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-cc3662e6-3397-466e-9cb2-289050ebc7cb, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }`,
];
var className = "framer-AIfo9";

// /:https://framerusercontent.com/modules/nNvBUXUdJFSCYSuQGxD0/ZJNsaPxvRXHStKFpk8Gm/jOC1i2Kqw.js
var cycleOrder = ["LrnUL8PMn", "dRUJRez5O", "SC6Vl0Aqy"];
var serializationHash = "framer-Po2fE";
var variantClassNames = {
	dRUJRez5O: "framer-v-1nim650",
	LrnUL8PMn: "framer-v-1ykal4w",
	SC6Vl0Aqy: "framer-v-vczb05",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "LrnUL8PMn",
	Phone: "SC6Vl0Aqy",
	Tablet: "dRUJRez5O",
};
var getProps = ({ brandName, height, id, width, ...props }) => {
	return {
		...props,
		pxkTsKd18: brandName ?? props.pxkTsKd18 ?? "Purestudio",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "LrnUL8PMn",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		pxkTsKd18,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "LrnUL8PMn",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1ykal4w",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"LrnUL8PMn"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								dRUJRez5O: {
									"data-framer-name": "Tablet",
								},
								SC6Vl0Aqy: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							background={{
								alt: "",
								fit: "fill",
							}}
							className={"framer-wo69io"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"K6hZj6XK1"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-77n2al"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"aBd5DGdDy"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={pxkTsKd18}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										dRUJRez5O: {
											viewBox: "0 0 1008 198",
										},
										SC6Vl0Aqy: {
											viewBox: "0 0 1008 198",
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h1
										className={"framer-styles-preset-jehuhb"}
										data-styles-preset={"JSL1oF6g1"}
										style={{
											"--framer-text-alignment": "center",
										}}
									>
										{"Purestudio"}
									</motion.h1>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Po2fE.framer-msqnz4, .framer-Po2fE .framer-msqnz4 { display: block; }",
	".framer-Po2fE.framer-1ykal4w { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1440px; }",
	".framer-Po2fE .framer-wo69io { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px 20px 0px 20px; position: relative; width: 100%; }",
	".framer-Po2fE .framer-77n2al { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Po2fE.framer-1ykal4w, .framer-Po2fE .framer-wo69io { gap: 0px; } .framer-Po2fE.framer-1ykal4w > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-Po2fE.framer-1ykal4w > :first-child { margin-top: 0px; } .framer-Po2fE.framer-1ykal4w > :last-child { margin-bottom: 0px; } .framer-Po2fE .framer-wo69io > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-Po2fE .framer-wo69io > :first-child { margin-left: 0px; } .framer-Po2fE .framer-wo69io > :last-child { margin-right: 0px; } }",
	".framer-Po2fE.framer-v-1nim650.framer-1ykal4w { width: 810px; }",
	".framer-Po2fE.framer-v-1nim650 .framer-77n2al, .framer-Po2fE.framer-v-vczb05 .framer-77n2al { white-space: pre; }",
	".framer-Po2fE.framer-v-vczb05.framer-1ykal4w { width: 320px; }",
	...css,
];
var FramerjOC1i2Kqw = withCSS(Component, css2, "framer-Po2fE");
var stdin_default = FramerjOC1i2Kqw;
FramerjOC1i2Kqw.displayName = "Brand Header";
FramerjOC1i2Kqw.defaultProps = {
	height: 198,
	width: 1440,
};
addPropertyControls(FramerjOC1i2Kqw, {
	variant: {
		options: ["LrnUL8PMn", "dRUJRez5O", "SC6Vl0Aqy"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	pxkTsKd18: {
		defaultValue: "Purestudio",
		displayTextArea: false,
		title: "Brand Name",
		type: ControlType.String,
	},
});
addFonts(
	FramerjOC1i2Kqw,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:brand-header
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "LrnUL8PMn",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BrandHeaderFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var brand_header_default = ComponentWithRoot;
export { brand_header_default as default };
