// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e9f968b120b46161 "Odin Project", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * link?: string // Link
 * radius?: any // Radius
 * title?: string // Title
 * fill?: string // Fill
}} Props

 */
import { Icon } from "./chunks/chunk-MJX6QVBH.js";
import "./chunks/chunk-NULYBL27.js";
import { routes } from "./chunks/chunk-3DUKK5YU.js";

// virtual:cta-button-delete
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/pSl8mboY6CSozoGe4psO/k2f1W6ZIwX3Ki9tndQ8L/zmeQ8k5tf.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PhosphorFonts = getFonts(Icon);
var enabledGestures = {
	P4W9mPgT5: {
		hover: true,
	},
};
var serializationHash = "framer-WXtxf";
var variantClassNames = {
	P4W9mPgT5: "framer-v-vcm4fe",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var radiusForCorner = (value, cornerIndex) => {
	if (typeof value === "number" && Number.isFinite(value))
		return Math.max(0, value) + "px";
	if (typeof value !== "string" || typeof cornerIndex !== "number")
		return void 0;
	const segments = value.split(" ");
	return segments[cornerIndex] || segments[cornerIndex - 2] || segments[0];
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ fill, height, id, link, radius, title, width, ...props }) => {
	return {
		...props,
		Fbyr5abmG: title ?? props.Fbyr5abmG ?? "Use for Free",
		l1Uh3DC2Y: radius ?? props.l1Uh3DC2Y ?? "10px",
		wjjmPj5qS: link ?? props.wjjmPj5qS,
		xLqgLZVjk:
			fill ??
			props.xLqgLZVjk ??
			"var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255))",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		wjjmPj5qS,
		l1Uh3DC2Y,
		Fbyr5abmG,
		xLqgLZVjk,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "P4W9mPgT5",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (gestureVariant === "P4W9mPgT5-hover") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={wjjmPj5qS}
						motionChild={true}
						nodeId={"P4W9mPgT5"}
						openInNewTab={true}
						scopeId={"zmeQ8k5tf"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-vcm4fe", className, classNames)} framer-ix9tz`}
							data-framer-name={"Variant 1"}
							layoutDependency={layoutDependency}
							layoutId={"P4W9mPgT5"}
							ref={refBinding}
							style={{
								backdropFilter: "blur(0px)",
								backgroundColor: xLqgLZVjk,
								borderBottomLeftRadius: radiusForCorner(l1Uh3DC2Y, 3),
								borderBottomRightRadius: radiusForCorner(l1Uh3DC2Y, 2),
								borderTopLeftRadius: radiusForCorner(l1Uh3DC2Y, 0),
								borderTopRightRadius: radiusForCorner(l1Uh3DC2Y, 1),
								WebkitBackdropFilter: "blur(0px)",
								...style,
							}}
							variants={{
								"P4W9mPgT5-hover": {
									backgroundColor:
										"var(--token-35958b5f-fcd4-4988-a517-708c39eda844, rgb(250, 250, 250))",
								},
							}}
							{...addPropertyOverrides(
								{
									"P4W9mPgT5-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-o33o9w"}
								fonts={["FS;Poppins-medium"]}
								layoutDependency={layoutDependency}
								layoutId={"WVTFcd3Gl"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={Fbyr5abmG}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "RlM7UG9wcGlucy1tZWRpdW0=",
											"--framer-font-family":
												'"Poppins", "Poppins Placeholder", sans-serif',
											"--framer-font-size": "14px",
											"--framer-font-weight": "500",
											"--framer-letter-spacing": "-0.02em",
											"--framer-line-height": "1.6em",
										}}
									>
										{"Use for Free"}
									</motion.p>
								</React.Fragment>
							</RichText>
							{isDisplayed() && (
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-iw8cxy-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"YRsU21fpP-container"}
										nodeId={"YRsU21fpP"}
										rendersWithMotion={true}
										scopeId={"zmeQ8k5tf"}
									>
										<Icon
											color={"rgb(0, 0, 0)"}
											height={"100%"}
											iconSearch={"House"}
											iconSelection={"ArrowRight"}
											id={"YRsU21fpP"}
											layoutId={"YRsU21fpP"}
											mirrored={false}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											weight={"regular"}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-WXtxf.framer-ix9tz, .framer-WXtxf .framer-ix9tz { display: block; }",
	".framer-WXtxf.framer-vcm4fe { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: 38px; justify-content: center; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 142px; will-change: var(--framer-will-change-override, transform); }",
	".framer-WXtxf .framer-o33o9w { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-WXtxf .framer-iw8cxy-container { flex: none; height: 16px; position: relative; width: 16px; }",
	".framer-WXtxf.framer-v-vcm4fe.hover.framer-vcm4fe { gap: 6px; }",
];
var FramerzmeQ8k5tf = withCSS(Component, css, "framer-WXtxf");
var stdin_default = FramerzmeQ8k5tf;
FramerzmeQ8k5tf.displayName = "CTA Button (Delete)";
FramerzmeQ8k5tf.defaultProps = {
	height: 38,
	width: 142,
};
addPropertyControls(FramerzmeQ8k5tf, {
	wjjmPj5qS: {
		title: "Link",
		type: ControlType.Link,
	},
	l1Uh3DC2Y: {
		defaultValue: "10px",
		title: "Radius",
		type: ControlType.BorderRadius,
	},
	Fbyr5abmG: {
		defaultValue: "Use for Free",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	xLqgLZVjk: {
		defaultValue:
			'var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255)) /* {"name":"White"} */',
		title: "Fill",
		type: ControlType.Color,
	},
});
addFonts(
	FramerzmeQ8k5tf,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Poppins",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/K4RHKGAGLQZBXEZQT2O2AGSLKJF2E4YC/JRUTXNFPWLFGIEVSSEYOW7EP7TYM3V6A/UCDYLFFGLZRGCFY5GYDYM5LDB52BAR5M.woff2",
					weight: "500",
				},
			],
		},
		...PhosphorFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cta-button-delete
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CtaButtonDeleteFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var cta_button_delete_default = ComponentWithRoot;
export { cta_button_delete_default as default };
