// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e9f968b120b46161 "Odin Project", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant Hello' | 'Variant Dot' | 'Variant Dot Hover' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-3DUKK5YU.js";

// virtual:cursor
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/kLsraWKHR73r3Ogw2Uo0/Ue5BxYUptdXxYznpy1tM/pFw_HLczq.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	SpKqW8P1p: {
		pressed: true,
	},
};
var cycleOrder = ["bZJV_1Au2", "SpKqW8P1p", "pO2Tp9wq6"];
var serializationHash = "framer-5m7B7";
var variantClassNames = {
	bZJV_1Au2: "framer-v-1jk02m5",
	pO2Tp9wq6: "framer-v-14fondl",
	SpKqW8P1p: "framer-v-1avthkb",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant Dot Hover": "pO2Tp9wq6",
	"Variant Dot": "SpKqW8P1p",
	"Variant Hello": "bZJV_1Au2",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "bZJV_1Au2",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "bZJV_1Au2",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "pO2Tp9wq6") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "pO2Tp9wq6") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1jk02m5",
							className,
							classNames,
						)}
						data-framer-name={"Variant Hello"}
						layoutDependency={layoutDependency}
						layoutId={"bZJV_1Au2"}
						ref={refBinding}
						style={{
							borderBottomLeftRadius: 4,
							borderBottomRightRadius: 4,
							borderTopLeftRadius: 4,
							borderTopRightRadius: 4,
							...style,
						}}
						{...addPropertyOverrides(
							{
								"SpKqW8P1p-pressed": {
									"data-framer-name": void 0,
								},
								pO2Tp9wq6: {
									"data-framer-name": "Variant Dot Hover",
								},
								SpKqW8P1p: {
									"data-framer-name": "Variant Dot",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-ibtjd7"}
							data-border={true}
							layoutDependency={layoutDependency}
							layoutId={"RtK1gm86I"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor: "rgba(0, 0, 0, 0)",
								borderBottomLeftRadius: 4,
								borderBottomRightRadius: 4,
								borderTopLeftRadius: 4,
								borderTopRightRadius: 4,
							}}
							variants={{
								pO2Tp9wq6: {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor: "rgba(0, 0, 0, 0)",
									borderBottomLeftRadius: 36,
									borderBottomRightRadius: 36,
									borderTopLeftRadius: 36,
									borderTopRightRadius: 36,
								},
								SpKqW8P1p: {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor:
										"var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255))",
									borderBottomLeftRadius: 6,
									borderBottomRightRadius: 6,
									borderTopLeftRadius: 6,
									borderTopRightRadius: 6,
								},
							}}
						>
							{isDisplayed() && (
								<RichText
									__fromCanvasComponent={true}
									className={"framer-106kbyz"}
									data-framer-name={"Hello"}
									fonts={["FS;JetBrains Mono-semibold"]}
									layoutDependency={layoutDependency}
									layoutId={"h5msZC5ZV"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										opacity: 1,
									}}
									variants={{
										SpKqW8P1p: {
											opacity: 0,
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector":
													"RlM7SmV0QnJhaW5zIE1vbm8tc2VtaWJvbGQ=",
												"--framer-font-family":
													'"JetBrains Mono", "JetBrains Mono Placeholder", sans-serif',
												"--framer-font-weight": "600",
												"--framer-letter-spacing": "-0.05em",
												"--framer-line-height": "1em",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255)))",
												"--framer-text-transform": "uppercase",
											}}
										>
											{"Hello"}
										</motion.p>
									</React.Fragment>
								</RichText>
							)}
							{isDisplayed1() && (
								<SVG
									className={"framer-p8qe3"}
									data-framer-name={"Graphic"}
									fill={"black"}
									intrinsicHeight={48}
									intrinsicWidth={48}
									layoutDependency={layoutDependency}
									layoutId={"QwO0gAiCZ"}
									svg={
										'<svg width="48" height="48" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M29.06 24A5.05 5.05 0 0 1 24 29.05 5.05 5.05 0 0 1 18.94 24a5.06 5.06 0 1 1 10.12 0ZM48 24c0 13.25-10.74 24-24 24S0 37.25 0 24 10.75 0 24 0s24 10.74 24 24Zm-7.25 0S33.25 13.6 24 13.6 7.26 24 7.26 24 14.76 34.39 24 34.39C33.24 34.39 40.75 24 40.75 24Z" fill="#fff"/></svg>'
									}
									withExternalLayout={true}
								/>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-5m7B7.framer-19njgvj, .framer-5m7B7 .framer-19njgvj { display: block; }",
	".framer-5m7B7.framer-1jk02m5 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; mix-blend-mode: difference; overflow: hidden; padding: 0px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-5m7B7 .framer-ibtjd7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 4px 6px 4px 6px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-5m7B7 .framer-106kbyz { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-5m7B7 .framer-p8qe3 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 48px); position: relative; width: 48px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-5m7B7.framer-1jk02m5, .framer-5m7B7 .framer-ibtjd7 { gap: 0px; } .framer-5m7B7.framer-1jk02m5 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-5m7B7.framer-1jk02m5 > :first-child { margin-left: 0px; } .framer-5m7B7.framer-1jk02m5 > :last-child { margin-right: 0px; } .framer-5m7B7 .framer-ibtjd7 > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-5m7B7 .framer-ibtjd7 > :first-child { margin-top: 0px; } .framer-5m7B7 .framer-ibtjd7 > :last-child { margin-bottom: 0px; } }",
	".framer-5m7B7.framer-v-1avthkb.framer-1jk02m5 { cursor: pointer; }",
	".framer-5m7B7.framer-v-1avthkb .framer-ibtjd7 { height: 12px; padding: 0px; width: 12px; }",
	".framer-5m7B7.framer-v-14fondl .framer-ibtjd7 { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 48px); padding: 0px; width: 48px; }",
	".framer-5m7B7.framer-v-14fondl .framer-p8qe3 { order: 1; }",
	".framer-5m7B7.framer-v-1avthkb.pressed .framer-ibtjd7 { height: 6px; width: 6px; }",
	'.framer-5m7B7[data-border="true"]::after, .framer-5m7B7 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerpFw_HLczq = withCSS(Component, css, "framer-5m7B7");
var stdin_default = FramerpFw_HLczq;
FramerpFw_HLczq.displayName = "Cursor";
FramerpFw_HLczq.defaultProps = {
	height: 24,
	width: 56,
};
addPropertyControls(FramerpFw_HLczq, {
	variant: {
		options: ["bZJV_1Au2", "SpKqW8P1p", "pO2Tp9wq6"],
		optionTitles: ["Variant Hello", "Variant Dot", "Variant Dot Hover"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerpFw_HLczq,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "JetBrains Mono",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/46G6Z5EVCZ42UYB746MDPUHE5JNFO2H5/B3L443IEKEYZR6IUA5H7G3HXQY6MFJYR/C4X2AZFIU7APBBKUZ2X4AGSKANOLALFP.woff2",
					weight: "600",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cursor
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CursorFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var cursor_default = ComponentWithRoot;
export { cursor_default as default };
