// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e9f968b120b46161 "Odin Project", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' // Variant
 * titleName1?: string // Title Name 1
 * onvIfB7AC7uChange?: any // onvIfB7AC7uChange
 * titleName2?: string // Title Name 2
 * onTeRVY7u1nChange?: any // onTeRVY7u1nChange
 * titleName3?: string // Title Name 3
 * onuf89OexKyChange?: any // onuf89OexKyChange
 * link?: string // Link
 * link2?: string // Link 2
 * link3?: string // Link 3
 * socialName1?: string // Social Name 1
 * onRaJd9_DyLCHange?: any // onRaJd9_DyLCHange
 * socialName2?: string // Social Name 2
 * onEZJI4eNx2Change?: any // onEZJI4eNx2Change
 * socialName3?: string // Social Name 3
 * onQ8xWqbXBECHange?: any // onQ8xWqbXBECHange
 * socialLink1?: string // Social Link 1
 * socialLink2?: string // Social Link 2
 * socialLink4?: string // Social Link 4
 * address?: string // Address
 * onPBDTDGPvqChange?: any // onPBDTDGPvqChange
 * location?: string // Location
 * onLQFOVAYlRCHange?: any // onLQFOVAYlRCHange
 * country?: string // Country
 * onAkZHFKsGHCHange?: any // onAkZHFKsGHCHange
 * copyright?: string // Copyright
 * onMJC5GCSTYChange?: any // onMJC5GCSTYChange
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-ZWC5X5L3.js";
import { className, css, fonts } from "./chunks/chunk-YFGASGYH.js";
import { routes } from "./chunks/chunk-3DUKK5YU.js";

// virtual:footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/pzQIO7n5oyQ20k6bwSuy/lYgp4zviWjGFpKl0hnSp/DW1HunZ74.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/iYYoXXG8g3peYcEjf5Vv/MsrZhHxpg66HJTgZh3xg/mCKVqgU0z.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;Poppins-regular",
	"FS;Poppins-bold",
	"FS;Poppins-bold italic",
	"FS;Poppins-italic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Poppins",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/NC2MP33RO4WQTSTEEAWBJLAEXNCNEQVF/7F4U3COKLHQH4WUH3AXPC7N4UELEWJQN/JMWNCAGBH3TLANIVQPVABVAVNV5QERTH.woff2",
				weight: "400",
			},
			{
				family: "Poppins",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/EOHGWBZYYKO6R4PWP4S2B3FFWHHBEZN6/UWQLMF4AFWLXCJQCFV3WRVYC77KZXPRB/FYG6OCH7XOLUUSZTIZE65ATBZWF623O4.woff2",
				weight: "700",
			},
			{
				family: "Poppins",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/JQL34MORONR7D7BXOVTX3KBGJGEJQ5BJ/CKUZVY5SFANCFAT7FS3MP6ZL4BMEWCJE/NOLRWF3JBJ434MILPG5RB6R2B4HGRSZB.woff2",
				weight: "700",
			},
			{
				family: "Poppins",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/7LLTLAW3NRWOADG4II2JGKZC6OSEMBQC/EYFXWX77PEMPU645EAWOTG22E375GULW/SSNNTU67MMJH4CSWT443B4KJ7OB4WFHF.woff2",
				weight: "400",
			},
		],
	},
];
var css3 = [
	`.framer-Kz5bN .framer-styles-preset-lbnqn7:not(.rich-text-wrapper), .framer-Kz5bN .framer-styles-preset-lbnqn7.rich-text-wrapper p { --framer-font-family: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-c42a75fd-bb9a-47e3-a5a0-31a6cc9f056a, #71717a); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
];
var className3 = "framer-Kz5bN";

// /:https://framerusercontent.com/modules/pzQIO7n5oyQ20k6bwSuy/lYgp4zviWjGFpKl0hnSp/DW1HunZ74.js
var cycleOrder = ["s2fqnj4uM", "hw2DTPJEH"];
var serializationHash = "framer-TZlZW";
var variantClassNames = {
	hw2DTPJEH: "framer-v-15pnoiw",
	s2fqnj4uM: "framer-v-16pj96t",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	damping: 50,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	y: -5,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "s2fqnj4uM",
	Phone: "hw2DTPJEH",
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	address,
	copyright,
	country,
	height,
	id,
	link,
	link2,
	link3,
	location,
	socialLink1,
	socialLink2,
	socialLink4,
	socialName1,
	socialName2,
	socialName3,
	titleName1,
	titleName2,
	titleName3,
	width,
	...props
}) => {
	return {
		...props,
		ABtG8b4Zz: socialLink1 ?? props.ABtG8b4Zz,
		AkZHFksGH: country ?? props.AkZHFksGH ?? "Country",
		EZJI4eNx2: socialName2 ?? props.EZJI4eNx2 ?? "Social Name 2",
		FQ17i7gfZ: socialLink2 ?? props.FQ17i7gfZ,
		GzslWh8uY: link2 ?? props.GzslWh8uY,
		LQFOVAylR: location ?? props.LQFOVAylR ?? "Location",
		MJC5GCSTy: copyright ?? props.MJC5GCSTy ?? "odeenaka@gmail.com",
		PBdTDgPvq: address ?? props.PBdTDgPvq ?? "Address",
		Q8xWqbXBE: socialName3 ?? props.Q8xWqbXBE ?? "Social Name 3",
		RaJd9_DyL: socialName1 ?? props.RaJd9_DyL ?? "Social Name 1",
		t3e6PPas3: link3 ?? props.t3e6PPas3,
		TeRVy7u1n: titleName2 ?? props.TeRVy7u1n ?? "Title Name 2",
		uf89OexKy: titleName3 ?? props.uf89OexKy ?? "Title Name 3",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "s2fqnj4uM",
		vIfB7AC7u: titleName1 ?? props.vIfB7AC7u ?? "Title Name 1",
		YugKf_bEl: link ?? props.YugKf_bEl,
		zEzdjfMHY: socialLink4 ?? props.zEzdjfMHY,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		vIfB7AC7u: vIfB7AC7u2,
		TeRVy7u1n: TeRVy7u1n2,
		uf89OexKy: uf89OexKy2,
		YugKf_bEl: YugKf_bEl2,
		GzslWh8uY: GzslWh8uY2,
		t3e6PPas3: t3e6PPas32,
		RaJd9_DyL: RaJd9_DyL2,
		EZJI4eNx2: EZJI4eNx22,
		Q8xWqbXBE: Q8xWqbXBE2,
		ABtG8b4Zz: ABtG8b4Zz2,
		FQ17i7gfZ: FQ17i7gfZ2,
		zEzdjfMHY: zEzdjfMHY2,
		PBdTDgPvq: PBdTDgPvq2,
		LQFOVAylR: LQFOVAylR2,
		AkZHFksGH: AkZHFksGH2,
		MJC5GCSTy: MJC5GCSTy2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "s2fqnj4uM",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className3, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "hw2DTPJEH") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "hw2DTPJEH") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.footer
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-16pj96t",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"s2fqnj4uM"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(0, 0, 0)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								hw2DTPJEH: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-zjadty"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"WXzrO4ZD1"}
						>
							<motion.div
								className={"framer-18t6tqo"}
								data-framer-name={"About"}
								layoutDependency={layoutDependency}
								layoutId={"caGsO1MMX"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-a58jyt"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"W3kGCl6PV"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											hw2DTPJEH: {
												children: (
													<React.Fragment>
														<motion.h6
															className={"framer-styles-preset-vif74l"}
															data-styles-preset={"eKbH3HTQS"}
														>
															{"Content"}
														</motion.h6>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.h6
											className={"framer-styles-preset-vif74l"}
											data-styles-preset={"eKbH3HTQS"}
										>
											{"About"}
										</motion.h6>
									</React.Fragment>
								</RichText>
								<motion.div
									className={"framer-1mvqf0c"}
									data-framer-name={"Links"}
									layoutDependency={layoutDependency}
									layoutId={"h732OVQH9"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1vhv34i"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"M88yzvwPD"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										text={vIfB7AC7u2}
										variants={{
											hw2DTPJEH: {
												"--extracted-r6o4lv":
													"var(--token-9c1506ba-d844-4c3d-95bb-d906caf7bec0, rgb(148, 163, 184))",
											},
										}}
										verticalAlignment={"top"}
										whileHover={animation}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												hw2DTPJEH: {
													children: (
														<React.Fragment>
															<motion.p
																style={{
																	"--font-selector": "R0Y7SW50ZXItcmVndWxhcg==",
																	"--framer-font-family":
																		'"Inter", "Inter Placeholder", sans-serif',
																	"--framer-font-size": "14px",
																	"--framer-letter-spacing": "-0.02em",
																	"--framer-line-height": "1.6em",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-9c1506ba-d844-4c3d-95bb-d906caf7bec0, rgb(148, 163, 184)))",
																}}
															>
																<Link
																	href={YugKf_bEl2}
																	motionChild={true}
																	nodeId={"M88yzvwPD"}
																	openInNewTab={false}
																	relValues={[]}
																	scopeId={"DW1HunZ74"}
																	smoothScroll={false}
																>
																	<motion.a
																		className={"framer-styles-preset-cnadud"}
																		data-styles-preset={"KfHwEVY0D"}
																	>
																		{"Link Title"}
																	</motion.a>
																</Link>
															</motion.p>
														</React.Fragment>
													),
													fonts: ["GF;Inter-regular"],
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-lbnqn7"}
												data-styles-preset={"mCKVqgU0z"}
											>
												<Link
													href={YugKf_bEl2}
													motionChild={true}
													nodeId={"M88yzvwPD"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"DW1HunZ74"}
													smoothScroll={false}
												>
													<motion.a
														className={"framer-styles-preset-cnadud"}
														data-styles-preset={"KfHwEVY0D"}
													>
														{"Link Title"}
													</motion.a>
												</Link>
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1eerwuc"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"WRL0tWkIW"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										text={TeRVy7u1n2}
										variants={{
											hw2DTPJEH: {
												"--extracted-r6o4lv":
													"var(--token-9c1506ba-d844-4c3d-95bb-d906caf7bec0, rgb(148, 163, 184))",
											},
										}}
										verticalAlignment={"top"}
										whileHover={animation}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												hw2DTPJEH: {
													children: (
														<React.Fragment>
															<motion.p
																style={{
																	"--font-selector": "R0Y7SW50ZXItcmVndWxhcg==",
																	"--framer-font-family":
																		'"Inter", "Inter Placeholder", sans-serif',
																	"--framer-font-size": "14px",
																	"--framer-letter-spacing": "-0.02em",
																	"--framer-line-height": "1.6em",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-9c1506ba-d844-4c3d-95bb-d906caf7bec0, rgb(148, 163, 184)))",
																}}
															>
																<Link
																	href={GzslWh8uY2}
																	motionChild={true}
																	nodeId={"WRL0tWkIW"}
																	openInNewTab={false}
																	relValues={[]}
																	scopeId={"DW1HunZ74"}
																	smoothScroll={false}
																>
																	<motion.a
																		className={"framer-styles-preset-cnadud"}
																		data-styles-preset={"KfHwEVY0D"}
																	>
																		{"Link Title 2"}
																	</motion.a>
																</Link>
															</motion.p>
														</React.Fragment>
													),
													fonts: ["GF;Inter-regular"],
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-lbnqn7"}
												data-styles-preset={"mCKVqgU0z"}
											>
												<Link
													href={GzslWh8uY2}
													motionChild={true}
													nodeId={"WRL0tWkIW"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"DW1HunZ74"}
													smoothScroll={false}
												>
													<motion.a
														className={"framer-styles-preset-cnadud"}
														data-styles-preset={"KfHwEVY0D"}
													>
														{"Link Title 2"}
													</motion.a>
												</Link>
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-ja9pkl"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"LI60hBjZG"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										text={uf89OexKy2}
										variants={{
											hw2DTPJEH: {
												"--extracted-r6o4lv":
													"var(--token-9c1506ba-d844-4c3d-95bb-d906caf7bec0, rgb(148, 163, 184))",
											},
										}}
										verticalAlignment={"top"}
										whileHover={animation}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												hw2DTPJEH: {
													children: (
														<React.Fragment>
															<motion.p
																style={{
																	"--font-selector": "R0Y7SW50ZXItcmVndWxhcg==",
																	"--framer-font-family":
																		'"Inter", "Inter Placeholder", sans-serif',
																	"--framer-font-size": "14px",
																	"--framer-letter-spacing": "-0.02em",
																	"--framer-line-height": "1.6em",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-9c1506ba-d844-4c3d-95bb-d906caf7bec0, rgb(148, 163, 184)))",
																}}
															>
																<Link
																	href={t3e6PPas32}
																	motionChild={true}
																	nodeId={"LI60hBjZG"}
																	openInNewTab={false}
																	relValues={[]}
																	scopeId={"DW1HunZ74"}
																	smoothScroll={false}
																>
																	<motion.a
																		className={"framer-styles-preset-cnadud"}
																		data-styles-preset={"KfHwEVY0D"}
																	>
																		{"Link Title 3"}
																	</motion.a>
																</Link>
															</motion.p>
														</React.Fragment>
													),
													fonts: ["GF;Inter-regular"],
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-lbnqn7"}
												data-styles-preset={"mCKVqgU0z"}
											>
												<Link
													href={t3e6PPas32}
													motionChild={true}
													nodeId={"LI60hBjZG"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"DW1HunZ74"}
													smoothScroll={false}
												>
													<motion.a
														className={"framer-styles-preset-cnadud"}
														data-styles-preset={"KfHwEVY0D"}
													>
														{"Link Title 3"}
													</motion.a>
												</Link>
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-rmul6z"}
								data-framer-name={"Location"}
								layoutDependency={layoutDependency}
								layoutId={"mOqgBhITr"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1xi50ek"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"xVOsBxxHP"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h6
											className={"framer-styles-preset-vif74l"}
											data-styles-preset={"eKbH3HTQS"}
										>
											{"Location"}
										</motion.h6>
									</React.Fragment>
								</RichText>
								<motion.div
									className={"framer-1o37d9a"}
									data-framer-name={"Info"}
									layoutDependency={layoutDependency}
									layoutId={"J_QWt443u"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-19n5cb2"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"aghOsUZdn"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={PBdTDgPvq2}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												hw2DTPJEH: {
													children: (
														<React.Fragment>
															<motion.p
																style={{
																	"--font-selector": "R0Y7SW50ZXItcmVndWxhcg==",
																	"--framer-font-family":
																		'"Inter", "Inter Placeholder", sans-serif',
																	"--framer-font-size": "14px",
																	"--framer-letter-spacing": "-0.02em",
																	"--framer-line-height": "1.6em",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255)))",
																}}
															>
																{"Address"}
															</motion.p>
														</React.Fragment>
													),
													fonts: ["GF;Inter-regular"],
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-lbnqn7"}
												data-styles-preset={"mCKVqgU0z"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255)))",
												}}
											>
												{"Address"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-3ckcf7"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"XGN2Kfuji"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={LQFOVAylR2}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												hw2DTPJEH: {
													children: (
														<React.Fragment>
															<motion.p
																style={{
																	"--font-selector": "R0Y7SW50ZXItcmVndWxhcg==",
																	"--framer-font-family":
																		'"Inter", "Inter Placeholder", sans-serif',
																	"--framer-font-size": "14px",
																	"--framer-letter-spacing": "-0.02em",
																	"--framer-line-height": "1.6em",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255)))",
																}}
															>
																{"Location"}
															</motion.p>
														</React.Fragment>
													),
													fonts: ["GF;Inter-regular"],
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-lbnqn7"}
												data-styles-preset={"mCKVqgU0z"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255)))",
												}}
											>
												{"Location"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1yf6y0h"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"EosDQYeVM"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={AkZHFksGH2}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												hw2DTPJEH: {
													children: (
														<React.Fragment>
															<motion.p
																style={{
																	"--font-selector": "R0Y7SW50ZXItcmVndWxhcg==",
																	"--framer-font-family":
																		'"Inter", "Inter Placeholder", sans-serif',
																	"--framer-font-size": "14px",
																	"--framer-letter-spacing": "-0.02em",
																	"--framer-line-height": "1.6em",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255)))",
																}}
															>
																{"Country"}
															</motion.p>
														</React.Fragment>
													),
													fonts: ["GF;Inter-regular"],
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-lbnqn7"}
												data-styles-preset={"mCKVqgU0z"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255)))",
												}}
											>
												{"Country"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							{isDisplayed() && (
								<motion.div
									className={"framer-1dwpmpu"}
									data-framer-name={"Text"}
									layoutDependency={layoutDependency}
									layoutId={"MyoJAVdHi"}
								>
									<motion.div
										className={"framer-1cwf8gy"}
										data-framer-name={"Wrap"}
										layoutDependency={layoutDependency}
										layoutId={"cvY2T_zwO"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-izxrzb"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"n7oj_ee5O"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={MJC5GCSTy2}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.h6
													className={"framer-styles-preset-vif74l"}
													data-styles-preset={"eKbH3HTQS"}
												>
													{"2025 \xA9 PureStudio"}
												</motion.h6>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
							)}
						</motion.div>
						{isDisplayed1() && (
							<motion.div
								className={"framer-13ccbpj"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"udLKMAfuh"}
							>
								<motion.div
									className={"framer-8l00oj"}
									data-framer-name={"Socials"}
									layoutDependency={layoutDependency}
									layoutId={"iM3RcXQvU"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1orpu7g"}
										data-framer-name={"Socials"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"AR8Knxd6q"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												hw2DTPJEH: {
													children: (
														<React.Fragment>
															<motion.h6
																className={"framer-styles-preset-vif74l"}
																data-styles-preset={"eKbH3HTQS"}
																dir={"auto"}
															>
																{"CONTACT"}
															</motion.h6>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.h6
												className={"framer-styles-preset-vif74l"}
												data-styles-preset={"eKbH3HTQS"}
											>
												{"Socials"}
											</motion.h6>
										</React.Fragment>
									</RichText>
									<motion.div
										className={"framer-1apcb7u"}
										data-framer-name={"Links"}
										layoutDependency={layoutDependency}
										layoutId={"rl61hQb_V"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-qomkop"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"OrzmW_4r1"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											text={RaJd9_DyL2}
											variants={{
												hw2DTPJEH: {
													"--extracted-r6o4lv":
														"var(--token-9c1506ba-d844-4c3d-95bb-d906caf7bec0, rgb(148, 163, 184))",
												},
											}}
											verticalAlignment={"top"}
											whileHover={animation}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													hw2DTPJEH: {
														children: (
															<React.Fragment>
																<motion.p
																	style={{
																		"--font-selector":
																			"R0Y7SW50ZXItcmVndWxhcg==",
																		"--framer-font-family":
																			'"Inter", "Inter Placeholder", sans-serif',
																		"--framer-font-size": "14px",
																		"--framer-letter-spacing": "-0.02em",
																		"--framer-line-height": "1.6em",
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-9c1506ba-d844-4c3d-95bb-d906caf7bec0, rgb(148, 163, 184)))",
																	}}
																>
																	<Link
																		href={ABtG8b4Zz2}
																		motionChild={true}
																		nodeId={"OrzmW_4r1"}
																		openInNewTab={true}
																		relValues={[]}
																		scopeId={"DW1HunZ74"}
																		smoothScroll={false}
																	>
																		<motion.a
																			className={"framer-styles-preset-cnadud"}
																			data-styles-preset={"KfHwEVY0D"}
																		>
																			{"Social Name 1"}
																		</motion.a>
																	</Link>
																</motion.p>
															</React.Fragment>
														),
														fonts: ["GF;Inter-regular"],
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-lbnqn7"}
													data-styles-preset={"mCKVqgU0z"}
												>
													<Link
														href={ABtG8b4Zz2}
														motionChild={true}
														nodeId={"OrzmW_4r1"}
														openInNewTab={true}
														relValues={[]}
														scopeId={"DW1HunZ74"}
														smoothScroll={false}
													>
														<motion.a
															className={"framer-styles-preset-cnadud"}
															data-styles-preset={"KfHwEVY0D"}
														>
															{"Social Name 1"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1maq6ki"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"uL3DQleYa"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											text={EZJI4eNx22}
											variants={{
												hw2DTPJEH: {
													"--extracted-r6o4lv":
														"var(--token-9c1506ba-d844-4c3d-95bb-d906caf7bec0, rgb(148, 163, 184))",
												},
											}}
											verticalAlignment={"top"}
											whileHover={animation}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													hw2DTPJEH: {
														children: (
															<React.Fragment>
																<motion.p
																	style={{
																		"--font-selector":
																			"R0Y7SW50ZXItcmVndWxhcg==",
																		"--framer-font-family":
																			'"Inter", "Inter Placeholder", sans-serif',
																		"--framer-font-size": "14px",
																		"--framer-letter-spacing": "-0.02em",
																		"--framer-line-height": "1.6em",
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-9c1506ba-d844-4c3d-95bb-d906caf7bec0, rgb(148, 163, 184)))",
																	}}
																>
																	<Link
																		href={FQ17i7gfZ2}
																		motionChild={true}
																		nodeId={"uL3DQleYa"}
																		openInNewTab={true}
																		relValues={[]}
																		scopeId={"DW1HunZ74"}
																		smoothScroll={false}
																	>
																		<motion.a
																			className={"framer-styles-preset-cnadud"}
																			data-styles-preset={"KfHwEVY0D"}
																		>
																			{"Social Name 2"}
																		</motion.a>
																	</Link>
																</motion.p>
															</React.Fragment>
														),
														fonts: ["GF;Inter-regular"],
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-lbnqn7"}
													data-styles-preset={"mCKVqgU0z"}
												>
													<Link
														href={FQ17i7gfZ2}
														motionChild={true}
														nodeId={"uL3DQleYa"}
														openInNewTab={true}
														relValues={[]}
														scopeId={"DW1HunZ74"}
														smoothScroll={false}
													>
														<motion.a
															className={"framer-styles-preset-cnadud"}
															data-styles-preset={"KfHwEVY0D"}
														>
															{"Social Name 2"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-i7s96p"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"YqIEfDAlr"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											text={Q8xWqbXBE2}
											variants={{
												hw2DTPJEH: {
													"--extracted-r6o4lv":
														"var(--token-9c1506ba-d844-4c3d-95bb-d906caf7bec0, rgb(148, 163, 184))",
												},
											}}
											verticalAlignment={"top"}
											whileHover={animation}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													hw2DTPJEH: {
														children: (
															<React.Fragment>
																<motion.p
																	style={{
																		"--font-selector":
																			"R0Y7SW50ZXItcmVndWxhcg==",
																		"--framer-font-family":
																			'"Inter", "Inter Placeholder", sans-serif',
																		"--framer-font-size": "14px",
																		"--framer-letter-spacing": "-0.02em",
																		"--framer-line-height": "1.6em",
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-9c1506ba-d844-4c3d-95bb-d906caf7bec0, rgb(148, 163, 184)))",
																	}}
																>
																	<Link
																		href={zEzdjfMHY2}
																		motionChild={true}
																		nodeId={"YqIEfDAlr"}
																		openInNewTab={true}
																		relValues={[]}
																		scopeId={"DW1HunZ74"}
																		smoothScroll={false}
																	>
																		<motion.a
																			className={"framer-styles-preset-cnadud"}
																			data-styles-preset={"KfHwEVY0D"}
																		>
																			{"Social Name 3"}
																		</motion.a>
																	</Link>
																</motion.p>
															</React.Fragment>
														),
														fonts: ["GF;Inter-regular"],
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-lbnqn7"}
													data-styles-preset={"mCKVqgU0z"}
												>
													<Link
														href={zEzdjfMHY2}
														motionChild={true}
														nodeId={"YqIEfDAlr"}
														openInNewTab={true}
														relValues={[]}
														scopeId={"DW1HunZ74"}
														smoothScroll={false}
													>
														<motion.a
															className={"framer-styles-preset-cnadud"}
															data-styles-preset={"KfHwEVY0D"}
														>
															{"Social Name 3"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-mfa9km"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"v22hNuNd4"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={MJC5GCSTy2}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-lbnqn7"}
													data-styles-preset={"mCKVqgU0z"}
													dir={"auto"}
													style={{
														"--framer-text-alignment": "center",
													}}
												>
													{"odeenaka@gmail.com"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<motion.div
											className={"framer-10d1dzt"}
											data-framer-name={"Wrap"}
											layoutDependency={layoutDependency}
											layoutId={"FfBr6Ndde"}
										/>
									</motion.div>
								</motion.div>
							</motion.div>
						)}
					</motion.footer>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-TZlZW.framer-1ljq354, .framer-TZlZW .framer-1ljq354 { display: block; }",
	".framer-TZlZW.framer-16pj96t { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 60px 0px 60px 0px; position: relative; width: 1440px; }",
	".framer-TZlZW .framer-zjadty { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px 40px 0px 40px; position: relative; width: 100%; }",
	".framer-TZlZW .framer-18t6tqo, .framer-TZlZW .framer-rmul6z { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 25%; }",
	".framer-TZlZW .framer-a58jyt, .framer-TZlZW .framer-1xi50ek, .framer-TZlZW .framer-19n5cb2, .framer-TZlZW .framer-3ckcf7, .framer-TZlZW .framer-1yf6y0h, .framer-TZlZW .framer-izxrzb, .framer-TZlZW .framer-1orpu7g { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-TZlZW .framer-1mvqf0c, .framer-TZlZW .framer-1o37d9a { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-TZlZW .framer-1vhv34i, .framer-TZlZW .framer-1eerwuc, .framer-TZlZW .framer-ja9pkl, .framer-TZlZW .framer-qomkop, .framer-TZlZW .framer-1maq6ki, .framer-TZlZW .framer-i7s96p { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; will-change: var(--framer-will-change-effect-override, transform); }",
	".framer-TZlZW .framer-1dwpmpu { align-content: flex-end; align-items: flex-end; align-self: stretch; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: auto; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: 25%; }",
	".framer-TZlZW .framer-1cwf8gy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-TZlZW .framer-13ccbpj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px 40px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 20px 0px 20px; position: relative; width: 390px; }",
	".framer-TZlZW .framer-8l00oj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-TZlZW .framer-1apcb7u { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-TZlZW .framer-mfa9km { flex: none; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-TZlZW .framer-10d1dzt { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 13px; height: min-content; justify-content: center; min-height: 23px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-TZlZW.framer-v-15pnoiw.framer-16pj96t { width: 390px; }",
	".framer-TZlZW.framer-v-15pnoiw .framer-zjadty { align-content: unset; align-items: unset; display: grid; gap: 40px 40px; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(2, minmax(50px, 1fr)); grid-template-rows: repeat(1, minmax(0, 1fr)); justify-content: center; order: 1; padding: 13px; width: 390px; }",
	".framer-TZlZW.framer-v-15pnoiw .framer-18t6tqo, .framer-TZlZW.framer-v-15pnoiw .framer-rmul6z { align-self: start; justify-self: start; width: 100%; }",
	".framer-TZlZW.framer-v-15pnoiw .framer-13ccbpj, .framer-TZlZW.framer-v-15pnoiw .framer-8l00oj { order: 0; }",
	...css,
	...css3,
	...css2,
];
var FramerDW1HunZ74 = withCSS(Component, css4, "framer-TZlZW");
var stdin_default = FramerDW1HunZ74;
FramerDW1HunZ74.displayName = "Footer";
FramerDW1HunZ74.defaultProps = {
	height: 225,
	width: 1440,
};
addPropertyControls(FramerDW1HunZ74, {
	variant: {
		options: ["s2fqnj4uM", "hw2DTPJEH"],
		optionTitles: ["Desktop", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	vIfB7AC7u: {
		defaultValue: "Title Name 1",
		displayTextArea: false,
		title: "Title Name 1",
		type: ControlType.String,
	},
	onvIfB7AC7uChange: {
		changes: "vIfB7AC7u",
		type: ControlType.ChangeHandler,
	},
	TeRVy7u1n: {
		defaultValue: "Title Name 2",
		displayTextArea: false,
		title: "Title Name 2",
		type: ControlType.String,
	},
	onTeRVy7u1nChange: {
		changes: "TeRVy7u1n",
		type: ControlType.ChangeHandler,
	},
	uf89OexKy: {
		defaultValue: "Title Name 3",
		displayTextArea: false,
		title: "Title Name 3",
		type: ControlType.String,
	},
	onuf89OexKyChange: {
		changes: "uf89OexKy",
		type: ControlType.ChangeHandler,
	},
	YugKf_bEl: {
		title: "Link",
		type: ControlType.Link,
	},
	GzslWh8uY: {
		title: "Link 2",
		type: ControlType.Link,
	},
	t3e6PPas3: {
		title: "Link 3",
		type: ControlType.Link,
	},
	RaJd9_DyL: {
		defaultValue: "Social Name 1",
		displayTextArea: false,
		title: "Social Name 1",
		type: ControlType.String,
	},
	onRaJd9_DyLChange: {
		changes: "RaJd9_DyL",
		type: ControlType.ChangeHandler,
	},
	EZJI4eNx2: {
		defaultValue: "Social Name 2",
		displayTextArea: false,
		title: "Social Name 2",
		type: ControlType.String,
	},
	onEZJI4eNx2Change: {
		changes: "EZJI4eNx2",
		type: ControlType.ChangeHandler,
	},
	Q8xWqbXBE: {
		defaultValue: "Social Name 3",
		displayTextArea: false,
		title: "Social Name 3",
		type: ControlType.String,
	},
	onQ8xWqbXBEChange: {
		changes: "Q8xWqbXBE",
		type: ControlType.ChangeHandler,
	},
	ABtG8b4Zz: {
		title: "Social Link 1",
		type: ControlType.Link,
	},
	FQ17i7gfZ: {
		title: "Social Link 2",
		type: ControlType.Link,
	},
	zEzdjfMHY: {
		title: "Social Link 4",
		type: ControlType.Link,
	},
	PBdTDgPvq: {
		defaultValue: "Address",
		displayTextArea: false,
		title: "Address",
		type: ControlType.String,
	},
	onPBdTDgPvqChange: {
		changes: "PBdTDgPvq",
		type: ControlType.ChangeHandler,
	},
	LQFOVAylR: {
		defaultValue: "Location",
		displayTextArea: false,
		title: "Location",
		type: ControlType.String,
	},
	onLQFOVAylRChange: {
		changes: "LQFOVAylR",
		type: ControlType.ChangeHandler,
	},
	AkZHFksGH: {
		defaultValue: "Country",
		displayTextArea: false,
		title: "Country",
		type: ControlType.String,
	},
	onAkZHFksGHChange: {
		changes: "AkZHFksGH",
		type: ControlType.ChangeHandler,
	},
	MJC5GCSTy: {
		defaultValue: "odeenaka@gmail.com",
		displayTextArea: false,
		title: "Copyright",
		type: ControlType.String,
	},
	onMJC5GCSTyChange: {
		changes: "MJC5GCSTy",
		type: ControlType.ChangeHandler,
	},
});
addFonts(
	FramerDW1HunZ74,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "google",
					style: "normal",
					uiFamilyName: "Inter",
					url: "https://fonts.gstatic.com/s/inter/v20/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuLyfMZ1rib2Bg-4.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "hw2DTPJEH",
	xl: "s2fqnj4uM",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var footer_default = ComponentWithRoot;
export { footer_default as default };
