// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e9f968b120b46161 "Odin Project", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Disabled' | 'Success' | 'Error' // Variant
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-S2GD33AD.js";
import { routes } from "./chunks/chunk-3DUKK5YU.js";

// virtual:form-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/1FuN7l3MrC7mBrFXT84B/jer2IS6ZHFlx2jyYwh7P/GtDQXQq9h.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var enabledGestures = {
	aUzTBUFva: {
		hover: true,
		pressed: true,
	},
};
var cycleOrder = [
	"aUzTBUFva",
	"StOiKZLRf",
	"Pg7W5tRTc",
	"IdAEekcqO",
	"k7PIN0JLH",
];
var serializationHash = "framer-eGd9L";
var variantClassNames = {
	aUzTBUFva: "framer-v-1b6wx8k",
	IdAEekcqO: "framer-v-1mlb18m",
	k7PIN0JLH: "framer-v-elulwa",
	Pg7W5tRTc: "framer-v-z7xiqv",
	StOiKZLRf: "framer-v-i9yirr",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.2,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "aUzTBUFva",
	Disabled: "Pg7W5tRTc",
	Error: "k7PIN0JLH",
	Loading: "StOiKZLRf",
	Success: "IdAEekcqO",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "aUzTBUFva",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "aUzTBUFva",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "StOiKZLRf") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "StOiKZLRf") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.button
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1b6wx8k",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						data-reset={"button"}
						layoutDependency={layoutDependency}
						layoutId={"aUzTBUFva"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255))",
							borderBottomLeftRadius: 4,
							borderBottomRightRadius: 4,
							borderTopLeftRadius: 4,
							borderTopRightRadius: 4,
							opacity: 1,
							...style,
						}}
						variants={{
							"aUzTBUFva-hover": {
								backgroundColor:
									"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
								opacity: 1,
							},
							"aUzTBUFva-pressed": {
								backgroundColor:
									"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
								opacity: 1,
							},
							IdAEekcqO: {
								opacity: 1,
							},
							k7PIN0JLH: {
								backgroundColor: "rgba(255, 34, 68, 0.15)",
								opacity: 1,
							},
							Pg7W5tRTc: {
								opacity: 0.5,
							},
							StOiKZLRf: {
								backgroundColor:
									"var(--token-88c66ff6-b74b-46bd-abb1-37498123a8c9, rgb(39, 39, 42))",
							},
						}}
						{...addPropertyOverrides(
							{
								"aUzTBUFva-hover": {
									"data-framer-name": void 0,
								},
								"aUzTBUFva-pressed": {
									"data-framer-name": void 0,
								},
								IdAEekcqO: {
									"data-framer-name": "Success",
								},
								k7PIN0JLH: {
									"data-framer-name": "Error",
								},
								Pg7W5tRTc: {
									"data-framer-name": "Disabled",
								},
								StOiKZLRf: {
									"data-framer-name": "Loading",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1rz0eiu"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"LXtB2Whrz"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-cc3662e6-3397-466e-9cb2-289050ebc7cb, rgb(0, 0, 0))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								variants={{
									k7PIN0JLH: {
										"--extracted-r6o4lv": "rgb(255, 34, 68)",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										IdAEekcqO: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1lbraru"}
														data-styles-preset={"kMRONeo8r"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-cc3662e6-3397-466e-9cb2-289050ebc7cb, rgb(0, 0, 0)))",
														}}
													>
														{"Thank you"}
													</motion.p>
												</React.Fragment>
											),
										},
										k7PIN0JLH: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
															"--framer-font-family":
																'"Inter", "Inter Placeholder", sans-serif',
															"--framer-font-size": "14px",
															"--framer-font-weight": "600",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 34, 68))",
														}}
													>
														{"Something went wrong"}
													</motion.p>
												</React.Fragment>
											),
											fonts: ["Inter-SemiBold"],
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1lbraru"}
										data-styles-preset={"kMRONeo8r"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-cc3662e6-3397-466e-9cb2-289050ebc7cb, rgb(0, 0, 0)))",
										}}
									>
										{"Submit"}
									</motion.p>
								</React.Fragment>
							</RichText>
						)}
						{isDisplayed1() && (
							<motion.div
								className={"framer-8ry37r"}
								data-framer-name={"Spinner"}
								layoutDependency={layoutDependency}
								layoutId={"I9CNUpjnN"}
								style={{
									mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
									WebkitMask:
										"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
								}}
							>
								<MotionDivWithFX
									__framer__loop={animation}
									__framer__loopEffectEnabled={true}
									__framer__loopRepeatDelay={0}
									__framer__loopRepeatType={"loop"}
									__framer__loopTransition={transition2}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-m2svap"}
									data-framer-name={"Conic"}
									layoutDependency={layoutDependency}
									layoutId={"rh8fUBmVy"}
									style={{
										background:
											"conic-gradient(from 180deg at 50% 50%, rgb(68, 204, 255) 0deg, rgb(68, 204, 255) 360deg)",
										backgroundColor: "rgb(68, 204, 255)",
										mask: "none",
										WebkitMask: "none",
									}}
									variants={{
										StOiKZLRf: {
											background:
												"conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 7.208614864864882deg, rgb(255, 255, 255) 342deg)",
											backgroundColor: "rgba(0, 0, 0, 0)",
											mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
											WebkitMask:
												"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
										},
									}}
								>
									<motion.div
										className={"framer-1ky69e3"}
										data-framer-name={"Rounding"}
										layoutDependency={layoutDependency}
										layoutId={"CLOsJp_Zs"}
										style={{
											backgroundColor: "rgb(255, 255, 255)",
											borderBottomLeftRadius: 1,
											borderBottomRightRadius: 1,
											borderTopLeftRadius: 1,
											borderTopRightRadius: 1,
										}}
										transformTemplate={transformTemplate1}
									/>
								</MotionDivWithFX>
							</motion.div>
						)}
					</motion.button>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-eGd9L.framer-1o40f1x, .framer-eGd9L .framer-1o40f1x { display: block; }",
	".framer-eGd9L.framer-1b6wx8k { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 10px 32px 10px 32px; position: relative; width: min-content; }",
	".framer-eGd9L .framer-1rz0eiu { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-eGd9L .framer-8ry37r { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); overflow: hidden; position: relative; width: 20px; }",
	".framer-eGd9L .framer-m2svap { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-eGd9L .framer-1ky69e3 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 2px); left: 50%; overflow: visible; position: absolute; top: 0px; width: 2px; }",
	".framer-eGd9L.framer-v-i9yirr.framer-1b6wx8k, .framer-eGd9L.framer-v-z7xiqv.framer-1b6wx8k, .framer-eGd9L.framer-v-1mlb18m.framer-1b6wx8k, .framer-eGd9L.framer-v-elulwa.framer-1b6wx8k { cursor: unset; }",
	".framer-eGd9L.framer-v-i9yirr .framer-m2svap { overflow: hidden; }",
	...css,
];
var FramerGtDQXQq9h = withCSS(Component, css2, "framer-eGd9L");
var stdin_default = FramerGtDQXQq9h;
FramerGtDQXQq9h.displayName = "Form Button";
FramerGtDQXQq9h.defaultProps = {
	height: 49,
	width: 120.5,
};
addPropertyControls(FramerGtDQXQq9h, {
	variant: {
		options: ["aUzTBUFva", "StOiKZLRf", "Pg7W5tRTc", "IdAEekcqO", "k7PIN0JLH"],
		optionTitles: ["Default", "Loading", "Disabled", "Success", "Error"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerGtDQXQq9h,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/1ZFS7N918ojhhd0nQWdj3jz4w.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
					weight: "600",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:form-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "aUzTBUFva",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FormButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var form_button_default = ComponentWithRoot;
export { form_button_default as default };
