// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e9f968b120b46161 "Odin Project", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
 * title?: string // Title
 * color?: string // Color
}} Props

 */
import { routes } from "./chunks/chunk-3DUKK5YU.js";

// virtual:heading-title
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/vvJDcVbf7SMflGOgy8hF/mTSu86J9GBQSKC4BkYSR/tklyvfXqV.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/nG5k6JoCUMWVpClTBCWg/ZtY4Ee1R3nHFOnfOxnkD/Vhzv2WVPa.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;JetBrains Mono-bold",
	"FS;JetBrains Mono-extrabold",
	"FS;JetBrains Mono-extrabold italic",
	"FS;JetBrains Mono-bold italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/BTOY6STFL42WXJYET4IAFJ4R4NWQMPYV/SIRJV64UEOICTYN5EECZFJJ3ML2D6HVV/ATU2C7QZBG7GCVXROP265OYM5E55WHMK.woff2",
				weight: "700",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/W2QLP4CHXEAE2UDQ4JZRQSCVGRWTODXQ/IZHRABAMPPUXMZ2PD72AYR3CARBXVTMT/VCHFQIE7HVVHWFPYX3UJFHLWZNFBWMY2.woff2",
				weight: "800",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/CYELXKES646LNQMHDBMMNBTFTS5XYQRB/H7NE6NFMXJ4EIQOOQK2QDHNFWQHSJ62F/HIEFT57NYSYQJX2RC4H6NZCOYVHPMBAL.woff2",
				weight: "800",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/4UER7KOM5ELODXZSILS67WJ47ZOE75JQ/6CQXJGOZP6EVG2LPOOVWXH2KM6JHNSRY/UTZ3OSIQCH2DNRJBPY7UY3LB6YDOZNJX.woff2",
				weight: "700",
			},
		],
	},
];
var css = [
	`.framer-xSyj5 .framer-styles-preset-f8fm9t:not(.rich-text-wrapper), .framer-xSyj5 .framer-styles-preset-f8fm9t.rich-text-wrapper h2 { --framer-font-family: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 72px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 800; --framer-font-weight-bold-italic: 800; --framer-font-weight-italic: 700; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, #e4e4e7); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }`,
	`@media (max-width: 1439px) and (min-width: 767px) { .framer-xSyj5 .framer-styles-preset-f8fm9t:not(.rich-text-wrapper), .framer-xSyj5 .framer-styles-preset-f8fm9t.rich-text-wrapper h2 { --framer-font-family: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 40px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, #e4e4e7); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }`,
	`@media (max-width: 766px) and (min-width: 0px) { .framer-xSyj5 .framer-styles-preset-f8fm9t:not(.rich-text-wrapper), .framer-xSyj5 .framer-styles-preset-f8fm9t.rich-text-wrapper h2 { --framer-font-family: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 28px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, #e4e4e7); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }`,
];
var className = "framer-xSyj5";

// /:https://framerusercontent.com/modules/vvJDcVbf7SMflGOgy8hF/mTSu86J9GBQSKC4BkYSR/tklyvfXqV.js
var RichTextWithFX = withFX(RichText);
var cycleOrder = ["raOa8I8gW", "w9dxAQWUj", "gpsNxj7Mn"];
var serializationHash = "framer-QR360";
var variantClassNames = {
	gpsNxj7Mn: "framer-v-1hcr63w",
	raOa8I8gW: "framer-v-11x0zyf",
	w9dxAQWUj: "framer-v-1whnl7u",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 40,
};
var transition2 = {
	damping: 50,
	delay: 0.2,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 20,
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "raOa8I8gW",
	Phone: "gpsNxj7Mn",
	Tablet: "w9dxAQWUj",
};
var getProps = ({ color, height, id, title, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "raOa8I8gW",
		xa4tJzsvo: title ?? props.xa4tJzsvo ?? "Heading Title",
		XmxGrINEz:
			color ??
			props.XmxGrINEz ??
			"var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255))",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		xa4tJzsvo: xa4tJzsvo2,
		XmxGrINEz: XmxGrINEz2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "raOa8I8gW",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-11x0zyf",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"raOa8I8gW"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								gpsNxj7Mn: {
									"data-framer-name": "Phone",
								},
								w9dxAQWUj: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichTextWithFX
							__framer__animate={{
								transition: transition2,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0.5}
							__fromCanvasComponent={true}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-jpyvp1"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"dBkRxK_lO"}
							style={{
								"--extracted-1of0zx5":
									"var(--variable-reference-XmxGrINEz-tklyvfXqV)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
								"--variable-reference-XmxGrINEz-tklyvfXqV": XmxGrINEz2,
							}}
							text={xa4tJzsvo2}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									gpsNxj7Mn: {
										__framer__enter: animation2,
									},
									w9dxAQWUj: {
										__framer__enter: animation1,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.h2
									className={"framer-styles-preset-f8fm9t"}
									data-styles-preset={"Vhzv2WVPa"}
									style={{
										"--framer-text-color":
											"var(--extracted-1of0zx5, var(--variable-reference-XmxGrINEz-tklyvfXqV))",
									}}
								>
									{"Heading Title"}
								</motion.h2>
							</React.Fragment>
						</RichTextWithFX>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-QR360.framer-1aj4qnh, .framer-QR360 .framer-1aj4qnh { display: block; }",
	".framer-QR360.framer-11x0zyf { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-QR360 .framer-jpyvp1 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css,
];
var FramertklyvfXqV = withCSS(Component, css2, "framer-QR360");
var stdin_default = FramertklyvfXqV;
FramertklyvfXqV.displayName = "Heading Title";
FramertklyvfXqV.defaultProps = {
	height: 86.5,
	width: 561.5,
};
addPropertyControls(FramertklyvfXqV, {
	variant: {
		options: ["raOa8I8gW", "w9dxAQWUj", "gpsNxj7Mn"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	xa4tJzsvo: {
		defaultValue: "Heading Title",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	XmxGrINEz: {
		defaultValue:
			'var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255)) /* {"name":"White"} */',
		title: "Color",
		type: ControlType.Color,
	},
});
addFonts(
	FramertklyvfXqV,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:heading-title
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "gpsNxj7Mn",
	md: "w9dxAQWUj",
	xl: "raOa8I8gW",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeadingTitleFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var heading_title_default = ComponentWithRoot;
export { heading_title_default as default };
