// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e9f968b120b46161 "Odin Project", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' | 'Variant 3' | 'Variant 4' // Variant
 * image1?: {src: string, srcSet?: string, alt?: string} // Image 1
 * image2?: {src: string, srcSet?: string, alt?: string} // Image 2
 * image3?: {src: string, srcSet?: string, alt?: string} // Image 3
}} Props

 */
import { routes } from "./chunks/chunk-3DUKK5YU.js";

// virtual:images-right
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/tm9ZvsaMNNBhyPWJbpKs/jwLhp3GfGaymTBcIgPrf/ayjHFrJ1o.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = ["Li75wqNCN", "nsQrAGGGg", "oYL6tcvq_", "PDuZRCnoK"];
var serializationHash = "framer-gd4n9";
var variantClassNames = {
	Li75wqNCN: "framer-v-1yor8xd",
	nsQrAGGGg: "framer-v-bpwr16",
	oYL6tcvq_: "framer-v-1v6egg",
	PDuZRCnoK: "framer-v-zk016u",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 30,
	delay: 0.2,
	mass: 0.1,
	stiffness: 300,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "Li75wqNCN",
	"Variant 2": "nsQrAGGGg",
	"Variant 3": "oYL6tcvq_",
	"Variant 4": "PDuZRCnoK",
};
var getProps = ({ height, id, image1, image2, image3, width, ...props }) => {
	return {
		...props,
		fypJWowoP: image2 ??
			props.fypJWowoP ?? {
				pixelHeight: 1200,
				pixelWidth: 901,
				src: "https://framerusercontent.com/images/lUz1P3ejN0H231GR4AbA8CuU.jpg?scale-down-to=1024",
				srcSet:
					"https://framerusercontent.com/images/lUz1P3ejN0H231GR4AbA8CuU.jpg?scale-down-to=1024 768w,https://framerusercontent.com/images/lUz1P3ejN0H231GR4AbA8CuU.jpg 901w",
			},
		LhO3u3D1V: image1 ??
			props.LhO3u3D1V ?? {
				pixelHeight: 1200,
				pixelWidth: 904,
				src: "https://framerusercontent.com/images/lgNUpOvykmwAdE57CBamX0bef8.png?scale-down-to=1024",
				srcSet:
					"https://framerusercontent.com/images/lgNUpOvykmwAdE57CBamX0bef8.png?scale-down-to=1024 771w,https://framerusercontent.com/images/lgNUpOvykmwAdE57CBamX0bef8.png 904w",
			},
		um3nNHNxb: image3 ??
			props.um3nNHNxb ?? {
				pixelHeight: 1200,
				pixelWidth: 900,
				src: "https://framerusercontent.com/images/HGbcPTLbYGvKlQDl9jTViqVA4.png?scale-down-to=1024",
				srcSet:
					"https://framerusercontent.com/images/HGbcPTLbYGvKlQDl9jTViqVA4.png?scale-down-to=1024 768w,https://framerusercontent.com/images/HGbcPTLbYGvKlQDl9jTViqVA4.png 900w",
			},
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Li75wqNCN",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		LhO3u3D1V,
		fypJWowoP,
		um3nNHNxb,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Li75wqNCN",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear11k3sl8 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("nsQrAGGGg"), 1e3);
	});
	const onAppear1fzub1b = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("oYL6tcvq_", true), 1e3);
	});
	const onAppear16zmgou = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("PDuZRCnoK"), 1e3);
	});
	const onAppear1mh9asg = activeVariantCallback(async (...args) => {
		setVariant("Li75wqNCN");
	});
	useOnVariantChange(baseVariant, {
		default: onAppear11k3sl8,
		nsQrAGGGg: onAppear1fzub1b,
		oYL6tcvq_: onAppear16zmgou,
		PDuZRCnoK: onAppear1mh9asg,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							scopingClassNames,
							"framer-1yor8xd",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"Li75wqNCN"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								nsQrAGGGg: {
									"data-framer-name": "Variant 2",
								},
								oYL6tcvq_: {
									"data-framer-name": "Variant 3",
								},
								PDuZRCnoK: {
									"data-framer-name": "Variant 4",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 0,
								),
								pixelHeight: 1200,
								pixelWidth: 904,
								sizes: componentViewport?.width || "100vw",
								...toResponsiveImage(LhO3u3D1V),
							}}
							className={"framer-hoynx3"}
							data-framer-name={"Image 1"}
							layoutDependency={layoutDependency}
							layoutId={"Lwu6Ae8H8"}
							style={{
								opacity: 1,
							}}
							variants={{
								nsQrAGGGg: {
									opacity: 0,
								},
								oYL6tcvq_: {
									opacity: 0,
								},
								PDuZRCnoK: {
									opacity: 1,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										((componentViewport?.height || 800) * 0.5000000000000002 -
											((componentViewport?.height || 800) * 1) / 2),
								),
								pixelHeight: 1200,
								pixelWidth: 800,
								sizes: componentViewport?.width || "100vw",
								...toResponsiveImage(fypJWowoP),
							}}
							className={"framer-175m96x"}
							data-framer-name={"Image 2"}
							layoutDependency={layoutDependency}
							layoutId={"bHwVbXMum"}
							style={{
								opacity: 0,
							}}
							variants={{
								nsQrAGGGg: {
									opacity: 1,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 0,
								),
								pixelHeight: 1200,
								pixelWidth: 960,
								sizes: componentViewport?.width || "100vw",
								...toResponsiveImage(um3nNHNxb),
							}}
							className={"framer-4om2ex"}
							data-framer-name={"Image 3"}
							layoutDependency={layoutDependency}
							layoutId={"OVqqf9JWU"}
							style={{
								opacity: 0,
							}}
							variants={{
								oYL6tcvq_: {
									opacity: 1,
								},
							}}
						/>
						<motion.div
							className={"framer-f1b6vo"}
							layoutDependency={layoutDependency}
							layoutId={"RXV1QsnTf"}
							style={{
								backgroundColor: "rgb(255, 255, 255)",
							}}
						/>
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-gd4n9.framer-5b2ypj, .framer-gd4n9 .framer-5b2ypj { display: block; }",
	".framer-gd4n9.framer-1yor8xd { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 800px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 600px; }",
	".framer-gd4n9 .framer-hoynx3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; left: 0px; overflow: visible; padding: 0px; position: absolute; top: 0px; width: 100%; z-index: 3; }",
	".framer-gd4n9 .framer-175m96x { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; left: calc(50.00000000000002% - 100% / 2); overflow: visible; padding: 0px; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 2; }",
	".framer-gd4n9 .framer-4om2ex { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; left: calc(50.00000000000002% - 100% / 2); overflow: visible; padding: 0px; position: absolute; top: 0px; width: 100%; z-index: 1; }",
	".framer-gd4n9 .framer-f1b6vo { flex: 1 0 0px; height: 1px; overflow: hidden; position: relative; width: 100%; z-index: -1; }",
];
var FramerayjHFrJ1o = withCSS(Component, css, "framer-gd4n9");
var stdin_default = FramerayjHFrJ1o;
FramerayjHFrJ1o.displayName = "Images Right";
FramerayjHFrJ1o.defaultProps = {
	height: 800,
	width: 600,
};
addPropertyControls(FramerayjHFrJ1o, {
	variant: {
		options: ["Li75wqNCN", "nsQrAGGGg", "oYL6tcvq_", "PDuZRCnoK"],
		optionTitles: ["Variant 1", "Variant 2", "Variant 3", "Variant 4"],
		title: "Variant",
		type: ControlType.Enum,
	},
	LhO3u3D1V: {
		__defaultAssetReference:
			"data:framer/asset-reference,lgNUpOvykmwAdE57CBamX0bef8.png?originalFilename=QmSXPQqyigBJgLabbeX933zSsWokBoGh9Tdc9NKYP54g8M%3Fauto%3Dformat%26h%3D1200.png&preferredSize=auto",
		title: "Image 1",
		type: ControlType.ResponsiveImage,
	},
	fypJWowoP: {
		__defaultAssetReference:
			"data:framer/asset-reference,lUz1P3ejN0H231GR4AbA8CuU.jpg?originalFilename=QmSpKC1BzBkcidAQRKcUPgk4K9exvSjvXyh6UxbDP3EvUu%3Fauto%3Dformat%26h%3D1200.jpg&preferredSize=auto",
		title: "Image 2",
		type: ControlType.ResponsiveImage,
	},
	um3nNHNxb: {
		__defaultAssetReference:
			"data:framer/asset-reference,HGbcPTLbYGvKlQDl9jTViqVA4.png?originalFilename=QmNRT4jVgbvwXLm8avNkxNwJUjVywzZCauLKqx5Lst3wxX%3Fauto%3Dformat%26h%3D1200.png&preferredSize=auto",
		title: "Image 3",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerayjHFrJ1o,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:images-right
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Li75wqNCN",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ImagesRightFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var images_right_default = ComponentWithRoot;
export { images_right_default as default };
