// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e9f968b120b46161 "Odin Project", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * image1?: {src: string, srcSet?: string, alt?: string} // Image 1
 * image2?: {src: string, srcSet?: string, alt?: string} // Image 2
 * image3?: {src: string, srcSet?: string, alt?: string} // Image 3
 * image4?: {src: string, srcSet?: string, alt?: string} // Image 4
 * image5?: {src: string, srcSet?: string, alt?: string} // Image 5
 * image6?: {src: string, srcSet?: string, alt?: string} // Image 6
}} Props

 */
import { Ticker } from "./chunks/chunk-JHL2URRN.js";
import { routes } from "./chunks/chunk-3DUKK5YU.js";

// virtual:image-slideshow
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/8BIMCQogQArq0alh99ro/N0luMsNFQabMHnWH409d/x7fUsaBZi.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	Image as Image1,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var TickerFonts = getFonts(Ticker);
var MotionDivWithFX = withFX(motion.div);
var serializationHash = "framer-qSCH9";
var variantClassNames = {
	Rtswf9E_X: "framer-v-41tkf",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition1 = {
	damping: 30,
	delay: 0.3,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	height,
	id,
	image1,
	image2,
	image3,
	image4,
	image5,
	image6,
	width,
	...props
}) => {
	return {
		...props,
		fcMlafgQF: image1 ??
			props.fcMlafgQF ?? {
				alt: "",
				pixelHeight: 600,
				pixelWidth: 900,
				src: "https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?width=900&height=600",
				srcSet:
					"https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?scale-down-to=512&width=900&height=600 512w,https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?width=900&height=600 900w",
			},
		FTwwGFC9O: image4 ??
			props.FTwwGFC9O ?? {
				alt: "",
				pixelHeight: 600,
				pixelWidth: 900,
				src: "https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?width=900&height=600",
				srcSet:
					"https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?scale-down-to=512&width=900&height=600 512w,https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?width=900&height=600 900w",
			},
		JzQFzt11O: image6 ??
			props.JzQFzt11O ?? {
				alt: "",
				pixelHeight: 600,
				pixelWidth: 900,
				src: "https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?width=900&height=600",
				srcSet:
					"https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?scale-down-to=512&width=900&height=600 512w,https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?width=900&height=600 900w",
			},
		oRQx3smJo: image3 ??
			props.oRQx3smJo ?? {
				alt: "",
				pixelHeight: 600,
				pixelWidth: 900,
				src: "https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?width=900&height=600",
				srcSet:
					"https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?scale-down-to=512&width=900&height=600 512w,https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?width=900&height=600 900w",
			},
		qUnbiRlyh: image5 ??
			props.qUnbiRlyh ?? {
				alt: "",
				pixelHeight: 600,
				pixelWidth: 900,
				src: "https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?width=900&height=600",
				srcSet:
					"https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?scale-down-to=512&width=900&height=600 512w,https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?width=900&height=600 900w",
			},
		r4WfWI7aL: image2 ??
			props.r4WfWI7aL ?? {
				alt: "",
				pixelHeight: 600,
				pixelWidth: 900,
				src: "https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?width=900&height=600",
				srcSet:
					"https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?scale-down-to=512&width=900&height=600 512w,https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?width=900&height=600 900w",
			},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		fcMlafgQF: fcMlafgQF2,
		r4WfWI7aL: r4WfWI7aL2,
		oRQx3smJo: oRQx3smJo2,
		FTwwGFC9O: FTwwGFC9O2,
		qUnbiRlyh: qUnbiRlyh2,
		JzQFzt11O: JzQFzt11O2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "Rtswf9E_X",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation}
						__framer__styleAppearEffectEnabled={false}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							scopingClassNames,
							"framer-41tkf",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"Rtswf9E_X"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-10ickhc-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"WbhTp116w-container"}
								nodeId={"WbhTp116w"}
								rendersWithMotion={true}
								scopeId={"x7fUsaBZi"}
							>
								<Ticker
									alignment={"center"}
									direction={"right"}
									fadeOptions={{
										fadeAlpha: 0,
										fadeContent: true,
										fadeInset: 0,
										fadeWidth: 50,
										overflow: false,
									}}
									gap={10}
									height={"100%"}
									hoverFactor={0.5}
									id={"WbhTp116w"}
									layoutId={"WbhTp116w"}
									padding={0}
									paddingBottom={0}
									paddingLeft={0}
									paddingPerSide={false}
									paddingRight={0}
									paddingTop={0}
									sizingOptions={{
										heightType: true,
										widthType: true,
									}}
									slots={[
										<Image1
											background={{
												alt: "",
												fit: "fill",
												pixelHeight: 600,
												pixelWidth: 900,
												sizes: "300px",
												...toResponsiveImage(fcMlafgQF2),
											}}
											className={"framer-ci7pae"}
											data-framer-name={"Image 1"}
											layoutDependency={layoutDependency}
											layoutId={"DDiI7IGCG"}
											style={{
												borderBottomLeftRadius: 4,
												borderBottomRightRadius: 4,
												borderTopLeftRadius: 4,
												borderTopRightRadius: 4,
											}}
										/>,
										<Image1
											background={{
												alt: "",
												fit: "fill",
												pixelHeight: 600,
												pixelWidth: 900,
												sizes: "300px",
												...toResponsiveImage(r4WfWI7aL2),
											}}
											className={"framer-1cte4ki"}
											data-framer-name={"Image 2"}
											layoutDependency={layoutDependency}
											layoutId={"aphtMBW0a"}
											style={{
												borderBottomLeftRadius: 4,
												borderBottomRightRadius: 4,
												borderTopLeftRadius: 4,
												borderTopRightRadius: 4,
											}}
										/>,
										<Image1
											background={{
												alt: "",
												fit: "fill",
												pixelHeight: 600,
												pixelWidth: 900,
												sizes: "300px",
												...toResponsiveImage(oRQx3smJo2),
											}}
											className={"framer-9s0ovi"}
											data-framer-name={"Image 3"}
											layoutDependency={layoutDependency}
											layoutId={"jPJkF12tN"}
											style={{
												borderBottomLeftRadius: 4,
												borderBottomRightRadius: 4,
												borderTopLeftRadius: 4,
												borderTopRightRadius: 4,
											}}
										/>,
										<Image1
											background={{
												alt: "",
												fit: "fill",
												pixelHeight: 600,
												pixelWidth: 900,
												sizes: "300px",
												...toResponsiveImage(FTwwGFC9O2),
											}}
											className={"framer-1tzzbcq"}
											data-framer-name={"Image 4"}
											layoutDependency={layoutDependency}
											layoutId={"qnCWpR9p9"}
											style={{
												borderBottomLeftRadius: 4,
												borderBottomRightRadius: 4,
												borderTopLeftRadius: 4,
												borderTopRightRadius: 4,
											}}
										/>,
										<Image1
											background={{
												alt: "",
												fit: "fill",
												pixelHeight: 600,
												pixelWidth: 900,
												sizes: "300px",
												...toResponsiveImage(qUnbiRlyh2),
											}}
											className={"framer-1df0tq9"}
											data-framer-name={"Image 5"}
											layoutDependency={layoutDependency}
											layoutId={"QI_0D8xD2"}
											style={{
												borderBottomLeftRadius: 4,
												borderBottomRightRadius: 4,
												borderTopLeftRadius: 4,
												borderTopRightRadius: 4,
											}}
										/>,
										<Image1
											background={{
												alt: "",
												fit: "fill",
												pixelHeight: 600,
												pixelWidth: 900,
												sizes: "300px",
												...toResponsiveImage(JzQFzt11O2),
											}}
											className={"framer-vvppql"}
											data-framer-name={"Image 6"}
											layoutDependency={layoutDependency}
											layoutId={"Yr2kFmJa6"}
											style={{
												borderBottomLeftRadius: 4,
												borderBottomRightRadius: 4,
												borderTopLeftRadius: 4,
												borderTopRightRadius: 4,
											}}
										/>,
									]}
									speed={50}
									style={{
										height: "100%",
										width: "100%",
									}}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-qSCH9.framer-10bdy1h, .framer-qSCH9 .framer-10bdy1h { display: block; }",
	".framer-qSCH9.framer-41tkf { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 400px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1440px; }",
	".framer-qSCH9 .framer-10ickhc-container { flex: 1 0 0px; height: 200px; position: relative; width: 1px; }",
	".framer-qSCH9 .framer-ci7pae, .framer-qSCH9 .framer-1cte4ki, .framer-qSCH9 .framer-9s0ovi, .framer-qSCH9 .framer-1tzzbcq, .framer-qSCH9 .framer-1df0tq9, .framer-qSCH9 .framer-vvppql { aspect-ratio: 1.5 / 1; height: var(--framer-aspect-ratio-supported, 200px); overflow: hidden; position: relative; width: 300px; will-change: var(--framer-will-change-override, transform); }",
];
var Framerx7fUsaBZi = withCSS(Component, css, "framer-qSCH9");
var stdin_default = Framerx7fUsaBZi;
Framerx7fUsaBZi.displayName = "Image Slideshow";
Framerx7fUsaBZi.defaultProps = {
	height: 400,
	width: 1440,
};
addPropertyControls(Framerx7fUsaBZi, {
	fcMlafgQF: {
		__defaultAssetReference:
			"data:framer/asset-reference,KHL4jYzaUKAmGoC7Ysn2WssrM.png?originalFilename=default+image.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,KHL4jYzaUKAmGoC7Ysn2WssrM.png?originalFilename=default+image.png&preferredSize=auto",
		},
		title: "Image 1",
		type: ControlType.ResponsiveImage,
	},
	r4WfWI7aL: {
		__defaultAssetReference:
			"data:framer/asset-reference,KHL4jYzaUKAmGoC7Ysn2WssrM.png?originalFilename=default+image.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,KHL4jYzaUKAmGoC7Ysn2WssrM.png?originalFilename=default+image.png&preferredSize=auto",
		},
		title: "Image 2",
		type: ControlType.ResponsiveImage,
	},
	oRQx3smJo: {
		__defaultAssetReference:
			"data:framer/asset-reference,KHL4jYzaUKAmGoC7Ysn2WssrM.png?originalFilename=default+image.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,KHL4jYzaUKAmGoC7Ysn2WssrM.png?originalFilename=default+image.png&preferredSize=auto",
		},
		title: "Image 3",
		type: ControlType.ResponsiveImage,
	},
	FTwwGFC9O: {
		__defaultAssetReference:
			"data:framer/asset-reference,KHL4jYzaUKAmGoC7Ysn2WssrM.png?originalFilename=default+image.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,KHL4jYzaUKAmGoC7Ysn2WssrM.png?originalFilename=default+image.png&preferredSize=auto",
		},
		title: "Image 4",
		type: ControlType.ResponsiveImage,
	},
	qUnbiRlyh: {
		__defaultAssetReference:
			"data:framer/asset-reference,KHL4jYzaUKAmGoC7Ysn2WssrM.png?originalFilename=default+image.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,KHL4jYzaUKAmGoC7Ysn2WssrM.png?originalFilename=default+image.png&preferredSize=auto",
		},
		title: "Image 5",
		type: ControlType.ResponsiveImage,
	},
	JzQFzt11O: {
		__defaultAssetReference:
			"data:framer/asset-reference,KHL4jYzaUKAmGoC7Ysn2WssrM.png?originalFilename=default+image.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,KHL4jYzaUKAmGoC7Ysn2WssrM.png?originalFilename=default+image.png&preferredSize=auto",
		},
		title: "Image 6",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	Framerx7fUsaBZi,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...TickerFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:image-slideshow
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ImageSlideshowFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var image_slideshow_default = ComponentWithRoot;
export { image_slideshow_default as default };
