// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e9f968b120b46161 "Odin Project", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' | 'Variant 3' | 'Variant 4' // Variant
 * image1?: {src: string, srcSet?: string, alt?: string} // Image 1
 * image2?: {src: string, srcSet?: string, alt?: string} // Image 2
 * image3?: {src: string, srcSet?: string, alt?: string} // Image 3
}} Props

 */
import { routes } from "./chunks/chunk-3DUKK5YU.js";

// virtual:images-left
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/eReuiv9tO1OMMThdDEPS/J0GuJ0bvP4xsZwGbpjrT/M4x9izFWJ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image as Image1,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = ["qHn_cTcow", "IfnsVZqyn", "g73VGMF8n", "KbtcdA44Q"];
var serializationHash = "framer-JEuc3";
var variantClassNames = {
	g73VGMF8n: "framer-v-crm2bf",
	IfnsVZqyn: "framer-v-366o3b",
	KbtcdA44Q: "framer-v-9sjrzw",
	qHn_cTcow: "framer-v-ip8680",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 30,
	delay: 0.2,
	mass: 0.1,
	stiffness: 300,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Variant 1": "qHn_cTcow",
	"Variant 2": "IfnsVZqyn",
	"Variant 3": "g73VGMF8n",
	"Variant 4": "KbtcdA44Q",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, image1, image2, image3, width, ...props }) => {
	return {
		...props,
		LJgYXdzOJ: image2 ??
			props.LJgYXdzOJ ?? {
				pixelHeight: 1200,
				pixelWidth: 904,
				src: "https://framerusercontent.com/images/VP3fwPS73PzRC6loj4mifvE92k.png?width=904&height=1200",
				srcSet:
					"https://framerusercontent.com/images/VP3fwPS73PzRC6loj4mifvE92k.png?scale-down-to=1024&width=904&height=1200 771w,https://framerusercontent.com/images/VP3fwPS73PzRC6loj4mifvE92k.png?width=904&height=1200 904w",
			},
		mfEldEwcy: image3 ??
			props.mfEldEwcy ?? {
				pixelHeight: 1200,
				pixelWidth: 904,
				src: "https://framerusercontent.com/images/phE5mCVRnpcfgIgac26K0g29J4.png?width=904&height=1200",
				srcSet:
					"https://framerusercontent.com/images/phE5mCVRnpcfgIgac26K0g29J4.png?scale-down-to=1024&width=904&height=1200 771w,https://framerusercontent.com/images/phE5mCVRnpcfgIgac26K0g29J4.png?width=904&height=1200 904w",
			},
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "qHn_cTcow",
		vGtn24uAa: image1 ??
			props.vGtn24uAa ?? {
				pixelHeight: 1200,
				pixelWidth: 800,
				src: "https://framerusercontent.com/images/IhyXH45ygWgKEq8fT8MQRygSxK8.png?width=800&height=1200",
				srcSet:
					"https://framerusercontent.com/images/IhyXH45ygWgKEq8fT8MQRygSxK8.png?scale-down-to=1024&width=800&height=1200 682w,https://framerusercontent.com/images/IhyXH45ygWgKEq8fT8MQRygSxK8.png?width=800&height=1200 800w",
			},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		vGtn24uAa: vGtn24uAa2,
		LJgYXdzOJ: LJgYXdzOJ2,
		mfEldEwcy: mfEldEwcy2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "qHn_cTcow",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppearcqanxh = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("IfnsVZqyn"), 1e3);
	});
	const onAppear71i4pf = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("g73VGMF8n"), 1e3);
	});
	const onAppear1aknfw6 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("KbtcdA44Q", true), 1e3);
	});
	const onAppearsmhwis = activeVariantCallback(async (...args) => {
		setVariant("qHn_cTcow");
	});
	useOnVariantChange(baseVariant, {
		default: onAppearcqanxh,
		g73VGMF8n: onAppear1aknfw6,
		IfnsVZqyn: onAppear71i4pf,
		KbtcdA44Q: onAppearsmhwis,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							scopingClassNames,
							"framer-ip8680",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"qHn_cTcow"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								g73VGMF8n: {
									"data-framer-name": "Variant 3",
								},
								IfnsVZqyn: {
									"data-framer-name": "Variant 2",
								},
								KbtcdA44Q: {
									"data-framer-name": "Variant 4",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image1
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										((componentViewport?.height || 800) * 0.5000000000000002 -
											((componentViewport?.height || 800) * 1) / 2),
								),
								pixelHeight: 1200,
								pixelWidth: 904,
								sizes: componentViewport?.width || "100vw",
								...toResponsiveImage(vGtn24uAa2),
							}}
							className={"framer-1vuif79"}
							data-framer-name={"Image 1"}
							layoutDependency={layoutDependency}
							layoutId={"I5P1W94KU"}
							style={{
								opacity: 1,
							}}
							variants={{
								g73VGMF8n: {
									opacity: 0,
								},
								IfnsVZqyn: {
									opacity: 0,
								},
								KbtcdA44Q: {
									opacity: 1,
								},
							}}
						/>
						<Image1
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										((componentViewport?.height || 800) * 0.5000000000000002 -
											((componentViewport?.height || 800) * 1) / 2),
								),
								pixelHeight: 1200,
								pixelWidth: 960,
								sizes: componentViewport?.width || "100vw",
								...toResponsiveImage(LJgYXdzOJ2),
							}}
							className={"framer-wwif7x"}
							data-framer-name={"Image 2"}
							layoutDependency={layoutDependency}
							layoutId={"FXWWabmq3"}
							style={{
								opacity: 0,
							}}
							variants={{
								IfnsVZqyn: {
									opacity: 1,
								},
							}}
						/>
						<Image1
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										((componentViewport?.height || 800) * 0.5000000000000002 -
											((componentViewport?.height || 800) * 1) / 2),
								),
								pixelHeight: 1200,
								pixelWidth: 904,
								sizes: componentViewport?.width || "100vw",
								...toResponsiveImage(mfEldEwcy2),
							}}
							className={"framer-5ggbcz"}
							data-framer-name={"Image 3"}
							layoutDependency={layoutDependency}
							layoutId={"byXgDDxYW"}
							style={{
								opacity: 0,
							}}
							variants={{
								g73VGMF8n: {
									opacity: 1,
								},
							}}
						/>
						<motion.div
							className={"framer-806cm1"}
							layoutDependency={layoutDependency}
							layoutId={"hJFxCyPqk"}
							style={{
								backgroundColor:
									"var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255))",
							}}
						/>
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-JEuc3.framer-erittu, .framer-JEuc3 .framer-erittu { display: block; }",
	".framer-JEuc3.framer-ip8680 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 800px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 600px; }",
	".framer-JEuc3 .framer-1vuif79 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; left: calc(50.00000000000002% - 100% / 2); overflow: visible; padding: 0px; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 3; }",
	".framer-JEuc3 .framer-wwif7x { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; left: calc(50.00000000000002% - 100% / 2); overflow: visible; padding: 0px; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 2; }",
	".framer-JEuc3 .framer-5ggbcz { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; left: calc(50.00000000000002% - 100% / 2); overflow: visible; padding: 0px; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 1; }",
	".framer-JEuc3 .framer-806cm1 { flex: 1 0 0px; height: 100%; overflow: hidden; position: relative; width: 1px; z-index: -1; }",
];
var FramerM4x9izFWJ = withCSS(Component, css, "framer-JEuc3");
var stdin_default = FramerM4x9izFWJ;
FramerM4x9izFWJ.displayName = "Images Left";
FramerM4x9izFWJ.defaultProps = {
	height: 800,
	width: 600,
};
addPropertyControls(FramerM4x9izFWJ, {
	variant: {
		options: ["qHn_cTcow", "IfnsVZqyn", "g73VGMF8n", "KbtcdA44Q"],
		optionTitles: ["Variant 1", "Variant 2", "Variant 3", "Variant 4"],
		title: "Variant",
		type: ControlType.Enum,
	},
	vGtn24uAa: {
		__defaultAssetReference:
			"data:framer/asset-reference,IhyXH45ygWgKEq8fT8MQRygSxK8.png?originalFilename=QmW97ydyL2jpUHftFtcbd46bW7do93tfKabMcCv4rw4JQ4%3Fauto%3Dformat%26h%3D1200.png&preferredSize=auto",
		title: "Image 1",
		type: ControlType.ResponsiveImage,
	},
	LJgYXdzOJ: {
		__defaultAssetReference:
			"data:framer/asset-reference,VP3fwPS73PzRC6loj4mifvE92k.png?originalFilename=QmYticGCucxBiE3NFDBggrML8daqE1QvT6dqQjakEiKpTW%3Fauto%3Dformat%26h%3D1200.png&preferredSize=auto",
		title: "Image 2",
		type: ControlType.ResponsiveImage,
	},
	mfEldEwcy: {
		__defaultAssetReference:
			"data:framer/asset-reference,phE5mCVRnpcfgIgac26K0g29J4.png?originalFilename=QmQmrdVgV1XTWCVFo67JcW4LfwpBZoadRCU5mVLQ8yp9ob%3Fauto%3Dformat%26h%3D1200.png&preferredSize=auto",
		title: "Image 3",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerM4x9izFWJ,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:images-left
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "qHn_cTcow",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ImagesLeftFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var images_left_default = ComponentWithRoot;
export { images_left_default as default };
