// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e9f968b120b46161 "Odin Project", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Hidden' // Variant
}} Props

 */
import { Icon } from "./chunks/chunk-MJX6QVBH.js";
import "./chunks/chunk-NULYBL27.js";
import { routes } from "./chunks/chunk-3DUKK5YU.js";

// virtual:new-release-delete
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/u4zuDOqOxTeTVasiS7yi/iVwyjBm9i099Ih5GYKwl/VIqmD2DOJ.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType6,
	cx as cx2,
	getFonts as getFonts2,
	RichText as RichText2,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useActiveVariantCallback,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React4 from "react";
import { useRef as useRef5 } from "react";

// /:https://framerusercontent.com/modules/o1PI5S8YtkA5bP5g4dFz/cAPMVEI6osbJ1UvICgTq/Embed.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	useEffect as useEffect7,
	useRef as useRef3,
	useState as useState3,
} from "react";
import { addPropertyControls, ControlType as ControlType4 } from "unframer";

// /:https://framerusercontent.com/modules/VTUDdizacRHpwbkOamr7/AykinQJbgwl92LvMGZwu/constants.js
import { ControlType } from "unframer";
var containerStyles = {
	position: "relative",
	width: "100%",
	height: "100%",
	display: "flex",
	justifyContent: "center",
	alignItems: "center",
};
var emptyStateStyle = {
	...containerStyles,
	borderRadius: 6,
	background: "rgba(136, 85, 255, 0.3)",
	color: "#85F",
	border: "1px dashed #85F",
	flexDirection: "column",
};
var defaultEvents = {
	onClick: {
		type: ControlType.EventHandler,
	},
	onMouseEnter: {
		type: ControlType.EventHandler,
	},
	onMouseLeave: {
		type: ControlType.EventHandler,
	},
};
var fontSizeOptions = {
	type: ControlType.Number,
	title: "Font Size",
	min: 2,
	max: 200,
	step: 1,
	displayStepper: true,
};
var fontControls = {
	font: {
		type: ControlType.Boolean,
		title: "Font",
		defaultValue: false,
		disabledTitle: "Default",
		enabledTitle: "Custom",
	},
	fontFamily: {
		type: ControlType.String,
		title: "Family",
		placeholder: "Inter",
		hidden: ({ font }) => !font,
	},
	fontWeight: {
		type: ControlType.Enum,
		title: "Weight",
		options: [100, 200, 300, 400, 500, 600, 700, 800, 900],
		optionTitles: [
			"Thin",
			"Extra-light",
			"Light",
			"Regular",
			"Medium",
			"Semi-bold",
			"Bold",
			"Extra-bold",
			"Black",
		],
		hidden: ({ font }) => !font,
	},
};

// /:https://framerusercontent.com/modules/D4TWeLfcxT6Tysr2BlYg/iZjmqdxVx1EOiM3k1FaW/useOnNavigationTargetChange.js
import { useIsInCurrentNavigationTarget } from "unframer";
import { useEffect } from "react";

// /:https://framerusercontent.com/modules/ExNgrA7EJTKUPpH6vIlN/eiOrSJ2Ab5M9jPCvVwUz/useConstant.js
import { useRef } from "react";

// /:https://framerusercontent.com/modules/D2Lz5CmnNVPZFFiZXalt/QaCzPbriZBfXWZIIycFI/colorFromToken.js
import { Color } from "unframer";

// /:https://framerusercontent.com/modules/3mKFSGQqKHV82uOV1eBc/5fbRLvOpxZC0JOXugvwm/isMotionValue.js
import { MotionValue } from "unframer";

// /:https://framerusercontent.com/modules/xDiQsqBGXzmMsv7AlEVy/uhunpMiNsbXxzjlXsg1y/useUniqueClassName.js
import * as React from "react";

// /:https://framerusercontent.com/modules/ETACN5BJyFTSo0VVDJfu/NHRqowOiXkF9UwOzczF7/variantUtils.js
import { ControlType as ControlType2 } from "unframer";

// /:https://framerusercontent.com/modules/eMBrwoqQK7h6mEeGQUH8/GuplvPJVjmxpk9zqOTcb/isBrowser.js
import { useMemo } from "react";

// /:https://framerusercontent.com/modules/v9AWX2URmiYsHf7GbctE/XxKAZ9KlhWqf5x1JMyyF/useOnChange.js
import { useEffect as useEffect3 } from "react";

// /:https://framerusercontent.com/modules/kNDwabfjDEb3vUxkQlZS/fSIr3AOAYbGlfSPgXpYu/useAutoMotionValue.js
import { useCallback, useEffect as useEffect4, useRef as useRef2 } from "react";
import { motionValue, animate, RenderTarget } from "unframer";

// /:https://framerusercontent.com/modules/cuQH4dmpDnV8YK1mSgQX/KqRXqunFjE6ufhpc7ZRu/useFontControls.js
import { fontStore } from "unframer";
import { useEffect as useEffect5 } from "react";

// /:https://framerusercontent.com/modules/afBE9Yx1W6bY5q32qPxe/m3q7puE2tbo1S2C0s0CT/useRenderTarget.js
import { useMemo as useMemo2 } from "react";
import { RenderTarget as RenderTarget2 } from "unframer";
function useIsOnCanvas() {
	const onCanvas = useMemo2(
		() => RenderTarget2.current() === RenderTarget2.canvas,
		[],
	);
	return onCanvas;
}

// /:https://framerusercontent.com/modules/zGkoP8tPDCkoBzMdt5uq/0zFSjxIYliHxrQQnryFX/useControlledState.js
import * as React2 from "react";

// /:https://framerusercontent.com/modules/5SM58HxZHxjjv7aLMOgQ/WXz9i6mVki0bBCrKdqB3/propUtils.js
import { useMemo as useMemo3 } from "react";
import { ControlType as ControlType3 } from "unframer";
var borderRadiusControl = {
	borderRadius: {
		title: "Radius",
		type: ControlType3.FusedNumber,
		toggleKey: "isMixedBorderRadius",
		toggleTitles: ["Radius", "Radius per corner"],
		valueKeys: [
			"topLeftRadius",
			"topRightRadius",
			"bottomRightRadius",
			"bottomLeftRadius",
		],
		valueLabels: ["TL", "TR", "BR", "BL"],
		min: 0,
	},
};
var paddingControl = {
	padding: {
		type: ControlType3.FusedNumber,
		toggleKey: "paddingPerSide",
		toggleTitles: ["Padding", "Padding per side"],
		valueKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
		valueLabels: ["T", "R", "B", "L"],
		min: 0,
		title: "Padding",
	},
};

// /:https://framerusercontent.com/modules/o1PI5S8YtkA5bP5g4dFz/cAPMVEI6osbJ1UvICgTq/Embed.js
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
function Embed({ type, url, html, zoom, radius, border, style = {} }) {
	if (type === "url" && url) {
		return (
			<EmbedUrl
				url={url}
				zoom={zoom}
				radius={radius}
				border={border}
				style={style}
			/>
		);
	}
	if (type === "html" && html) {
		return <EmbedHtml html={html} style={style} />;
	}
	return <Instructions style={style} />;
}
addPropertyControls(Embed, {
	type: {
		type: ControlType4.Enum,
		defaultValue: "url",
		displaySegmentedControl: true,
		options: ["url", "html"],
		optionTitles: ["URL", "HTML"],
	},
	url: {
		title: "URL",
		type: ControlType4.String,
		description: "Some websites don\u2019t support embedding.",
		hidden(props) {
			return props.type !== "url";
		},
	},
	html: {
		title: "HTML",
		type: ControlType4.String,
		displayTextArea: true,
		hidden(props) {
			return props.type !== "html";
		},
	},
	border: {
		title: "Border",
		type: ControlType4.Border,
		optional: true,
		hidden(props) {
			return props.type !== "url";
		},
	},
	radius: {
		type: ControlType4.BorderRadius,
		title: "Radius",
		hidden(props) {
			return props.type !== "url";
		},
	},
	zoom: {
		title: "Zoom",
		defaultValue: 1,
		type: ControlType4.Number,
		hidden(props) {
			return props.type !== "url";
		},
		min: 0.1,
		max: 1,
		step: 0.1,
		displayStepper: true,
	},
});
function Instructions({ style }) {
	return (
		<div
			style={{
				minHeight: getMinHeight(style),
				...emptyStateStyle,
				overflow: "hidden",
				...style,
			}}
		>
			<div style={centerTextStyle}>
				{"To embed a website or widget, add it to the properties\xA0panel."}
			</div>
		</div>
	);
}
function EmbedUrl({ url, zoom, radius, border, style }) {
	const hasAutoHeight = !style.height;
	if (!/[a-z]+:\/\//.test(url)) {
		url = "https://" + url;
	}
	const onCanvas = useIsOnCanvas();
	const [state, setState] = useState3(onCanvas ? void 0 : false);
	useEffect7(() => {
		if (!onCanvas) return;
		let isLastEffect = true;
		setState(void 0);
		async function load() {
			const response = await fetch(
				"https://api.framer.com/functions/check-iframe-url?url=" +
					encodeURIComponent(url),
			);
			if (response.status == 200) {
				const { isBlocked } = await response.json();
				if (isLastEffect) {
					setState(isBlocked);
				}
			} else {
				const message = await response.text();
				console.error(message);
				const error = new Error("This site can\u2019t be reached.");
				setState(error);
			}
		}
		load().catch((error) => {
			console.error(error);
			setState(error);
		});
		return () => {
			isLastEffect = false;
		};
	}, [url]);
	if (onCanvas && hasAutoHeight) {
		return (
			<ErrorMessage
				message={"URL embeds do not support auto height."}
				style={style}
			/>
		);
	}
	if (!url.startsWith("https://")) {
		return <ErrorMessage message={"Unsupported protocol."} style={style} />;
	}
	if (state === void 0) {
		return <LoadingIndicator />;
	}
	if (state instanceof Error) {
		return <ErrorMessage message={state.message} style={style} />;
	}
	if (state === true) {
		const message = `Can\u2019t embed ${url} due to its content security policy.`;
		return <ErrorMessage message={message} style={style} />;
	}
	return (
		<iframe
			src={url}
			style={{
				...iframeStyle,
				...style,
				...border,
				zoom,
				borderRadius: radius,
				transformOrigin: "top center",
			}}
			loading={"lazy"}
			fetchPriority={onCanvas ? "low" : "auto"}
			referrerPolicy={"no-referrer"}
			sandbox={getSandbox(onCanvas)}
			allowFullScreen={true}
			allow={
				"presentation; fullscreen; accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture; clipboard-write"
			}
		/>
	);
}
var iframeStyle = {
	width: "100%",
	height: "100%",
	border: "none",
};
function getSandbox(onCanvas) {
	const result = ["allow-same-origin", "allow-scripts"];
	if (!onCanvas) {
		result.push(
			"allow-downloads",
			"allow-forms",
			"allow-modals",
			"allow-orientation-lock",
			"allow-pointer-lock",
			"allow-popups",
			"allow-popups-to-escape-sandbox",
			"allow-presentation",
			"allow-storage-access-by-user-activation",
			"allow-top-navigation-by-user-activation",
		);
	}
	return result.join(" ");
}
function EmbedHtml({ html, ...props }) {
	const hasScript = html.includes("</script>");
	if (hasScript) {
		const hasSplineViewer = html.includes("</spline-viewer>");
		const hasComment = html.includes("<!-- framer-direct-embed -->");
		if (hasSplineViewer || hasComment) {
			return <EmbedHtmlWithScripts html={html} {...props} />;
		}
		return <EmbedHtmlInsideIframe html={html} {...props} />;
	}
	return <EmbedHtmlWithoutScripts html={html} {...props} />;
}
function EmbedHtmlInsideIframe({ html, style }) {
	const ref = useRef3();
	const [iframeHeight, setIframeHeight] = useState3(0);
	useEffect7(() => {
		const iframeWindow = ref.current?.contentWindow;
		function handleMessage(event) {
			if (event.source !== iframeWindow) return;
			const data = event.data;
			if (typeof data !== "object" || data === null) return;
			const height = data.embedHeight;
			if (typeof height !== "number") return;
			setIframeHeight(height);
		}
		__unframerWindow.addEventListener("message", handleMessage);
		iframeWindow?.postMessage("getEmbedHeight", "*");
		return () => {
			__unframerWindow.removeEventListener("message", handleMessage);
		};
	}, []);
	const srcDoc = `
<html>
    <head>
        <style>
            html, body {
                margin: 0;
                padding: 0;
            }

            body {
                display: flex;
                justify-content: center;
                align-items: center;
            }

            :root {
                -webkit-font-smoothing: antialiased;
                -moz-osx-font-smoothing: grayscale;
            }

            * {
                box-sizing: border-box;
                -webkit-font-smoothing: inherit;
            }

            h1, h2, h3, h4, h5, h6, p, figure {
                margin: 0;
            }

            body, input, textarea, select, button {
                font-size: 12px;
                font-family: sans-serif;
            }
        </style>
    </head>
    <body>
        ${html}
        <script type="module">
            let height = 0

            function sendEmbedHeight() {
                window.parent.postMessage({
                    embedHeight: height
                }, "*")
            }

            const observer = new ResizeObserver((entries) => {
                if (entries.length !== 1) return
                const entry = entries[0]
                if (entry.target !== document.body) return

                height = entry.contentRect.height
                sendEmbedHeight()
            })

            observer.observe(document.body)

            window.addEventListener("message", (event) => {
                if (event.source !== window.parent) return
                if (event.data !== "getEmbedHeight") return
                sendEmbedHeight()
            })
        <\/script>
    <body>
</html>
`;
	const currentStyle = {
		...iframeStyle,
		...style,
	};
	const hasAutoHeight = !style.height;
	if (hasAutoHeight) {
		currentStyle.height = iframeHeight + "px";
	}
	return <iframe ref={ref} style={currentStyle} srcDoc={srcDoc} />;
}
function EmbedHtmlWithScripts({ html, style }) {
	const ref = useRef3();
	useEffect7(() => {
		const div = ref.current;
		if (!div) return;
		div.innerHTML = html;
		executeScripts(div);
		return () => {
			div.innerHTML = "";
		};
	}, [html]);
	return (
		<div
			ref={ref}
			style={{
				...htmlStyle,
				...style,
			}}
		/>
	);
}
function EmbedHtmlWithoutScripts({ html, style }) {
	return (
		<div
			style={{
				...htmlStyle,
				...style,
			}}
			dangerouslySetInnerHTML={{
				__html: html,
			}}
		/>
	);
}
var htmlStyle = {
	width: "100%",
	height: "100%",
	display: "flex",
	flexDirection: "column",
	justifyContent: "center",
	alignItems: "center",
};
function executeScripts(node) {
	if (node instanceof Element && node.tagName === "SCRIPT") {
		const script = document.createElement("script");
		script.text = node.innerHTML;
		for (const { name, value } of node.attributes) {
			script.setAttribute(name, value);
		}
		node.parentElement.replaceChild(script, node);
	} else {
		for (const child of node.childNodes) {
			executeScripts(child);
		}
	}
}
function LoadingIndicator() {
	return (
		<div
			className={"framerInternalUI-componentPlaceholder"}
			style={{
				...containerStyles,
				overflow: "hidden",
			}}
		>
			<div style={centerTextStyle}>{"Loading\u2026"}</div>
		</div>
	);
}
function ErrorMessage({ message, style }) {
	return (
		<div
			className={"framerInternalUI-errorPlaceholder"}
			style={{
				minHeight: getMinHeight(style),
				...containerStyles,
				overflow: "hidden",
				...style,
			}}
		>
			<div style={centerTextStyle}>{message}</div>
		</div>
	);
}
var centerTextStyle = {
	textAlign: "center",
	minWidth: 140,
};
function getMinHeight(style) {
	const hasAutoHeight = !style.height;
	if (hasAutoHeight) return 200;
}

// /:https://framerusercontent.com/modules/sZRoVpGk8N1QJxA57SCq/7FD3y52YdP2xHfl02s6g/zmeQ8k5tf.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType5,
	cx,
	getFonts,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React3 from "react";
import { useRef as useRef4 } from "react";
var PhosphorFonts = getFonts(Icon);
var enabledGestures = {
	P4W9mPgT5: {
		hover: true,
	},
};
var serializationHash = "framer-WXtxf";
var variantClassNames = {
	P4W9mPgT5: "framer-v-vcm4fe",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var radiusForCorner = (value, cornerIndex) => {
	if (typeof value === "number" && Number.isFinite(value))
		return Math.max(0, value) + "px";
	if (typeof value !== "string" || typeof cornerIndex !== "number")
		return void 0;
	const segments = value.split(" ");
	return segments[cornerIndex] || segments[cornerIndex - 2] || segments[0];
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React3.Fragment);
var getProps = ({ fill, height, id, link, radius, title, width, ...props }) => {
	return {
		...props,
		Fbyr5abmG: title ?? props.Fbyr5abmG ?? "Use for Free",
		l1Uh3DC2Y: radius ?? props.l1Uh3DC2Y ?? "10px",
		wjjmPj5qS: link ?? props.wjjmPj5qS,
		xLqgLZVjk:
			fill ??
			props.xLqgLZVjk ??
			"var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255))",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef4(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		wjjmPj5qS,
		l1Uh3DC2Y,
		Fbyr5abmG,
		xLqgLZVjk,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "P4W9mPgT5",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (gestureVariant === "P4W9mPgT5-hover") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={wjjmPj5qS}
						motionChild={true}
						nodeId={"P4W9mPgT5"}
						openInNewTab={true}
						scopeId={"zmeQ8k5tf"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-vcm4fe", className, classNames)} framer-ix9tz`}
							data-framer-name={"Variant 1"}
							layoutDependency={layoutDependency}
							layoutId={"P4W9mPgT5"}
							ref={refBinding}
							style={{
								backdropFilter: "blur(0px)",
								backgroundColor: xLqgLZVjk,
								borderBottomLeftRadius: radiusForCorner(l1Uh3DC2Y, 3),
								borderBottomRightRadius: radiusForCorner(l1Uh3DC2Y, 2),
								borderTopLeftRadius: radiusForCorner(l1Uh3DC2Y, 0),
								borderTopRightRadius: radiusForCorner(l1Uh3DC2Y, 1),
								WebkitBackdropFilter: "blur(0px)",
								...style,
							}}
							variants={{
								"P4W9mPgT5-hover": {
									backgroundColor:
										"var(--token-35958b5f-fcd4-4988-a517-708c39eda844, rgb(250, 250, 250))",
								},
							}}
							{...addPropertyOverrides(
								{
									"P4W9mPgT5-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-o33o9w"}
								fonts={["FS;Poppins-medium"]}
								layoutDependency={layoutDependency}
								layoutId={"WVTFcd3Gl"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={Fbyr5abmG}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React3.Fragment>
									<motion.p
										style={{
											"--font-selector": "RlM7UG9wcGlucy1tZWRpdW0=",
											"--framer-font-family":
												'"Poppins", "Poppins Placeholder", sans-serif',
											"--framer-font-size": "14px",
											"--framer-font-weight": "500",
											"--framer-letter-spacing": "-0.02em",
											"--framer-line-height": "1.6em",
										}}
									>
										{"Use for Free"}
									</motion.p>
								</React3.Fragment>
							</RichText>
							{isDisplayed() && (
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-iw8cxy-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"YRsU21fpP-container"}
										nodeId={"YRsU21fpP"}
										rendersWithMotion={true}
										scopeId={"zmeQ8k5tf"}
									>
										<Icon
											color={"rgb(0, 0, 0)"}
											height={"100%"}
											iconSearch={"House"}
											iconSelection={"ArrowRight"}
											id={"YRsU21fpP"}
											layoutId={"YRsU21fpP"}
											mirrored={false}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											weight={"regular"}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-WXtxf.framer-ix9tz, .framer-WXtxf .framer-ix9tz { display: block; }",
	".framer-WXtxf.framer-vcm4fe { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: 38px; justify-content: center; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 142px; will-change: var(--framer-will-change-override, transform); }",
	".framer-WXtxf .framer-o33o9w { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-WXtxf .framer-iw8cxy-container { flex: none; height: 16px; position: relative; width: 16px; }",
	".framer-WXtxf.framer-v-vcm4fe.hover.framer-vcm4fe { gap: 6px; }",
];
var FramerzmeQ8k5tf = withCSS(Component, css, "framer-WXtxf");
var stdin_default = FramerzmeQ8k5tf;
FramerzmeQ8k5tf.displayName = "CTA Button (Delete)";
FramerzmeQ8k5tf.defaultProps = {
	height: 38,
	width: 142,
};
addPropertyControls2(FramerzmeQ8k5tf, {
	wjjmPj5qS: {
		title: "Link",
		type: ControlType5.Link,
	},
	l1Uh3DC2Y: {
		defaultValue: "10px",
		title: "Radius",
		type: ControlType5.BorderRadius,
	},
	Fbyr5abmG: {
		defaultValue: "Use for Free",
		displayTextArea: false,
		title: "Title",
		type: ControlType5.String,
	},
	xLqgLZVjk: {
		defaultValue:
			'var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255)) /* {"name":"White"} */',
		title: "Fill",
		type: ControlType5.Color,
	},
});
addFonts(
	FramerzmeQ8k5tf,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Poppins",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/K4RHKGAGLQZBXEZQT2O2AGSLKJF2E4YC/JRUTXNFPWLFGIEVSSEYOW7EP7TYM3V6A/UCDYLFFGLZRGCFY5GYDYM5LDB52BAR5M.woff2",
					weight: "500",
				},
			],
		},
		...PhosphorFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/u4zuDOqOxTeTVasiS7yi/iVwyjBm9i099Ih5GYKwl/VIqmD2DOJ.js
var CTAButtonDeleteFonts = getFonts2(stdin_default);
var EmbedFonts = getFonts2(Embed);
var enabledGestures2 = {
	YY2dnKp2V: {
		hover: true,
	},
};
var cycleOrder = ["YY2dnKp2V", "ytmeDIGIM"];
var serializationHash2 = "framer-c4eI1";
var variantClassNames2 = {
	ytmeDIGIM: "framer-v-6m8kkk",
	YY2dnKp2V: "framer-v-1mzoot6",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	damping: 50,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React4.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React4.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React4.Fragment);
var humanReadableVariantMap = {
	Default: "YY2dnKp2V",
	Hidden: "ytmeDIGIM",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "YY2dnKp2V",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React4.forwardRef(function (props, ref) {
	const fallbackRef = useRef5(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React4.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const { style, className, layoutId, variant, ...restProps } =
		getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder,
		defaultVariant: "YY2dnKp2V",
		enabledGestures: enabledGestures2,
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapsz6oe4 = activeVariantCallback(async (...args) => {
		setVariant("ytmeDIGIM");
	});
	const sharedStyleClassNames = [];
	const isDisplayed = () => {
		if (baseVariant === "ytmeDIGIM") return false;
		return true;
	};
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const isDisplayed1 = () => {
		if (gestureVariant === "YY2dnKp2V-hover") return true;
		return false;
	};
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				{isDisplayed() && (
					<Transition2 value={transition12}>
						<motion2.div
							{...restProps}
							{...gestureHandlers}
							className={cx2(
								scopingClassNames,
								"framer-1mzoot6",
								className,
								classNames,
							)}
							data-framer-name={"Default"}
							layoutDependency={layoutDependency}
							layoutId={"YY2dnKp2V"}
							ref={refBinding}
							style={{
								backdropFilter: "blur(5px)",
								backgroundColor: "rgba(24, 24, 27, 0.7)",
								borderBottomLeftRadius: 8,
								borderBottomRightRadius: 8,
								borderTopLeftRadius: 8,
								borderTopRightRadius: 8,
								WebkitBackdropFilter: "blur(5px)",
								...style,
							}}
							{...addPropertyOverrides2(
								{
									"YY2dnKp2V-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion2.div
								className={"framer-57vrfw"}
								data-framer-name={"Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"JTpBJCZo4"}
							>
								{isDisplayed1() && (
									<motion2.div
										className={"framer-10yz83t"}
										data-framer-name={"Hover"}
										layoutDependency={layoutDependency}
										layoutId={"keOzAveHN"}
										style={{
											backgroundColor: "rgba(0, 0, 0, 0.8)",
										}}
									>
										<ComponentViewportProvider2
											height={32}
											{...addPropertyOverrides2(
												{
													"YY2dnKp2V-hover": {
														width: "126px",
														y:
															(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 81) - 0 - 81) /
																2 +
																0 +
																0) +
															0 +
															0 +
															8 +
															1.1,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer2
												className={"framer-x0nv9x-container"}
												layoutDependency={layoutDependency}
												layoutId={"CK2ls9hgA-container"}
												nodeId={"CK2ls9hgA"}
												rendersWithMotion={true}
												scopeId={"VIqmD2DOJ"}
											>
												{_jsx3(stdin_default, {
													Fbyr5abmG: "Preview",
													height: "100%",
													id: "CK2ls9hgA",
													l1Uh3DC2Y: "4px",
													layoutId: "CK2ls9hgA",
													style: {
														height: "100%",
														width: "100%",
													},
													width: "100%",
													wjjmPj5qS: "https://bold-agency.framer.media/",
													xLqgLZVjk:
														"var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255))",
												})}
											</SmartComponentScopedContainer2>
										</ComponentViewportProvider2>
										<RichText2
											__fromCanvasComponent={true}
											className={"framer-rmozus"}
											data-highlight={true}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"DCwUeKS0M"}
											onTap={onTapsz6oe4}
											style={{
												"--extracted-r6o4lv":
													"var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React4.Fragment>
												<motion2.p
													style={{
														"--framer-font-size": "14px",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-f016f496-47f9-415e-be0d-11a3633c456c, rgb(255, 255, 255)))",
													}}
												>
													{"Close"}
												</motion2.p>
											</React4.Fragment>
										</RichText2>
									</motion2.div>
								)}
								<motion2.div
									className={"framer-18ql275"}
									data-framer-name={"Media"}
									layoutDependency={layoutDependency}
									layoutId={"jzIEAw0dE"}
									style={{
										borderBottomLeftRadius: 6,
										borderBottomRightRadius: 6,
										borderTopLeftRadius: 6,
										borderTopRightRadius: 6,
									}}
								>
									<ComponentViewportProvider2>
										<SmartComponentScopedContainer2
											className={"framer-ogay1o-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"YmYr7FWUR-container"}
											nodeId={"YmYr7FWUR"}
											rendersWithMotion={true}
											scopeId={"VIqmD2DOJ"}
										>
											<Embed
												height={"100%"}
												html={
													'<iframe \n  src="https://player.vimeo.com/video/1127097609?autoplay=1&loop=1&muted=1&controls=0&title=0&byline=0&portrait=0"\n  frameborder="0" \n  allow="autoplay; fullscreen" \n  allowfullscreen \n  width="144%" \n  height="200%">\n</iframe>\n'
												}
												id={"YmYr7FWUR"}
												layoutId={"YmYr7FWUR"}
												radius={"0px"}
												style={{
													height: "100%",
													width: "100%",
												}}
												type={"html"}
												url={""}
												width={"100%"}
												zoom={1}
											/>
										</SmartComponentScopedContainer2>
									</ComponentViewportProvider2>
								</motion2.div>
							</motion2.div>
						</motion2.div>
					</Transition2>
				)}
			</Variants2>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-c4eI1.framer-rkp1u5, .framer-c4eI1 .framer-rkp1u5 { display: block; }",
	".framer-c4eI1.framer-1mzoot6 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 2px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-c4eI1 .framer-57vrfw { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 81px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 142px; }",
	".framer-c4eI1 .framer-10yz83t { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 14px; height: 1px; justify-content: center; overflow: visible; padding: 8px; position: relative; width: 100%; z-index: 2; }",
	".framer-c4eI1 .framer-x0nv9x-container { flex: none; height: 32px; position: relative; width: 100%; }",
	".framer-c4eI1 .framer-rmozus { cursor: pointer; flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-c4eI1 .framer-18ql275 { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; justify-content: center; left: 0px; overflow: hidden; padding: 0px; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-c4eI1 .framer-ogay1o-container { flex: none; height: 81px; position: relative; width: 143px; }",
];
var FramerVIqmD2DOJ = withCSS2(Component2, css2, "framer-c4eI1");
var stdin_default2 = FramerVIqmD2DOJ;
FramerVIqmD2DOJ.displayName = "New Release (Delete)";
FramerVIqmD2DOJ.defaultProps = {
	height: 81,
	width: 142,
};
addPropertyControls3(FramerVIqmD2DOJ, {
	variant: {
		options: ["YY2dnKp2V", "ytmeDIGIM"],
		optionTitles: ["Default", "Hidden"],
		title: "Variant",
		type: ControlType6.Enum,
	},
});
addFonts2(
	FramerVIqmD2DOJ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...CTAButtonDeleteFonts,
		...EmbedFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:new-release-delete
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NewReleaseDeleteFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var new_release_delete_default = ComponentWithRoot;
export { new_release_delete_default as default };
