// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e9f968b120b46161 "Odin Project", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * onjRzf0D_RxChange?: any // onjRzf0D_RxChange
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * hoverImage?: {src: string, srcSet?: string, alt?: string} // Hover Image
 * cursor?: any // Cursor
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-4DKRTGL7.js";
import { routes } from "./chunks/chunk-3DUKK5YU.js";

// virtual:project-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/sfcwlZjianA6cSq8L7KB/OYgERzPY2XQfNxyiY5GO/LjhG5_nl3.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image as Image1,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var enabledGestures = {
	YhrOVitpn: {
		hover: true,
	},
};
var serializationHash = "framer-RrxbH";
var variantClassNames = {
	YhrOVitpn: "framer-v-1h44rq0",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var transition1 = {
	damping: 30,
	delay: 0.2,
	mass: 1,
	stiffness: 150,
	type: "spring",
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 1,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	cursor,
	height,
	hoverImage,
	id,
	image,
	title,
	width,
	...props
}) => {
	return {
		...props,
		jRzf0D_Rx: title ?? props.jRzf0D_Rx ?? "Project Title",
		kRO6bzT7M: cursor ?? props.kRO6bzT7M,
		N2hX8XkEc: image ??
			props.N2hX8XkEc ?? {
				pixelHeight: 600,
				pixelWidth: 900,
				src: "https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?width=900&height=600",
				srcSet:
					"https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?scale-down-to=512&width=900&height=600 512w,https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?width=900&height=600 900w",
			},
		YBAZDHJYL: hoverImage ??
			props.YBAZDHJYL ?? {
				pixelHeight: 600,
				pixelWidth: 900,
				src: "https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?width=900&height=600",
				srcSet:
					"https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?scale-down-to=512&width=900&height=600 512w,https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?width=900&height=600 900w",
			},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		jRzf0D_Rx: jRzf0D_Rx2,
		N2hX8XkEc: N2hX8XkEc2,
		YBAZDHJYL: YBAZDHJYL2,
		kRO6bzT7M: kRO6bzT7M2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "YhrOVitpn",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							scopingClassNames,
							"framer-1h44rq0",
							className2,
							classNames,
						)}
						data-framer-cursor={kRO6bzT7M2}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"YhrOVitpn"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								"YhrOVitpn-hover": {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-laoyxd"}
							data-framer-name={"Image Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"I5n51Ck4g"}
							style={{
								backgroundColor:
									"var(--token-c42a75fd-bb9a-47e3-a5a0-31a6cc9f056a, rgb(113, 113, 122))",
								borderBottomLeftRadius: 4,
								borderBottomRightRadius: 4,
								borderTopLeftRadius: 4,
								borderTopRightRadius: 4,
							}}
						>
							<Image1
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 783) -
												0 -
												(((componentViewport?.height || 783) - 0) * 0.9119 +
													68.8 +
													0)) /
												2 +
												0 +
												0) +
											(0 +
												(((componentViewport?.height || 783) - 0) * 0.9119 -
													0 -
													(((componentViewport?.height || 783) - 0) * 0.9119 -
														0) *
														1) /
													2),
									),
									pixelHeight: 984,
									pixelWidth: 1240,
									sizes: `max(min(${componentViewport?.width || "100vw"}, 900px), 1px)`,
									...toResponsiveImage(N2hX8XkEc2),
								}}
								className={"framer-1idngem"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"wUk_VagLg"}
								style={{
									rotate: 0,
									scale: 1,
								}}
								variants={{
									"YhrOVitpn-hover": {
										rotate: 0.3,
										scale: 1.02,
									},
								}}
								{...addPropertyOverrides(
									{
										"YhrOVitpn-hover": {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 783) -
															0 -
															(((componentViewport?.height || 783) - 0) *
																0.9119 +
																68.8 +
																0)) /
															2 +
															0 +
															0) +
														(0 +
															(((componentViewport?.height || 783) - 0) *
																0.9119 -
																0 -
																(((componentViewport?.height || 783) - 0) *
																	0.9119 -
																	0) *
																	1) /
																2),
												),
												sizes: `max(min(${componentViewport?.width || "100vw"}, 900px), 1px)`,
												...toResponsiveImage(YBAZDHJYL2),
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</motion.div>
						<motion.div
							className={"framer-o9cadf"}
							data-framer-name={"Title + Category"}
							layoutDependency={layoutDependency}
							layoutId={"XPkRqKWNX"}
						>
							<motion.div
								className={"framer-4r6ic9"}
								data-framer-name={"Title Wrap"}
								layoutDependency={layoutDependency}
								layoutId={"Lw4ggRWaw"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-y35hyy"}
									data-framer-name={"Title"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"eYCNXIHoN"}
									text={jRzf0D_Rx2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h4
											className={"framer-styles-preset-mxgjku"}
											data-styles-preset={"WxXIS8PjV"}
										>
											{"Project Title"}
										</motion.h4>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-RrxbH.framer-k2nmtb, .framer-RrxbH .framer-k2nmtb { display: block; }",
	".framer-RrxbH.framer-1h44rq0 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 783px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1000px; }",
	".framer-RrxbH .framer-laoyxd { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 91%; justify-content: center; max-width: 900px; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-RrxbH .framer-1idngem { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-RrxbH .framer-o9cadf { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 20px 0px 20px 0px; position: relative; width: 100%; }",
	".framer-RrxbH .framer-4r6ic9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-RrxbH .framer-y35hyy { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-RrxbH.framer-v-1h44rq0.hover .framer-laoyxd { order: 0; }",
	".framer-RrxbH.framer-v-1h44rq0.hover .framer-o9cadf { order: 1; }",
	...css,
];
var FramerLjhG5_nl3 = withCSS(Component, css2, "framer-RrxbH");
var stdin_default = FramerLjhG5_nl3;
FramerLjhG5_nl3.displayName = "Project Card";
FramerLjhG5_nl3.defaultProps = {
	height: 783,
	width: 1e3,
};
addPropertyControls(FramerLjhG5_nl3, {
	jRzf0D_Rx: {
		defaultValue: "Project Title",
		title: "Title",
		type: ControlType.String,
	},
	onjRzf0D_RxChange: {
		changes: "jRzf0D_Rx",
		type: ControlType.ChangeHandler,
	},
	N2hX8XkEc: {
		__defaultAssetReference:
			"data:framer/asset-reference,KHL4jYzaUKAmGoC7Ysn2WssrM.png?originalFilename=default+image.png&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	YBAZDHJYL: {
		__defaultAssetReference:
			"data:framer/asset-reference,KHL4jYzaUKAmGoC7Ysn2WssrM.png?originalFilename=default+image.png&preferredSize=auto",
		title: "Hover Image",
		type: ControlType.ResponsiveImage,
	},
	kRO6bzT7M: {
		title: "Cursor",
		type: ControlType.CustomCursor,
	},
});
addFonts(
	FramerLjhG5_nl3,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:project-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProjectCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var project_card_default = ComponentWithRoot;
export { project_card_default as default };
