// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e9f968b120b46161 "Odin Project", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop-Off' | 'Desktop-On' | 'Tablet-Off' | 'Tablet-On' | 'Phone-Off' | 'Phone-On' // Variant
 * name?: string // Name
 * subName1?: string // Sub Name 1
 * subName2?: string // Sub Name 2
 * subName3?: string // Sub Name 3
 * subName4?: string // Sub Name 4
 * subName5?: string // Sub Name 5
 * subName6?: string // Sub Name 6
}} Props

 */
import { routes } from "./chunks/chunk-3DUKK5YU.js";

// virtual:service-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/jrPagALqsqAAOzOmNOm7/18XBDugHFOdTlHBz5LOZ/wggAvxRUU.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/4oFIVrb93Jy1USHMpu5a/H9cNFKD7T8m3it8ggV8B/l8QMfxZmA.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;JetBrains Mono-regular",
	"FS;JetBrains Mono-bold",
	"FS;JetBrains Mono-bold italic",
	"FS;JetBrains Mono-italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/TZ2PMVPWEVHUPJWOPNSWLOXAF6QPOEMZ/O4OZKA7ZLZGT4JOGT5IEKURK6U3RXYGM/EO5MKE3BUDOZN44BP4HDPXAJAC2BIMCD.woff2",
				weight: "400",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/BTOY6STFL42WXJYET4IAFJ4R4NWQMPYV/SIRJV64UEOICTYN5EECZFJJ3ML2D6HVV/ATU2C7QZBG7GCVXROP265OYM5E55WHMK.woff2",
				weight: "700",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/4UER7KOM5ELODXZSILS67WJ47ZOE75JQ/6CQXJGOZP6EVG2LPOOVWXH2KM6JHNSRY/UTZ3OSIQCH2DNRJBPY7UY3LB6YDOZNJX.woff2",
				weight: "700",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/4CLQH4JOZMAJ6BPWKUFRQYNRRCIRLEBP/3KY6UMEKQ554PCGWM3CWW3ONMSYQ3ELX/O32TDYA5Q7PAMBBEUNMO44BILZFPSQXN.woff2",
				weight: "400",
			},
		],
	},
];
var css = [
	`.framer-Mspij .framer-styles-preset-ocptjj:not(.rich-text-wrapper), .framer-Mspij .framer-styles-preset-ocptjj.rich-text-wrapper h6 { --framer-font-family: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, #e4e4e7); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }`,
	`@media (max-width: 1199px) and (min-width: 810px) { .framer-Mspij .framer-styles-preset-ocptjj:not(.rich-text-wrapper), .framer-Mspij .framer-styles-preset-ocptjj.rich-text-wrapper h6 { --framer-font-family: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, #e4e4e7); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-Mspij .framer-styles-preset-ocptjj:not(.rich-text-wrapper), .framer-Mspij .framer-styles-preset-ocptjj.rich-text-wrapper h6 { --framer-font-family: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, #e4e4e7); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }`,
];
var className = "framer-Mspij";

// /:https://framerusercontent.com/modules/eAbualabjQncq2WMjXCi/UUeoReFMFhXHcTPOqiyb/lknbuE0Ln.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"FS;JetBrains Mono-bold",
	"FS;JetBrains Mono-extrabold",
	"FS;JetBrains Mono-extrabold italic",
	"FS;JetBrains Mono-bold italic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/BTOY6STFL42WXJYET4IAFJ4R4NWQMPYV/SIRJV64UEOICTYN5EECZFJJ3ML2D6HVV/ATU2C7QZBG7GCVXROP265OYM5E55WHMK.woff2",
				weight: "700",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/W2QLP4CHXEAE2UDQ4JZRQSCVGRWTODXQ/IZHRABAMPPUXMZ2PD72AYR3CARBXVTMT/VCHFQIE7HVVHWFPYX3UJFHLWZNFBWMY2.woff2",
				weight: "800",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/CYELXKES646LNQMHDBMMNBTFTS5XYQRB/H7NE6NFMXJ4EIQOOQK2QDHNFWQHSJ62F/HIEFT57NYSYQJX2RC4H6NZCOYVHPMBAL.woff2",
				weight: "800",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/4UER7KOM5ELODXZSILS67WJ47ZOE75JQ/6CQXJGOZP6EVG2LPOOVWXH2KM6JHNSRY/UTZ3OSIQCH2DNRJBPY7UY3LB6YDOZNJX.woff2",
				weight: "700",
			},
		],
	},
];
var css2 = [
	`.framer-5Wols .framer-styles-preset-105ayym:not(.rich-text-wrapper), .framer-5Wols .framer-styles-preset-105ayym.rich-text-wrapper h3 { --framer-font-family: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 40px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 800; --framer-font-weight-bold-italic: 800; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, #e4e4e7); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }`,
	`@media (max-width: 1439px) and (min-width: 809px) { .framer-5Wols .framer-styles-preset-105ayym:not(.rich-text-wrapper), .framer-5Wols .framer-styles-preset-105ayym.rich-text-wrapper h3 { --framer-font-family: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 28px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, #e4e4e7); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }`,
	`@media (max-width: 808px) and (min-width: 0px) { .framer-5Wols .framer-styles-preset-105ayym:not(.rich-text-wrapper), .framer-5Wols .framer-styles-preset-105ayym.rich-text-wrapper h3 { --framer-font-family: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 22px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, #e4e4e7); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }`,
];
var className2 = "framer-5Wols";

// /:https://framerusercontent.com/modules/jrPagALqsqAAOzOmNOm7/18XBDugHFOdTlHBz5LOZ/wggAvxRUU.js
var cycleOrder = [
	"MoHNcZ1HL",
	"YWyxEjNMJ",
	"lyTpA38dX",
	"I49cqsUW4",
	"xBOMfMY55",
	"FjyYOtbPx",
];
var serializationHash = "framer-3L6vk";
var variantClassNames = {
	FjyYOtbPx: "framer-v-1c1gfqe",
	I49cqsUW4: "framer-v-ss7a6g",
	lyTpA38dX: "framer-v-umwzje",
	MoHNcZ1HL: "framer-v-govzfx",
	xBOMfMY55: "framer-v-wm9g0p",
	YWyxEjNMJ: "framer-v-hoyihs",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Desktop-Off": "MoHNcZ1HL",
	"Desktop-On": "YWyxEjNMJ",
	"Phone-Off": "xBOMfMY55",
	"Phone-On": "FjyYOtbPx",
	"Tablet-Off": "lyTpA38dX",
	"Tablet-On": "I49cqsUW4",
};
var getProps = ({
	height,
	id,
	name1,
	subName1,
	subName2,
	subName3,
	subName4,
	subName5,
	subName6,
	width,
	...props
}) => {
	return {
		...props,
		AOVtaWO3e: subName5 ?? props.AOVtaWO3e ?? "Sub-service name 5",
		bRIdXNYSK: subName1 ?? props.bRIdXNYSK ?? "Sub-service name 1",
		CgRxUyMxn: name1 ?? props.CgRxUyMxn ?? "Service Name",
		qJ5rxwY8n: subName4 ?? props.qJ5rxwY8n ?? "Sub-service name 4",
		SuLj62dgv: subName6 ?? props.SuLj62dgv ?? "Sub-service name 6",
		TohdB_xuk: subName2 ?? props.TohdB_xuk ?? "Sub-service name 2",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "MoHNcZ1HL",
		YM6ek7xDl: subName3 ?? props.YM6ek7xDl ?? "Sub-service name 3",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		CgRxUyMxn,
		bRIdXNYSK,
		TohdB_xuk,
		YM6ek7xDl,
		qJ5rxwY8n,
		AOVtaWO3e,
		SuLj62dgv,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "MoHNcZ1HL",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const visible = isSet(bRIdXNYSK);
	const visible1 = isSet(YM6ek7xDl);
	const visible2 = isSet(AOVtaWO3e);
	const visible3 = isSet(TohdB_xuk);
	const visible4 = isSet(qJ5rxwY8n);
	const visible5 = isSet(SuLj62dgv);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-govzfx",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop-Off"}
						layoutDependency={layoutDependency}
						layoutId={"MoHNcZ1HL"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-cc3662e6-3397-466e-9cb2-289050ebc7cb, rgb(0, 0, 0))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								FjyYOtbPx: {
									"data-framer-name": "Phone-On",
								},
								I49cqsUW4: {
									"data-framer-name": "Tablet-On",
								},
								lyTpA38dX: {
									"data-framer-name": "Tablet-Off",
								},
								xBOMfMY55: {
									"data-framer-name": "Phone-Off",
								},
								YWyxEjNMJ: {
									"data-framer-name": "Desktop-On",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1h0wny1"}
							data-framer-name={"Seperate"}
							layoutDependency={layoutDependency}
							layoutId={"bKYLbTyvx"}
							style={{
								backgroundColor:
									"var(--token-88c66ff6-b74b-46bd-abb1-37498123a8c9, rgb(39, 39, 42))",
							}}
							variants={{
								FjyYOtbPx: {
									backgroundColor:
										"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
								},
								I49cqsUW4: {
									backgroundColor:
										"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
								},
								YWyxEjNMJ: {
									backgroundColor:
										"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
								},
							}}
						/>
						<motion.div
							className={"framer-1irxc9a"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"wLzbWNJ57"}
						>
							<motion.div
								className={"framer-3035vt"}
								data-framer-name={"Service Name"}
								layoutDependency={layoutDependency}
								layoutId={"nZT_EzSLO"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1f3dwbx"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"FMVqF5PJ8"}
									style={{
										"--extracted-a0htzi":
											"var(--token-88c66ff6-b74b-46bd-abb1-37498123a8c9, rgb(39, 39, 42))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={CgRxUyMxn}
									variants={{
										FjyYOtbPx: {
											"--extracted-a0htzi":
												"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
										},
										I49cqsUW4: {
											"--extracted-a0htzi":
												"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
										},
										YWyxEjNMJ: {
											"--extracted-a0htzi":
												"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											FjyYOtbPx: {
												children: (
													<React.Fragment>
														<motion.h3
															className={"framer-styles-preset-105ayym"}
															data-styles-preset={"lknbuE0Ln"}
															style={{
																"--framer-text-color":
																	"var(--extracted-a0htzi, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
															}}
														>
															{"Service Name"}
														</motion.h3>
													</React.Fragment>
												),
											},
											I49cqsUW4: {
												children: (
													<React.Fragment>
														<motion.h3
															className={"framer-styles-preset-105ayym"}
															data-styles-preset={"lknbuE0Ln"}
															style={{
																"--framer-text-color":
																	"var(--extracted-a0htzi, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
															}}
														>
															{"Service Name"}
														</motion.h3>
													</React.Fragment>
												),
											},
											YWyxEjNMJ: {
												children: (
													<React.Fragment>
														<motion.h3
															className={"framer-styles-preset-105ayym"}
															data-styles-preset={"lknbuE0Ln"}
															style={{
																"--framer-text-color":
																	"var(--extracted-a0htzi, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
															}}
														>
															{"Service Name"}
														</motion.h3>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.h3
											className={"framer-styles-preset-105ayym"}
											data-styles-preset={"lknbuE0Ln"}
											style={{
												"--framer-text-color":
													"var(--extracted-a0htzi, var(--token-88c66ff6-b74b-46bd-abb1-37498123a8c9, rgb(39, 39, 42)))",
											}}
										>
											{"Service Name"}
										</motion.h3>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-31mqha"}
								data-framer-name={"Sub-Services"}
								layoutDependency={layoutDependency}
								layoutId={"ao83Z_TFl"}
							>
								<motion.div
									className={"framer-5buubr"}
									data-framer-name={"Column 1"}
									layoutDependency={layoutDependency}
									layoutId={"QcLobb3VK"}
								>
									{visible && (
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1g07pyd"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"Jw1VZ34dL"}
											style={{
												"--extracted-1w1cjl5":
													"var(--token-88c66ff6-b74b-46bd-abb1-37498123a8c9, rgb(39, 39, 42))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={bRIdXNYSK}
											variants={{
												FjyYOtbPx: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
												I49cqsUW4: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
												YWyxEjNMJ: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													FjyYOtbPx: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 1"}
																</motion.h6>
															</React.Fragment>
														),
													},
													I49cqsUW4: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 1"}
																</motion.h6>
															</React.Fragment>
														),
													},
													YWyxEjNMJ: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 1"}
																</motion.h6>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.h6
													className={"framer-styles-preset-ocptjj"}
													data-styles-preset={"l8QMfxZmA"}
													style={{
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-1w1cjl5, var(--token-88c66ff6-b74b-46bd-abb1-37498123a8c9, rgb(39, 39, 42)))",
													}}
												>
													{"Sub-service name 1"}
												</motion.h6>
											</React.Fragment>
										</RichText>
									)}
									{visible1 && (
										<RichText
											__fromCanvasComponent={true}
											className={"framer-cchd7e"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"wFRDUlIub"}
											style={{
												"--extracted-1w1cjl5":
													"var(--token-88c66ff6-b74b-46bd-abb1-37498123a8c9, rgb(39, 39, 42))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={YM6ek7xDl}
											variants={{
												FjyYOtbPx: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
												I49cqsUW4: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
												YWyxEjNMJ: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													FjyYOtbPx: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 3"}
																</motion.h6>
															</React.Fragment>
														),
													},
													I49cqsUW4: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 3"}
																</motion.h6>
															</React.Fragment>
														),
													},
													YWyxEjNMJ: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 3"}
																</motion.h6>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.h6
													className={"framer-styles-preset-ocptjj"}
													data-styles-preset={"l8QMfxZmA"}
													style={{
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-1w1cjl5, var(--token-88c66ff6-b74b-46bd-abb1-37498123a8c9, rgb(39, 39, 42)))",
													}}
												>
													{"Sub-service name 3"}
												</motion.h6>
											</React.Fragment>
										</RichText>
									)}
									{visible2 && (
										<RichText
											__fromCanvasComponent={true}
											className={"framer-bmuoou"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"ZAe8V4ZQW"}
											style={{
												"--extracted-1w1cjl5":
													"var(--token-88c66ff6-b74b-46bd-abb1-37498123a8c9, rgb(39, 39, 42))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={AOVtaWO3e}
											variants={{
												FjyYOtbPx: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
												I49cqsUW4: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
												YWyxEjNMJ: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													FjyYOtbPx: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 5"}
																</motion.h6>
															</React.Fragment>
														),
													},
													I49cqsUW4: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 5"}
																</motion.h6>
															</React.Fragment>
														),
													},
													YWyxEjNMJ: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 5"}
																</motion.h6>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.h6
													className={"framer-styles-preset-ocptjj"}
													data-styles-preset={"l8QMfxZmA"}
													style={{
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-1w1cjl5, var(--token-88c66ff6-b74b-46bd-abb1-37498123a8c9, rgb(39, 39, 42)))",
													}}
												>
													{"Sub-service name 5"}
												</motion.h6>
											</React.Fragment>
										</RichText>
									)}
								</motion.div>
								<motion.div
									className={"framer-1q7zktq"}
									data-framer-name={"Column 2"}
									layoutDependency={layoutDependency}
									layoutId={"oCtZtLV5s"}
								>
									{visible3 && (
										<RichText
											__fromCanvasComponent={true}
											className={"framer-furhrp"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"jJcONQI6K"}
											style={{
												"--extracted-1w1cjl5":
													"var(--token-88c66ff6-b74b-46bd-abb1-37498123a8c9, rgb(39, 39, 42))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={TohdB_xuk}
											variants={{
												FjyYOtbPx: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
												I49cqsUW4: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
												YWyxEjNMJ: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													FjyYOtbPx: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 2"}
																</motion.h6>
															</React.Fragment>
														),
													},
													I49cqsUW4: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 2"}
																</motion.h6>
															</React.Fragment>
														),
													},
													YWyxEjNMJ: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 2"}
																</motion.h6>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.h6
													className={"framer-styles-preset-ocptjj"}
													data-styles-preset={"l8QMfxZmA"}
													style={{
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-1w1cjl5, var(--token-88c66ff6-b74b-46bd-abb1-37498123a8c9, rgb(39, 39, 42)))",
													}}
												>
													{"Sub-service name 2"}
												</motion.h6>
											</React.Fragment>
										</RichText>
									)}
									{visible4 && (
										<RichText
											__fromCanvasComponent={true}
											className={"framer-6w3rd7"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"Txq9MYdaE"}
											style={{
												"--extracted-1w1cjl5":
													"var(--token-88c66ff6-b74b-46bd-abb1-37498123a8c9, rgb(39, 39, 42))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={qJ5rxwY8n}
											variants={{
												FjyYOtbPx: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
												I49cqsUW4: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
												YWyxEjNMJ: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													FjyYOtbPx: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 4"}
																</motion.h6>
															</React.Fragment>
														),
													},
													I49cqsUW4: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 4"}
																</motion.h6>
															</React.Fragment>
														),
													},
													YWyxEjNMJ: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 4"}
																</motion.h6>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.h6
													className={"framer-styles-preset-ocptjj"}
													data-styles-preset={"l8QMfxZmA"}
													style={{
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-1w1cjl5, var(--token-88c66ff6-b74b-46bd-abb1-37498123a8c9, rgb(39, 39, 42)))",
													}}
												>
													{"Sub-service name 4"}
												</motion.h6>
											</React.Fragment>
										</RichText>
									)}
									{visible5 && (
										<RichText
											__fromCanvasComponent={true}
											className={"framer-fkd68i"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"VI1REVuFv"}
											style={{
												"--extracted-1w1cjl5":
													"var(--token-88c66ff6-b74b-46bd-abb1-37498123a8c9, rgb(39, 39, 42))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={SuLj62dgv}
											variants={{
												FjyYOtbPx: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
												I49cqsUW4: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
												YWyxEjNMJ: {
													"--extracted-1w1cjl5":
														"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
												},
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													FjyYOtbPx: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 6"}
																</motion.h6>
															</React.Fragment>
														),
													},
													I49cqsUW4: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 6"}
																</motion.h6>
															</React.Fragment>
														),
													},
													YWyxEjNMJ: {
														children: (
															<React.Fragment>
																<motion.h6
																	className={"framer-styles-preset-ocptjj"}
																	data-styles-preset={"l8QMfxZmA"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1w1cjl5, var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231)))",
																	}}
																>
																	{"Sub-service name 6"}
																</motion.h6>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.h6
													className={"framer-styles-preset-ocptjj"}
													data-styles-preset={"l8QMfxZmA"}
													style={{
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-1w1cjl5, var(--token-88c66ff6-b74b-46bd-abb1-37498123a8c9, rgb(39, 39, 42)))",
													}}
												>
													{"Sub-service name 6"}
												</motion.h6>
											</React.Fragment>
										</RichText>
									)}
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-3L6vk.framer-1kg8kg6, .framer-3L6vk .framer-1kg8kg6 { display: block; }",
	".framer-3L6vk.framer-govzfx { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 40px 0px 100px 0px; position: relative; width: 1240px; }",
	".framer-3L6vk .framer-1h0wny1 { flex: none; height: 2px; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; z-index: 2; }",
	".framer-3L6vk .framer-1irxc9a { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-3L6vk .framer-3035vt { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 40%; }",
	".framer-3L6vk .framer-1f3dwbx { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-3L6vk .framer-31mqha { align-content: center; align-items: center; align-self: stretch; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: auto; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 60%; }",
	".framer-3L6vk .framer-5buubr, .framer-3L6vk .framer-1q7zktq { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 87px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-3L6vk .framer-1g07pyd, .framer-3L6vk .framer-cchd7e, .framer-3L6vk .framer-bmuoou, .framer-3L6vk .framer-furhrp, .framer-3L6vk .framer-6w3rd7, .framer-3L6vk .framer-fkd68i { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-3L6vk.framer-govzfx, .framer-3L6vk .framer-1irxc9a, .framer-3L6vk .framer-3035vt, .framer-3L6vk .framer-31mqha, .framer-3L6vk .framer-5buubr, .framer-3L6vk .framer-1q7zktq { gap: 0px; } .framer-3L6vk.framer-govzfx > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-3L6vk.framer-govzfx > :first-child, .framer-3L6vk .framer-5buubr > :first-child, .framer-3L6vk .framer-1q7zktq > :first-child { margin-top: 0px; } .framer-3L6vk.framer-govzfx > :last-child, .framer-3L6vk .framer-5buubr > :last-child, .framer-3L6vk .framer-1q7zktq > :last-child { margin-bottom: 0px; } .framer-3L6vk .framer-1irxc9a > *, .framer-3L6vk .framer-3035vt > *, .framer-3L6vk .framer-31mqha > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-3L6vk .framer-1irxc9a > :first-child, .framer-3L6vk .framer-3035vt > :first-child, .framer-3L6vk .framer-31mqha > :first-child { margin-left: 0px; } .framer-3L6vk .framer-1irxc9a > :last-child, .framer-3L6vk .framer-3035vt > :last-child, .framer-3L6vk .framer-31mqha > :last-child { margin-right: 0px; } .framer-3L6vk .framer-5buubr > *, .framer-3L6vk .framer-1q7zktq > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } }",
	".framer-3L6vk.framer-v-umwzje.framer-govzfx, .framer-3L6vk.framer-v-ss7a6g.framer-govzfx { width: 810px; }",
	".framer-3L6vk.framer-v-umwzje .framer-1irxc9a, .framer-3L6vk.framer-v-ss7a6g .framer-1irxc9a, .framer-3L6vk.framer-v-wm9g0p .framer-1irxc9a, .framer-3L6vk.framer-v-1c1gfqe .framer-1irxc9a { flex-direction: column; gap: 40px; }",
	".framer-3L6vk.framer-v-umwzje .framer-3035vt, .framer-3L6vk.framer-v-ss7a6g .framer-3035vt, .framer-3L6vk.framer-v-wm9g0p .framer-3035vt, .framer-3L6vk.framer-v-1c1gfqe .framer-3035vt { width: 100%; }",
	".framer-3L6vk.framer-v-umwzje .framer-31mqha, .framer-3L6vk.framer-v-ss7a6g .framer-31mqha { align-self: unset; height: min-content; width: 100%; }",
	".framer-3L6vk.framer-v-umwzje .framer-5buubr, .framer-3L6vk.framer-v-umwzje .framer-1q7zktq { height: min-content; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-3L6vk.framer-v-umwzje .framer-1irxc9a { gap: 0px; } .framer-3L6vk.framer-v-umwzje .framer-1irxc9a > * { margin: 0px; margin-bottom: calc(40px / 2); margin-top: calc(40px / 2); } .framer-3L6vk.framer-v-umwzje .framer-1irxc9a > :first-child { margin-top: 0px; } .framer-3L6vk.framer-v-umwzje .framer-1irxc9a > :last-child { margin-bottom: 0px; } }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-3L6vk.framer-v-ss7a6g .framer-1irxc9a { gap: 0px; } .framer-3L6vk.framer-v-ss7a6g .framer-1irxc9a > * { margin: 0px; margin-bottom: calc(40px / 2); margin-top: calc(40px / 2); } .framer-3L6vk.framer-v-ss7a6g .framer-1irxc9a > :first-child { margin-top: 0px; } .framer-3L6vk.framer-v-ss7a6g .framer-1irxc9a > :last-child { margin-bottom: 0px; } }",
	".framer-3L6vk.framer-v-wm9g0p.framer-govzfx, .framer-3L6vk.framer-v-1c1gfqe.framer-govzfx { width: 390px; }",
	".framer-3L6vk.framer-v-wm9g0p .framer-31mqha, .framer-3L6vk.framer-v-1c1gfqe .framer-31mqha { align-self: unset; flex-direction: column; gap: 10px; height: min-content; width: 100%; }",
	".framer-3L6vk.framer-v-wm9g0p .framer-5buubr, .framer-3L6vk.framer-v-wm9g0p .framer-1q7zktq, .framer-3L6vk.framer-v-1c1gfqe .framer-5buubr, .framer-3L6vk.framer-v-1c1gfqe .framer-1q7zktq { flex: none; height: min-content; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-3L6vk.framer-v-wm9g0p .framer-1irxc9a, .framer-3L6vk.framer-v-wm9g0p .framer-31mqha { gap: 0px; } .framer-3L6vk.framer-v-wm9g0p .framer-1irxc9a > * { margin: 0px; margin-bottom: calc(40px / 2); margin-top: calc(40px / 2); } .framer-3L6vk.framer-v-wm9g0p .framer-1irxc9a > :first-child, .framer-3L6vk.framer-v-wm9g0p .framer-31mqha > :first-child { margin-top: 0px; } .framer-3L6vk.framer-v-wm9g0p .framer-1irxc9a > :last-child, .framer-3L6vk.framer-v-wm9g0p .framer-31mqha > :last-child { margin-bottom: 0px; } .framer-3L6vk.framer-v-wm9g0p .framer-31mqha > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-3L6vk.framer-v-1c1gfqe .framer-1irxc9a, .framer-3L6vk.framer-v-1c1gfqe .framer-31mqha { gap: 0px; } .framer-3L6vk.framer-v-1c1gfqe .framer-1irxc9a > * { margin: 0px; margin-bottom: calc(40px / 2); margin-top: calc(40px / 2); } .framer-3L6vk.framer-v-1c1gfqe .framer-1irxc9a > :first-child, .framer-3L6vk.framer-v-1c1gfqe .framer-31mqha > :first-child { margin-top: 0px; } .framer-3L6vk.framer-v-1c1gfqe .framer-1irxc9a > :last-child, .framer-3L6vk.framer-v-1c1gfqe .framer-31mqha > :last-child { margin-bottom: 0px; } .framer-3L6vk.framer-v-1c1gfqe .framer-31mqha > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } }",
	...css2,
	...css,
];
var FramerwggAvxRUU = withCSS(Component, css3, "framer-3L6vk");
var stdin_default = FramerwggAvxRUU;
FramerwggAvxRUU.displayName = "Service Card";
FramerwggAvxRUU.defaultProps = {
	height: 227,
	width: 1240,
};
addPropertyControls(FramerwggAvxRUU, {
	variant: {
		options: [
			"MoHNcZ1HL",
			"YWyxEjNMJ",
			"lyTpA38dX",
			"I49cqsUW4",
			"xBOMfMY55",
			"FjyYOtbPx",
		],
		optionTitles: [
			"Desktop-Off",
			"Desktop-On",
			"Tablet-Off",
			"Tablet-On",
			"Phone-Off",
			"Phone-On",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	CgRxUyMxn: {
		defaultValue: "Service Name",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	bRIdXNYSK: {
		defaultValue: "Sub-service name 1",
		displayTextArea: false,
		title: "Sub Name 1",
		type: ControlType.String,
	},
	TohdB_xuk: {
		defaultValue: "Sub-service name 2",
		displayTextArea: false,
		title: "Sub Name 2",
		type: ControlType.String,
	},
	YM6ek7xDl: {
		defaultValue: "Sub-service name 3",
		displayTextArea: false,
		title: "Sub Name 3",
		type: ControlType.String,
	},
	qJ5rxwY8n: {
		defaultValue: "Sub-service name 4",
		displayTextArea: false,
		title: "Sub Name 4",
		type: ControlType.String,
	},
	AOVtaWO3e: {
		defaultValue: "Sub-service name 5",
		displayTextArea: false,
		title: "Sub Name 5",
		type: ControlType.String,
	},
	SuLj62dgv: {
		defaultValue: "Sub-service name 6",
		displayTextArea: false,
		title: "Sub Name 6",
		type: ControlType.String,
	},
});
addFonts(
	FramerwggAvxRUU,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:service-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "xBOMfMY55",
	md: "lyTpA38dX",
	xl: "MoHNcZ1HL",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ServiceCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var service_card_default = ComponentWithRoot;
export { service_card_default as default };
