// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e9f968b120b46161 "Odin Project", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * mainImage?: {src: string, srcSet?: string, alt?: string} // Main Image
}} Props

 */
import { routes } from "./chunks/chunk-3DUKK5YU.js";

// virtual:single-image
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/2zyU8WNKJ3oxfhfSZL7T/fczeKQnjArVinl50LiqZ/HBgOA7yZC.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var serializationHash = "framer-q8Sow";
var variantClassNames = {
	GfH9txZ5h: "framer-v-1wsko9l",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 20,
};
var transition1 = {
	bounce: 0.1,
	delay: 0.2,
	duration: 0.8,
	type: "spring",
};
var transition2 = {
	damping: 50,
	delay: 0.1,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, mainImage, width, ...props }) => {
	return {
		...props,
		qsMU9itmH: mainImage ??
			props.qsMU9itmH ?? {
				src: "https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png",
				srcSet:
					"https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?scale-down-to=512 512w,https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png 900w",
			},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, qsMU9itmH, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "GfH9txZ5h",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							scopingClassNames,
							"framer-1wsko9l",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"GfH9txZ5h"}
						ref={refBinding}
						style={{
							borderBottomLeftRadius: 4,
							borderBottomRightRadius: 4,
							borderTopLeftRadius: 4,
							borderTopRightRadius: 4,
							...style,
						}}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 393.5) - 0 - 420) / 2),
								),
								sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
								...toResponsiveImage(qsMU9itmH),
							}}
							className={"framer-197ryw9"}
							data-framer-name={"Main Image"}
							layoutDependency={layoutDependency}
							layoutId={"K0gQNW1kG"}
						/>
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-q8Sow.framer-1pmf6r2, .framer-q8Sow .framer-1pmf6r2 { display: block; }",
	".framer-q8Sow.framer-1wsko9l { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 590px; will-change: var(--framer-will-change-override, transform); }",
	".framer-q8Sow .framer-197ryw9 { align-content: center; align-items: center; aspect-ratio: 1.5 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 394px); justify-content: center; padding: 0px; position: relative; width: 1px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-q8Sow.framer-1wsko9l, .framer-q8Sow .framer-197ryw9 { gap: 0px; } .framer-q8Sow.framer-1wsko9l > *, .framer-q8Sow .framer-197ryw9 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-q8Sow.framer-1wsko9l > :first-child, .framer-q8Sow .framer-197ryw9 > :first-child { margin-left: 0px; } .framer-q8Sow.framer-1wsko9l > :last-child, .framer-q8Sow .framer-197ryw9 > :last-child { margin-right: 0px; } }",
];
var FramerHBgOA7yZC = withCSS(Component, css, "framer-q8Sow");
var stdin_default = FramerHBgOA7yZC;
FramerHBgOA7yZC.displayName = "Single Image";
FramerHBgOA7yZC.defaultProps = {
	height: 393.5,
	width: 590,
};
addPropertyControls(FramerHBgOA7yZC, {
	qsMU9itmH: {
		__defaultAssetReference:
			"data:framer/asset-reference,KHL4jYzaUKAmGoC7Ysn2WssrM.png?originalFilename=default+image.png&preferredSize=auto",
		title: "Main Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerHBgOA7yZC,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:single-image
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SingleImageFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var single_image_default = ComponentWithRoot;
export { single_image_default as default };
