// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e9f968b120b46161 "Odin Project", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * name?: string // Name
 * position?: string // Position
 * image?: {src: string, srcSet?: string, alt?: string} // Image
}} Props

 */
import { routes } from "./chunks/chunk-3DUKK5YU.js";

// virtual:team-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/3yHHkZiwuzYKyQ0v8iqk/oI0bbeb4XX7thS3Wo7eo/aQEEWLDXX.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/ai5SiWxxmPD6SSA57bgV/3rOJeDUk13SqwW3PPbIA/eKbH3HTQS.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;JetBrains Mono-regular",
	"FS;JetBrains Mono-bold",
	"FS;JetBrains Mono-bold italic",
	"FS;JetBrains Mono-italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/TZ2PMVPWEVHUPJWOPNSWLOXAF6QPOEMZ/O4OZKA7ZLZGT4JOGT5IEKURK6U3RXYGM/EO5MKE3BUDOZN44BP4HDPXAJAC2BIMCD.woff2",
				weight: "400",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/BTOY6STFL42WXJYET4IAFJ4R4NWQMPYV/SIRJV64UEOICTYN5EECZFJJ3ML2D6HVV/ATU2C7QZBG7GCVXROP265OYM5E55WHMK.woff2",
				weight: "700",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/4UER7KOM5ELODXZSILS67WJ47ZOE75JQ/6CQXJGOZP6EVG2LPOOVWXH2KM6JHNSRY/UTZ3OSIQCH2DNRJBPY7UY3LB6YDOZNJX.woff2",
				weight: "700",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/4CLQH4JOZMAJ6BPWKUFRQYNRRCIRLEBP/3KY6UMEKQ554PCGWM3CWW3ONMSYQ3ELX/O32TDYA5Q7PAMBBEUNMO44BILZFPSQXN.woff2",
				weight: "400",
			},
		],
	},
];
var css = [
	`.framer-rAEcr .framer-styles-preset-vif74l:not(.rich-text-wrapper), .framer-rAEcr .framer-styles-preset-vif74l.rich-text-wrapper h6 { --framer-font-family: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0.05em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-c42a75fd-bb9a-47e3-a5a0-31a6cc9f056a, #71717a); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }`,
];
var className = "framer-rAEcr";

// /:https://framerusercontent.com/modules/eHar6h0CQUVf7HmnaNum/NnK8ofFJvPgRF62Ue0r0/WxXIS8PjV.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"FS;JetBrains Mono-medium",
	"FS;JetBrains Mono-bold",
	"FS;JetBrains Mono-bold italic",
	"FS;JetBrains Mono-medium italic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/WAVZNL4Z7TESTS4B4IIRZFODLSPP6FXA/E36Y7HT2GFM2VKF4G73CRBOSSERR73SW/33ZCUAC3GU2QVDMGY6EP3BNWHET5IUK4.woff2",
				weight: "500",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/BTOY6STFL42WXJYET4IAFJ4R4NWQMPYV/SIRJV64UEOICTYN5EECZFJJ3ML2D6HVV/ATU2C7QZBG7GCVXROP265OYM5E55WHMK.woff2",
				weight: "700",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/4UER7KOM5ELODXZSILS67WJ47ZOE75JQ/6CQXJGOZP6EVG2LPOOVWXH2KM6JHNSRY/UTZ3OSIQCH2DNRJBPY7UY3LB6YDOZNJX.woff2",
				weight: "700",
			},
			{
				family: "JetBrains Mono",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/RYPPSTLQMV7DLOHH7PHCXPB6RLY42HYV/QCGHF55LMKJRYMLPWIC5T6ELCTX2YYRJ/YKQ7PORZM5DHBJRQMTFVQEHVSJOEFFJ5.woff2",
				weight: "500",
			},
		],
	},
];
var css2 = [
	`.framer-bsjS5 .framer-styles-preset-mxgjku:not(.rich-text-wrapper), .framer-bsjS5 .framer-styles-preset-mxgjku.rich-text-wrapper h4 { --framer-font-family: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-italic: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, #e4e4e7); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }`,
	`@media (max-width: 1439px) and (min-width: 809px) { .framer-bsjS5 .framer-styles-preset-mxgjku:not(.rich-text-wrapper), .framer-bsjS5 .framer-styles-preset-mxgjku.rich-text-wrapper h4 { --framer-font-family: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 22px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, #e4e4e7); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }`,
	`@media (max-width: 808px) and (min-width: 0px) { .framer-bsjS5 .framer-styles-preset-mxgjku:not(.rich-text-wrapper), .framer-bsjS5 .framer-styles-preset-mxgjku.rich-text-wrapper h4 { --framer-font-family: "JetBrains Mono", "JetBrains Mono Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, #e4e4e7); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }`,
];
var className2 = "framer-bsjS5";

// /:https://framerusercontent.com/modules/3yHHkZiwuzYKyQ0v8iqk/oI0bbeb4XX7thS3Wo7eo/aQEEWLDXX.js
var MotionDivWithFX = withFX(motion.div);
var serializationHash = "framer-B15da";
var variantClassNames = {
	l0NXnIHzP: "framer-v-1530tma",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var transition1 = {
	damping: 50,
	delay: 0.4,
	mass: 1,
	stiffness: 300,
	type: "spring",
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transition3 = {
	damping: 30,
	delay: 0,
	mass: 1,
	stiffness: 300,
	type: "spring",
};
var animation1 = {
	opacity: 1,
	rotate: 1,
	rotateX: 0,
	rotateY: 0,
	scale: 1.02,
	skewX: 0,
	skewY: 0,
	transition: transition3,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, image, name1, position, width, ...props }) => {
	return {
		...props,
		GqaFJtUef: position ?? props.GqaFJtUef ?? "Position",
		H8D082bQU: image ??
			props.H8D082bQU ?? {
				alt: "",
				src: "https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png?scale-down-to=512 512w,https://framerusercontent.com/images/KHL4jYzaUKAmGoC7Ysn2WssrM.png 900w",
			},
		PxHWkUmWm: name1 ?? props.PxHWkUmWm ?? "Name",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		PxHWkUmWm,
		GqaFJtUef,
		H8D082bQU,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "l0NXnIHzP",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							scopingClassNames,
							"framer-1530tma",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"l0NXnIHzP"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<motion.div
							className={"framer-1l5nu8w"}
							data-framer-name={"Image Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"zULL509Mw"}
							style={{
								backgroundColor:
									"var(--token-c42a75fd-bb9a-47e3-a5a0-31a6cc9f056a, rgb(113, 113, 122))",
								borderBottomLeftRadius: 4,
								borderBottomRightRadius: 4,
								borderTopLeftRadius: 4,
								borderTopRightRadius: 4,
							}}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 493) - 0 - 493.2) / 2 +
												0 +
												0) +
											0,
									),
									pixelHeight: 984,
									pixelWidth: 1240,
									sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
									...toResponsiveImage(H8D082bQU),
								}}
								className={"framer-17bczyh"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"NrNY2CiVo"}
								whileHover={animation1}
							/>
						</motion.div>
						<motion.div
							className={"framer-tbm6m9"}
							data-framer-name={"Title + Category"}
							layoutDependency={layoutDependency}
							layoutId={"yBFuaul0V"}
						>
							<motion.div
								className={"framer-1gznayf"}
								data-framer-name={"Name"}
								layoutDependency={layoutDependency}
								layoutId={"ELtt1z6yX"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1ukzti3"}
									data-framer-name={"Name"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"oxgSU3yPO"}
									text={PxHWkUmWm}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h4
											className={"framer-styles-preset-mxgjku"}
											data-styles-preset={"WxXIS8PjV"}
										>
											{"Name"}
										</motion.h4>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-124eu11"}
								data-framer-name={"Position"}
								layoutDependency={layoutDependency}
								layoutId={"LfYQnAm1A"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1gjiv7k"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"chI6mfgmk"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={GqaFJtUef}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h6
											className={"framer-styles-preset-vif74l"}
											data-styles-preset={"eKbH3HTQS"}
										>
											{"Position"}
										</motion.h6>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-B15da.framer-x2bykf, .framer-B15da .framer-x2bykf { display: block; }",
	".framer-B15da.framer-1530tma { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 300px; }",
	".framer-B15da .framer-1l5nu8w { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-B15da .framer-17bczyh { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 400px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-effect-override, transform); }",
	".framer-B15da .framer-tbm6m9 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 20px 0px 20px 0px; position: relative; width: 100%; }",
	".framer-B15da .framer-1gznayf { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-B15da .framer-1ukzti3, .framer-B15da .framer-1gjiv7k { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-B15da .framer-124eu11 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-B15da.framer-1530tma, .framer-B15da .framer-1l5nu8w, .framer-B15da .framer-17bczyh, .framer-B15da .framer-tbm6m9, .framer-B15da .framer-1gznayf, .framer-B15da .framer-124eu11 { gap: 0px; } .framer-B15da.framer-1530tma > *, .framer-B15da .framer-tbm6m9 > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-B15da.framer-1530tma > :first-child, .framer-B15da .framer-tbm6m9 > :first-child { margin-top: 0px; } .framer-B15da.framer-1530tma > :last-child, .framer-B15da .framer-tbm6m9 > :last-child { margin-bottom: 0px; } .framer-B15da .framer-1l5nu8w > *, .framer-B15da .framer-17bczyh > *, .framer-B15da .framer-1gznayf > *, .framer-B15da .framer-124eu11 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-B15da .framer-1l5nu8w > :first-child, .framer-B15da .framer-17bczyh > :first-child, .framer-B15da .framer-1gznayf > :first-child, .framer-B15da .framer-124eu11 > :first-child { margin-left: 0px; } .framer-B15da .framer-1l5nu8w > :last-child, .framer-B15da .framer-17bczyh > :last-child, .framer-B15da .framer-1gznayf > :last-child, .framer-B15da .framer-124eu11 > :last-child { margin-right: 0px; } }",
	...css2,
	...css,
];
var FrameraQEEWLDXX = withCSS(Component, css3, "framer-B15da");
var stdin_default = FrameraQEEWLDXX;
FrameraQEEWLDXX.displayName = "Team Card";
FrameraQEEWLDXX.defaultProps = {
	height: 493,
	width: 300,
};
addPropertyControls(FrameraQEEWLDXX, {
	PxHWkUmWm: {
		defaultValue: "Name",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	GqaFJtUef: {
		defaultValue: "Position",
		displayTextArea: false,
		title: "Position",
		type: ControlType.String,
	},
	H8D082bQU: {
		__defaultAssetReference:
			"data:framer/asset-reference,KHL4jYzaUKAmGoC7Ysn2WssrM.png?originalFilename=default+image.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,KHL4jYzaUKAmGoC7Ysn2WssrM.png?originalFilename=default+image.png&preferredSize=auto",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FrameraQEEWLDXX,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:team-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TeamCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var team_card_default = ComponentWithRoot;
export { team_card_default as default };
