// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e9f968b120b46161 "Odin Project", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-2NPYEUCN.js";
import "./chunks/chunk-DS3S36D3.js";
import "./chunks/chunk-YFGASGYH.js";
import "./chunks/chunk-4DKRTGL7.js";
import { routes } from "./chunks/chunk-3DUKK5YU.js";

// virtual:testimonials
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/bkuGcwP39hk0pDUcbFrT/EBNjM6JVfBMtb0s4bA5Z/gvk807VK1.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext,
} from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/zvkTOpMSuRzRhLzZZIwG/yCImoe7N6FDrwtjU8MPe/SlideShow.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { resize } from "@motionone/dom";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import {
	animate,
	LayoutGroup,
	mix,
	motion,
	frame,
	useInView,
	useMotionValue,
	useTransform,
	wrap,
	usePageInView,
} from "unframer";
import {
	Children,
	cloneElement,
	forwardRef,
	memo,
	startTransition,
	useCallback,
	useEffect,
	useLayoutEffect,
	useMemo,
	useRef,
	useState,
} from "react";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
function awaitRefCallback(element, controller) {
	let refCallbackResolve;
	let current = element.current;
	Object.defineProperty(element, "current", {
		get() {
			return current;
		},
		set(node) {
			current = node;
			if (node === null) {
				controller.abort();
				return;
			}
			refCallbackResolve?.(node);
		},
		configurable: true,
	});
	if (current) return current;
	const refCallbackPromise = new Promise((resolve, reject) => {
		refCallbackResolve = resolve;
		controller.signal.addEventListener("abort", reject);
	}).catch(() => {});
	return refCallbackPromise;
}
var OPACITY_0 = 1e-3;
function Slideshow(props) {
	const {
		slots = [],
		startFrom,
		direction,
		effectsOptions,
		autoPlayControl,
		dragControl,
		alignment,
		gap,
		padding,
		paddingPerSide,
		paddingTop,
		paddingRight,
		paddingBottom,
		paddingLeft,
		itemAmount,
		fadeOptions,
		intervalControl,
		transitionControl,
		arrowOptions,
		borderRadius,
		progressOptions,
		style,
	} = props;
	const {
		effectsOpacity,
		effectsScale,
		effectsRotate,
		effectsPerspective,
		effectsHover,
		playOffscreen,
	} = effectsOptions;
	const { fadeContent, overflow, fadeWidth, fadeInset, fadeAlpha } =
		fadeOptions;
	const {
		showMouseControls,
		arrowSize,
		arrowRadius,
		arrowFill,
		leftArrow,
		rightArrow,
		arrowShouldSpace = true,
		arrowShouldFadeIn = false,
		arrowPosition,
		arrowPadding,
		arrowGap,
		arrowPaddingTop,
		arrowPaddingRight,
		arrowPaddingBottom,
		arrowPaddingLeft,
	} = arrowOptions;
	const {
		showProgressDots,
		dotSize,
		dotsInset,
		dotsRadius,
		dotsPadding,
		dotsGap,
		dotsFill,
		dotsBackground,
		dotsActiveOpacity,
		dotsOpacity,
		dotsBlur,
	} = progressOptions;
	const paddingValue = paddingPerSide
		? `${paddingTop}px ${paddingRight}px ${paddingBottom}px ${paddingLeft}px`
		: `${padding}px`;
	const isCanvas = RenderTarget.current() === RenderTarget.canvas;
	const filteredSlots = slots.filter(Boolean);
	const amountChildren = Children.count(filteredSlots);
	const hasChildren = amountChildren > 0;
	if (!hasChildren) {
		return (
			<section style={placeholderStyles}>
				<div style={emojiStyles}>{"\u2B50\uFE0F"}</div>
				<p style={titleStyles}>{"Connect to Content"}</p>
				<p style={subtitleStyles}>
					{"Add layers or components to make infinite auto-playing slideshows."}
				</p>
			</section>
		);
	}
	const parentRef = useRef(null);
	const childrenRef = useMemo(() => {
		return [
			{
				current: null,
			},
			{
				current: null,
			},
		];
	}, [filteredSlots]);
	const timeoutRef = useRef(void 0);
	const [size, setSize] = useState({
		parent: null,
		children: null,
		item: null,
		itemWidth: null,
		itemHeight: null,
		viewportLength: null,
	});
	const writingDirection = useWritingDirection();
	const resolvedDirection = getSlideshowResolvedDirection(
		direction,
		writingDirection,
	);
	const isHorizontal =
		resolvedDirection === "left" || resolvedDirection === "right";
	const isInverted =
		resolvedDirection === "right" || resolvedDirection === "bottom";
	const rtlDirectionModifier =
		isHorizontal && writingDirection === "rtl" ? -1 : 1;
	const [isHovering, setIsHovering] = useState(false);
	const [shouldPlayOnHover, setShouldPlayOnHover] = useState(autoPlayControl);
	const [isMouseDown, setIsMouseDown] = useState(false);
	const [isResizing, setIsResizing] = useState(false);
	let dupedChildren = [];
	let duplicateBy = 4;
	if (isCanvas) {
		duplicateBy = 1;
	}
	const measure = useCallback(() => {
		if (!parentRef.current) return;
		const isRTL =
			isHorizontal &&
			childrenRef[0].current &&
			childrenRef[1].current &&
			childrenRef[1].current.offsetLeft < childrenRef[0].current.offsetLeft;
		const firstChild = isRTL ? childrenRef[1].current : childrenRef[0].current;
		const lastChild = isRTL ? childrenRef[0].current : childrenRef[1].current;
		const parentLength = isHorizontal
			? parentRef.current.offsetWidth
			: parentRef.current.offsetHeight;
		const start = firstChild
			? isHorizontal
				? firstChild.offsetLeft
				: firstChild.offsetTop
			: 0;
		const end = lastChild
			? isHorizontal
				? lastChild.offsetLeft + lastChild.offsetWidth
				: lastChild.offsetTop + lastChild.offsetHeight
			: 0;
		const childrenLength = end - start + gap;
		const itemSize = firstChild
			? isHorizontal
				? firstChild.offsetWidth
				: firstChild.offsetHeight
			: 0;
		const itemWidth = firstChild ? firstChild.offsetWidth : 0;
		const itemHeight = firstChild ? firstChild.offsetHeight : 0;
		const viewportLength = isHorizontal
			? Math.max(
					document.documentElement.clientWidth || 0,
					__unframerWindow.innerWidth || 0,
					parentRef.current.offsetWidth,
				)
			: Math.max(
					document.documentElement.clientHeight || 0,
					__unframerWindow.innerHeight || 0,
					parentRef.current.offsetHeight,
				);
		setSize({
			parent: parentLength,
			children: childrenLength,
			item: itemSize,
			itemWidth,
			itemHeight,
			viewportLength,
		});
	}, []);
	const scheduleMeasure = useCallback(async () => {
		const controller = new AbortController();
		const [firstChild, lastChild] = childrenRef;
		if (!isCanvas && (!firstChild.current || !lastChild.current))
			try {
				await Promise.all([
					awaitRefCallback(firstChild, controller),
					amountChildren > 1 ? awaitRefCallback(lastChild, controller) : true,
				]);
			} catch {
				controller.abort();
			}
		frame.read(measure, false, true);
	}, [measure]);
	useLayoutEffect(() => {
		scheduleMeasure();
	}, [itemAmount]);
	const initialResize = useRef(true);
	useEffect(() => {
		return resize(parentRef.current, ({ contentSize }) => {
			if (!initialResize.current && (contentSize.width || contentSize.height)) {
				scheduleMeasure();
				startTransition(() => setIsResizing(true));
			}
			initialResize.current = false;
		});
	}, []);
	useEffect(() => {
		if (isResizing) {
			const timer = setTimeout(
				() => startTransition(() => setIsResizing(false)),
				500,
			);
			return () => clearTimeout(timer);
		}
	}, [isResizing]);
	const totalItems = filteredSlots?.length;
	const childrenSize = isCanvas ? 0 : size?.children;
	const itemWithGap = size?.item + gap;
	const itemOffset = startFrom * itemWithGap;
	const [currentItem, setCurrentItem] = useState(startFrom + totalItems);
	const [isDragging, setIsDragging] = useState(false);
	if (isCanvas) {
		if (currentItem !== startFrom) {
			setCurrentItem(startFrom);
		}
	}
	const visibilityRef = useRef(null);
	const isInView = useInView(visibilityRef);
	const isVisible = usePageInView() && isInView;
	const factor = isInverted ? 1 : -1;
	const xOrY = useMotionValue(childrenSize);
	const canvasPosition = isHorizontal
		? -startFrom * (size?.itemWidth + gap)
		: -startFrom * (size?.itemHeight + gap);
	const newPosition = () => factor * currentItem * itemWithGap;
	const wrappedValue = !isCanvas
		? useTransform(xOrY, (value) => {
				const wrapped = wrap(
					-childrenSize * rtlDirectionModifier,
					-childrenSize * rtlDirectionModifier * 2,
					value * rtlDirectionModifier,
				);
				return isNaN(wrapped) ? 0 : wrapped;
			})
		: 0;
	const wrappedIndex = wrap(0, totalItems, currentItem);
	const wrappedIndexInverted = wrap(0, -totalItems, currentItem);
	useLayoutEffect(() => {
		if (size?.children === null) return;
		if (!initialResize.current && isResizing) {
			xOrY.set(newPosition());
		}
	}, [
		size,
		childrenSize,
		factor,
		itemOffset,
		currentItem,
		itemWithGap,
		isResizing,
	]);
	const switchPages = () => {
		if (isCanvas || !hasChildren || !size.parent || isDragging) return;
		if (xOrY.get() !== newPosition()) {
			animate(xOrY, newPosition(), transitionControl);
		}
		if (autoPlayControl && shouldPlayOnHover && (playOffscreen || isVisible)) {
			timeoutRef.current = setTimeout(() => {
				startTransition(() =>
					setCurrentItem((item) => item + 1 * rtlDirectionModifier),
				);
				switchPages();
			}, intervalControl * 1e3);
		}
	};
	const setDelta = (delta, transition = false) => {
		if (!isInverted) {
			if (transition)
				startTransition(() => setCurrentItem((item) => item + delta));
			else setCurrentItem((item) => item + delta);
		} else {
			if (transition)
				startTransition(() => setCurrentItem((item) => item - delta));
			else setCurrentItem((item) => item - delta);
		}
	};
	const setPage = (index) => {
		const currentItemWrapped = wrap(0, totalItems, currentItem);
		const currentItemWrappedInvert = wrap(0, -totalItems, currentItem);
		const goto = index - currentItemWrapped;
		const gotoInverted = index - Math.abs(currentItemWrappedInvert);
		if (!isInverted) {
			startTransition(() => setCurrentItem((item) => item + goto));
		} else {
			startTransition(() => setCurrentItem((item) => item - gotoInverted));
		}
	};
	const handleDragStart = () => {
		startTransition(() => setIsDragging(true));
	};
	const handleDragEnd = (event, { offset, velocity }) => {
		startTransition(() => setIsDragging(false));
		const offsetXorY = isHorizontal ? offset.x : offset.y;
		const velocityThreshold = 200;
		const velocityXorY = isHorizontal ? velocity.x : velocity.y;
		const isHalfOfNext = offsetXorY < -size.item / 2;
		const isHalfOfPrev = offsetXorY > size.item / 2;
		const normalizedOffset = Math.abs(offsetXorY);
		const itemDelta = Math.round(normalizedOffset / size.item);
		const itemDeltaFromOne = itemDelta === 0 ? 1 : itemDelta;
		if (velocityXorY > velocityThreshold) {
			setDelta(-itemDeltaFromOne * rtlDirectionModifier, true);
		} else if (velocityXorY < -velocityThreshold) {
			setDelta(itemDeltaFromOne * rtlDirectionModifier, true);
		} else {
			if (isHalfOfNext) {
				setDelta(itemDelta * rtlDirectionModifier, true);
			}
			if (isHalfOfPrev) {
				setDelta(-itemDelta * rtlDirectionModifier, true);
			}
		}
	};
	useEffect(() => {
		if (!isVisible || isResizing || amountChildren <= 1) return;
		switchPages();
		return () => timeoutRef.current && clearTimeout(timeoutRef.current);
	}, [dupedChildren, isVisible, isResizing]);
	let childCounter = 0;
	const columnOrRowValue = `calc(${100 / itemAmount}% - ${gap}px + ${gap / itemAmount}px)`;
	for (let index = 0; index < duplicateBy; index++) {
		dupedChildren = dupedChildren.concat(
			Children.map(filteredSlots, (child, childIndex) => {
				let ref;
				if (index === 0) {
					if (childIndex === 0) {
						ref = childrenRef[0];
					} else if (childIndex === filteredSlots.length - 1) {
						ref = childrenRef[1];
					}
				}
				return (
					<Slide
						ref={ref}
						slideKey={index + childIndex + "lg"}
						index={index}
						width={
							isHorizontal
								? itemAmount > 1
									? columnOrRowValue
									: "100%"
								: "100%"
						}
						height={
							!isHorizontal
								? itemAmount > 1
									? columnOrRowValue
									: "100%"
								: "100%"
						}
						size={size}
						child={child}
						numChildren={filteredSlots?.length}
						wrappedValue={wrappedValue}
						childCounter={childCounter++}
						gap={gap}
						isCanvas={isCanvas}
						isHorizontal={isHorizontal}
						effectsOpacity={effectsOpacity}
						effectsScale={effectsScale}
						effectsRotate={effectsRotate}
						directionModifier={rtlDirectionModifier}
					>
						{index + childIndex}
					</Slide>
				);
			}),
		);
	}
	const fadeDirection = isHorizontal ? "to right" : "to bottom";
	const fadeWidthStart = fadeWidth / 2;
	const fadeWidthEnd = 100 - fadeWidth / 2;
	const fadeInsetStart = clamp(fadeInset, 0, fadeWidthStart);
	const fadeInsetEnd = 100 - fadeInset;
	const fadeMask = `linear-gradient(${fadeDirection}, rgba(0, 0, 0, ${fadeAlpha}) ${fadeInsetStart}%, rgba(0, 0, 0, 1) ${fadeWidthStart}%, rgba(0, 0, 0, 1) ${fadeWidthEnd}%, rgba(0, 0, 0, ${fadeAlpha}) ${fadeInsetEnd}%)`;
	const dots = [];
	const dotsBlurStyle = {};
	if (showProgressDots) {
		for (let i = 0; i < filteredSlots?.length; i++) {
			dots.push(
				<Dot
					dotStyle={{
						...dotStyle,
						width: dotSize,
						height: dotSize,
						backgroundColor: dotsFill,
					}}
					buttonStyle={baseButtonStyles}
					selectedOpacity={dotsActiveOpacity}
					opacity={dotsOpacity}
					onClick={() => setPage(i)}
					wrappedIndex={wrappedIndex}
					wrappedIndexInverted={wrappedIndexInverted}
					total={totalItems}
					index={i}
					gap={dotsGap}
					padding={dotsPadding}
					isHorizontal={isHorizontal}
					isInverted={isInverted}
				/>,
			);
		}
		if (dotsBlur > 0) {
			dotsBlurStyle.backdropFilter =
				dotsBlurStyle.WebkitBackdropFilter = `blur(${dotsBlur}px)`;
		}
	}
	const dragProps = dragControl
		? {
				drag: isHorizontal ? "x" : "y",
				onDragStart: handleDragStart,
				onDragEnd: handleDragEnd,
				dragDirectionLock: true,
				values: {
					x: writingDirection === "rtl" ? -xOrY : xOrY,
					y: xOrY,
				},
				dragMomentum: false,
			}
		: {};
	const arrowHasTop =
		arrowPosition === "top-left" ||
		arrowPosition === "top-mid" ||
		arrowPosition === "top-right";
	const arrowHasBottom =
		arrowPosition === "bottom-left" ||
		arrowPosition === "bottom-mid" ||
		arrowPosition === "bottom-right";
	const arrowHasLeft =
		arrowPosition === "top-left" || arrowPosition === "bottom-left";
	const arrowHasRight =
		arrowPosition === "top-right" || arrowPosition === "bottom-right";
	const arrowHasMid =
		arrowPosition === "top-mid" ||
		arrowPosition === "bottom-mid" ||
		arrowPosition === "auto";
	const leftArrowSrc =
		leftArrow ||
		"https://framerusercontent.com/images/6tTbkXggWgQCAJ4DO2QEdXXmgM.svg?arrow=left";
	const rightArrowSrc =
		rightArrow ||
		"https://framerusercontent.com/images/11KSGbIZoRSg4pjdnUoif6MKHI.svg?arrow=right";
	return (
		<section
			style={{
				...containerStyle,
				padding: paddingValue,
				WebkitMaskImage: fadeContent ? fadeMask : void 0,
				maskImage: fadeContent ? fadeMask : void 0,
				opacity: size?.item !== null ? 1 : OPACITY_0,
				userSelect: "none",
			}}
			onMouseEnter={() => {
				setIsHovering(true);
				if (!effectsHover) setShouldPlayOnHover(false);
			}}
			onMouseLeave={() => {
				setIsHovering(false);
				if (!effectsHover) setShouldPlayOnHover(true);
			}}
			onMouseDown={(event) => {
				event.preventDefault();
				startTransition(() => setIsMouseDown(true));
			}}
			onMouseUp={() => startTransition(() => setIsMouseDown(false))}
			ref={visibilityRef}
		>
			<div
				style={{
					width: "100%",
					height: "100%",
					margin: 0,
					padding: "inherit",
					position: "absolute",
					inset: 0,
					overflow: overflow ? "visible" : "hidden",
					borderRadius,
					userSelect: "none",
					perspective: isCanvas ? "none" : effectsPerspective,
				}}
			>
				<motion.ul
					ref={parentRef}
					{...dragProps}
					style={{
						...containerStyle,
						gap,
						placeItems: alignment,
						x: isHorizontal ? (isCanvas ? canvasPosition : wrappedValue) : 0,
						y: !isHorizontal ? (isCanvas ? canvasPosition : wrappedValue) : 0,
						flexDirection: isHorizontal ? "row" : "column",
						transformStyle:
							effectsRotate !== 0 && !isCanvas ? "preserve-3d" : void 0,
						cursor: dragControl ? (isMouseDown ? "grabbing" : "grab") : "auto",
						userSelect: "none",
						...style,
					}}
				>
					{dupedChildren}
				</motion.ul>
			</div>
			<fieldset
				style={{
					...controlsStyles,
				}}
				aria-label={"Slideshow pagination controls"}
				className={"framer--slideshow-controls"}
			>
				<motion.div
					style={{
						position: "absolute",
						display: "flex",
						flexDirection: isHorizontal ? "row" : "column",
						justifyContent: arrowShouldSpace ? "space-between" : "center",
						gap: arrowShouldSpace ? "unset" : arrowGap,
						opacity: arrowShouldFadeIn ? OPACITY_0 : 1,
						alignItems: "center",
						inset: arrowPadding,
						top: arrowShouldSpace
							? arrowPadding
							: arrowHasTop
								? arrowPaddingTop
								: "unset",
						left: arrowShouldSpace
							? arrowPadding
							: arrowHasLeft
								? arrowPaddingLeft
								: arrowHasMid
									? 0
									: "unset",
						right: arrowShouldSpace
							? arrowPadding
							: arrowHasRight
								? arrowPaddingRight
								: arrowHasMid
									? 0
									: "unset",
						bottom: arrowShouldSpace
							? arrowPadding
							: arrowHasBottom
								? arrowPaddingBottom
								: "unset",
					}}
					animate={
						arrowShouldFadeIn && {
							opacity: isHovering ? 1 : OPACITY_0,
						}
					}
					transition={transitionControl}
				>
					<motion.button
						type={"button"}
						style={{
							...baseButtonStyles,
							backgroundColor: arrowFill,
							width: arrowSize,
							height: arrowSize,
							borderRadius: arrowRadius,
							rotate: !isHorizontal ? 90 : 0,
							display: showMouseControls ? "block" : "none",
							pointerEvents: "auto",
						}}
						onClick={() => setDelta(-1, true)}
						aria-label={"Previous"}
						whileTap={{
							scale: 0.9,
						}}
						transition={{
							duration: 0.15,
						}}
					>
						<img
							decoding={"async"}
							width={arrowSize}
							height={arrowSize}
							src={
								isHorizontal && writingDirection === "rtl"
									? rightArrowSrc
									: leftArrowSrc
							}
							alt={"Back Arrow"}
						/>
					</motion.button>
					<motion.button
						type={"button"}
						style={{
							...baseButtonStyles,
							backgroundColor: arrowFill,
							width: arrowSize,
							height: arrowSize,
							borderRadius: arrowRadius,
							rotate: !isHorizontal ? 90 : 0,
							display: showMouseControls ? "block" : "none",
							pointerEvents: "auto",
						}}
						onClick={() => setDelta(1, true)}
						aria-label={"Next"}
						whileTap={{
							scale: 0.9,
						}}
						transition={{
							duration: 0.15,
						}}
					>
						<img
							decoding={"async"}
							width={arrowSize}
							height={arrowSize}
							src={
								isHorizontal && writingDirection === "rtl"
									? leftArrowSrc
									: rightArrowSrc
							}
							alt={"Next Arrow"}
						/>
					</motion.button>
				</motion.div>
				{dots.length > 1 ? (
					<div
						style={{
							...dotsContainerStyle,
							left: isHorizontal ? "50%" : dotsInset,
							top: !isHorizontal ? "50%" : "unset",
							transform: isHorizontal ? "translateX(-50%)" : "translateY(-50%)",
							flexDirection: isHorizontal ? "row" : "column",
							bottom: isHorizontal ? dotsInset : "unset",
							borderRadius: dotsRadius,
							backgroundColor: dotsBackground,
							userSelect: "none",
							...dotsBlurStyle,
						}}
					>
						{dots}
					</div>
				) : null}
			</fieldset>
		</section>
	);
}
Slideshow.defaultProps = {
	direction: "left",
	dragControl: false,
	startFrom: 0,
	itemAmount: 1,
	infinity: true,
	gap: 10,
	padding: 10,
	autoPlayControl: true,
	effectsOptions: {
		effectsOpacity: 1,
		effectsScale: 1,
		effectsRotate: 0,
		effectsPerspective: 1200,
		effectsHover: true,
		playOffscreen: false,
	},
	transitionControl: {
		type: "spring",
		stiffness: 200,
		damping: 40,
	},
	fadeOptions: {
		fadeContent: false,
		overflow: false,
		fadeWidth: 25,
		fadeAlpha: 0,
		fadeInset: 0,
	},
	arrowOptions: {
		showMouseControls: true,
		arrowShouldFadeIn: false,
		arrowShouldSpace: true,
		arrowFill: "rgba(0,0,0,0.2)",
		arrowSize: 40,
	},
	progressOptions: {
		showProgressDots: true,
	},
};
addPropertyControls(Slideshow, {
	slots: {
		type: ControlType.Array,
		title: "Content",
		control: {
			type: ControlType.ComponentInstance,
		},
	},
	direction: {
		type: ControlType.Enum,
		title: "Direction",
		options: ["left", "right", "top", "bottom"],
		optionIcons: [
			"direction-left",
			"direction-right",
			"direction-up",
			"direction-down",
		],
		optionTitles: ["Left", "Right", "Top", "Bottom"],
		displaySegmentedControl: true,
		defaultValue: Slideshow.defaultProps.direction,
	},
	autoPlayControl: {
		type: ControlType.Boolean,
		title: "Auto Play",
		defaultValue: true,
	},
	intervalControl: {
		type: ControlType.Number,
		title: "Interval",
		defaultValue: 1.5,
		min: 0.5,
		max: 10,
		step: 0.1,
		displayStepper: true,
		unit: "s",
		hidden: (props) => !props.autoPlayControl,
	},
	dragControl: {
		type: ControlType.Boolean,
		title: "Draggable",
		defaultValue: false,
	},
	startFrom: {
		type: ControlType.Number,
		title: "Current",
		min: 0,
		max: 10,
		displayStepper: true,
		defaultValue: Slideshow.defaultProps.startFrom,
	},
	effectsOptions: {
		type: ControlType.Object,
		title: "Effects",
		controls: {
			effectsOpacity: {
				type: ControlType.Number,
				title: "Opacity",
				defaultValue: Slideshow.defaultProps.effectsOptions.effectsOpacity,
				min: 0,
				max: 1,
				step: 0.01,
				displayStepper: true,
			},
			effectsScale: {
				type: ControlType.Number,
				title: "Scale",
				defaultValue: Slideshow.defaultProps.effectsOptions.effectsScale,
				min: 0,
				max: 1,
				step: 0.01,
				displayStepper: true,
			},
			effectsPerspective: {
				type: ControlType.Number,
				title: "Perspective",
				defaultValue: Slideshow.defaultProps.effectsOptions.effectsPerspective,
				min: 200,
				max: 2e3,
				step: 1,
			},
			effectsRotate: {
				type: ControlType.Number,
				title: "Rotate",
				defaultValue: Slideshow.defaultProps.effectsOptions.effectsRotate,
				min: -180,
				max: 180,
				step: 1,
			},
			effectsHover: {
				type: ControlType.Boolean,
				title: "On Hover",
				enabledTitle: "Play",
				disabledTitle: "Pause",
				defaultValue: Slideshow.defaultProps.effectsOptions.effectsHover,
			},
			playOffscreen: {
				type: ControlType.Boolean,
				title: "Offscreen",
				enabledTitle: "Play",
				disabledTitle: "Pause",
				defaultValue: Slideshow.defaultProps.effectsOptions.playOffscreen,
			},
		},
	},
	alignment: {
		type: ControlType.Enum,
		title: "Align",
		options: ["flex-start", "center", "flex-end"],
		optionIcons: {
			direction: {
				right: ["align-top", "align-middle", "align-bottom"],
				left: ["align-top", "align-middle", "align-bottom"],
				top: ["align-left", "align-center", "align-right"],
				bottom: ["align-left", "align-center", "align-right"],
			},
		},
		defaultValue: "center",
		displaySegmentedControl: true,
	},
	itemAmount: {
		type: ControlType.Number,
		title: "Items",
		min: 1,
		max: 10,
		displayStepper: true,
		defaultValue: Slideshow.defaultProps.itemAmount,
	},
	gap: {
		type: ControlType.Number,
		title: "Gap",
		min: 0,
	},
	padding: {
		title: "Padding",
		type: ControlType.FusedNumber,
		toggleKey: "paddingPerSide",
		toggleTitles: ["Padding", "Padding per side"],
		defaultValue: 0,
		valueKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
		valueLabels: ["T", "R", "B", "L"],
		min: 0,
	},
	borderRadius: {
		type: ControlType.Number,
		title: "Radius",
		min: 0,
		max: 500,
		displayStepper: true,
		defaultValue: 0,
	},
	transitionControl: {
		type: ControlType.Transition,
		defaultValue: Slideshow.defaultProps.transitionControl,
		title: "Transition",
	},
	fadeOptions: {
		type: ControlType.Object,
		title: "Clipping",
		controls: {
			fadeContent: {
				type: ControlType.Boolean,
				title: "Fade",
				defaultValue: false,
			},
			overflow: {
				type: ControlType.Boolean,
				title: "Overflow",
				enabledTitle: "Show",
				disabledTitle: "Hide",
				defaultValue: false,
				hidden(props) {
					return props.fadeContent === true;
				},
			},
			fadeWidth: {
				type: ControlType.Number,
				title: "Width",
				defaultValue: 25,
				min: 0,
				max: 100,
				unit: "%",
				hidden(props) {
					return props.fadeContent === false;
				},
			},
			fadeInset: {
				type: ControlType.Number,
				title: "Inset",
				defaultValue: 0,
				min: 0,
				max: 100,
				unit: "%",
				hidden(props) {
					return props.fadeContent === false;
				},
			},
			fadeAlpha: {
				type: ControlType.Number,
				title: "Opacity",
				defaultValue: 0,
				min: 0,
				max: 1,
				step: 0.05,
				hidden(props) {
					return props.fadeContent === false;
				},
			},
		},
	},
	arrowOptions: {
		type: ControlType.Object,
		title: "Arrows",
		controls: {
			showMouseControls: {
				type: ControlType.Boolean,
				title: "Show",
				defaultValue: Slideshow.defaultProps.arrowOptions.showMouseControls,
			},
			arrowFill: {
				type: ControlType.Color,
				title: "Fill",
				hidden: (props) => !props.showMouseControls,
				defaultValue: Slideshow.defaultProps.arrowOptions.arrowFill,
			},
			leftArrow: {
				type: ControlType.Image,
				title: "Previous",
				hidden: (props) => !props.showMouseControls,
			},
			rightArrow: {
				type: ControlType.Image,
				title: "Next",
				hidden: (props) => !props.showMouseControls,
			},
			arrowSize: {
				type: ControlType.Number,
				title: "Size",
				min: 0,
				max: 200,
				displayStepper: true,
				defaultValue: Slideshow.defaultProps.arrowOptions.arrowSize,
				hidden: (props) => !props.showMouseControls,
			},
			arrowRadius: {
				type: ControlType.Number,
				title: "Radius",
				min: 0,
				max: 500,
				defaultValue: 40,
				hidden: (props) => !props.showMouseControls,
			},
			arrowShouldFadeIn: {
				type: ControlType.Boolean,
				title: "Fade In",
				defaultValue: false,
				hidden: (props) => !props.showMouseControls,
			},
			arrowShouldSpace: {
				type: ControlType.Boolean,
				title: "Distance",
				enabledTitle: "Space",
				disabledTitle: "Group",
				defaultValue: Slideshow.defaultProps.arrowOptions.arrowShouldSpace,
				hidden: (props) => !props.showMouseControls,
			},
			arrowPosition: {
				type: ControlType.Enum,
				title: "Position",
				options: [
					"auto",
					"top-left",
					"top-mid",
					"top-right",
					"bottom-left",
					"bottom-mid",
					"bottom-right",
				],
				optionTitles: [
					"Center",
					"Top Left",
					"Top Middle",
					"Top Right",
					"Bottom Left",
					"Bottom Middle",
					"Bottom Right",
				],
				hidden: (props) => !props.showMouseControls || props.arrowShouldSpace,
			},
			arrowPadding: {
				type: ControlType.Number,
				title: "Inset",
				min: -100,
				max: 100,
				defaultValue: 20,
				displayStepper: true,
				hidden: (props) => !props.showMouseControls || !props.arrowShouldSpace,
			},
			arrowPaddingTop: {
				type: ControlType.Number,
				title: "Top",
				min: -500,
				max: 500,
				defaultValue: 0,
				displayStepper: true,
				hidden: (props) =>
					!props.showMouseControls ||
					props.arrowShouldSpace ||
					props.arrowPosition === "auto" ||
					props.arrowPosition === "bottom-mid" ||
					props.arrowPosition === "bottom-left" ||
					props.arrowPosition === "bottom-right",
			},
			arrowPaddingBottom: {
				type: ControlType.Number,
				title: "Bottom",
				min: -500,
				max: 500,
				defaultValue: 0,
				displayStepper: true,
				hidden: (props) =>
					!props.showMouseControls ||
					props.arrowShouldSpace ||
					props.arrowPosition === "auto" ||
					props.arrowPosition === "top-mid" ||
					props.arrowPosition === "top-left" ||
					props.arrowPosition === "top-right",
			},
			arrowPaddingRight: {
				type: ControlType.Number,
				title: "Right",
				min: -500,
				max: 500,
				defaultValue: 0,
				displayStepper: true,
				hidden: (props) =>
					!props.showMouseControls ||
					props.arrowShouldSpace ||
					props.arrowPosition === "auto" ||
					props.arrowPosition === "top-left" ||
					props.arrowPosition === "top-mid" ||
					props.arrowPosition === "bottom-left" ||
					props.arrowPosition === "bottom-mid",
			},
			arrowPaddingLeft: {
				type: ControlType.Number,
				title: "Left",
				min: -500,
				max: 500,
				defaultValue: 0,
				displayStepper: true,
				hidden: (props) =>
					!props.showMouseControls ||
					props.arrowShouldSpace ||
					props.arrowPosition === "auto" ||
					props.arrowPosition === "top-right" ||
					props.arrowPosition === "top-mid" ||
					props.arrowPosition === "bottom-right" ||
					props.arrowPosition === "bottom-mid",
			},
			arrowGap: {
				type: ControlType.Number,
				title: "Gap",
				min: 0,
				max: 100,
				defaultValue: 10,
				displayStepper: true,
				hidden: (props) => !props.showMouseControls || props.arrowShouldSpace,
			},
		},
	},
	progressOptions: {
		type: ControlType.Object,
		title: "Dots",
		controls: {
			showProgressDots: {
				type: ControlType.Boolean,
				title: "Show",
				defaultValue: false,
			},
			dotSize: {
				type: ControlType.Number,
				title: "Size",
				min: 1,
				max: 100,
				defaultValue: 10,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsInset: {
				type: ControlType.Number,
				title: "Inset",
				min: -100,
				max: 100,
				defaultValue: 10,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsGap: {
				type: ControlType.Number,
				title: "Gap",
				min: 0,
				max: 100,
				defaultValue: 10,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsPadding: {
				type: ControlType.Number,
				title: "Padding",
				min: 0,
				max: 100,
				defaultValue: 10,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsFill: {
				type: ControlType.Color,
				title: "Fill",
				defaultValue: "#fff",
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsBackground: {
				type: ControlType.Color,
				title: "Backdrop",
				defaultValue: "rgba(0,0,0,0.2)",
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsRadius: {
				type: ControlType.Number,
				title: "Radius",
				min: 0,
				max: 200,
				defaultValue: 50,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsOpacity: {
				type: ControlType.Number,
				title: "Opacity",
				min: 0,
				max: 1,
				defaultValue: 0.5,
				step: 0.1,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsActiveOpacity: {
				type: ControlType.Number,
				title: "Current",
				min: 0,
				max: 1,
				defaultValue: 1,
				step: 0.1,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsBlur: {
				type: ControlType.Number,
				title: "Blur",
				min: 0,
				max: 50,
				defaultValue: 0,
				step: 1,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
		},
	},
});
var containerStyle = {
	display: "flex",
	flexDirection: "row",
	width: "100%",
	height: "100%",
	maxWidth: "100%",
	maxHeight: "100%",
	placeItems: "center",
	margin: 0,
	padding: 0,
	listStyleType: "none",
	textIndent: "none",
};
var placeholderStyles = {
	display: "flex",
	width: "100%",
	height: "100%",
	placeContent: "center",
	placeItems: "center",
	flexDirection: "column",
	color: "#96F",
	background: "rgba(136, 85, 255, 0.1)",
	fontSize: 11,
	overflow: "hidden",
	padding: "20px 20px 30px 20px",
};
var emojiStyles = {
	fontSize: 32,
	marginBottom: 10,
};
var titleStyles = {
	margin: 0,
	marginBottom: 10,
	fontWeight: 600,
	textAlign: "center",
};
var subtitleStyles = {
	margin: 0,
	opacity: 0.7,
	maxWidth: 180,
	lineHeight: 1.5,
	textAlign: "center",
};
var baseButtonStyles = {
	border: "none",
	display: "flex",
	placeContent: "center",
	placeItems: "center",
	overflow: "hidden",
	background: "transparent",
	cursor: "pointer",
	margin: 0,
	padding: 0,
};
var controlsStyles = {
	display: "flex",
	justifyContent: "space-between",
	alignItems: "center",
	position: "absolute",
	pointerEvents: "none",
	userSelect: "none",
	top: 0,
	left: 0,
	right: 0,
	bottom: 0,
	border: 0,
	padding: 0,
	margin: 0,
};
var clamp = (num, min, max) => Math.min(Math.max(num, min), max);
var Slide = /* @__PURE__ */ memo(
	/* @__PURE__ */ forwardRef(function Component(props, ref) {
		const {
			slideKey,
			width,
			height,
			child,
			size,
			gap,
			wrappedValue,
			numChildren,
			childCounter,
			isCanvas,
			effects,
			effectsOpacity,
			effectsScale,
			effectsRotate,
			isHorizontal,
			isLast,
			index,
			/** 1 or -1 depending on if horizontal and rtl writing direction */
			directionModifier,
		} = props;
		const fallbackRef = useRef();
		const childOffset = (size?.item + gap) * childCounter;
		const scrollRange = [
			-size?.item,
			0,
			size?.parent - size?.item + gap,
			size?.parent,
		].map((val) => val - childOffset * directionModifier);
		const rotateY =
			!isCanvas &&
			useTransform(wrappedValue, scrollRange, [
				-effectsRotate,
				0,
				0,
				effectsRotate,
			]);
		const rotateX =
			!isCanvas &&
			useTransform(wrappedValue, scrollRange, [
				effectsRotate,
				0,
				0,
				-effectsRotate,
			]);
		const opacity =
			!isCanvas &&
			useTransform(wrappedValue, scrollRange, [
				effectsOpacity,
				1,
				1,
				effectsOpacity,
			]);
		const scale =
			!isCanvas &&
			useTransform(wrappedValue, scrollRange, [
				effectsScale,
				1,
				1,
				effectsScale,
			]);
		const originXorY =
			!isCanvas && useTransform(wrappedValue, scrollRange, [1, 1, 0, 0]);
		const isVisible =
			!isCanvas &&
			useTransform(
				wrappedValue,
				(latest) => latest >= scrollRange[1] && latest <= scrollRange[2],
			);
		useEffect(() => {
			if (!isVisible) return;
			function manageVisibility(visible) {
				const node = ref?.current ?? fallbackRef.current;
				if (!node) return;
				if (visible) {
					node.querySelectorAll("button,a").forEach((el) => {
						const orig = el.dataset.origTabIndex;
						if (orig) el.tabIndex = orig;
						else el.removeAttribute("tabIndex");
					});
				} else {
					node.querySelectorAll("button,a").forEach((el) => {
						const orig = el.getAttribute("tabIndex");
						if (orig) el.dataset.origTabIndex = orig;
						el.tabIndex = -1;
					});
				}
				node.setAttribute("aria-hidden", !visible);
			}
			manageVisibility(isVisible);
			return isVisible.on("change", (visible) => {
				manageVisibility(visible);
			});
		}, []);
		const visibility = isCanvas
			? "visible"
			: useTransform(
					wrappedValue,
					[
						scrollRange[0] - size.viewportLength,
						mix(scrollRange[1], scrollRange[2], 0.5),
						scrollRange[3] + size.viewportLength,
					],
					["hidden", "visible", "hidden"],
				);
		const key = slideKey + "child";
		return (
			<LayoutGroup inherit={"id"} id={key}>
				<li
					style={{
						display: "contents",
					}}
				>
					{
						/* @__PURE__ */ cloneElement(child, {
							ref: ref ?? fallbackRef,
							key,
							style: {
								...child.props?.style,
								flexShrink: 0,
								userSelect: "none",
								width,
								height,
								opacity,
								scale,
								originX: isHorizontal ? originXorY : 0.5,
								originY: !isHorizontal ? originXorY : 0.5,
								rotateY: isHorizontal ? rotateY : 0,
								rotateX: !isHorizontal ? rotateX : 0,
								visibility,
							},
							layoutId: child.props.layoutId
								? child.props.layoutId + "-original-" + index
								: void 0,
						})
					}
				</li>
			</LayoutGroup>
		);
	}),
);
var Dot = /* @__PURE__ */ memo(function Dot2({
	selectedOpacity,
	opacity,
	total,
	index,
	wrappedIndex,
	wrappedIndexInverted,
	dotStyle: dotStyle2,
	buttonStyle,
	gap,
	padding,
	isHorizontal,
	isInverted,
	...props
}) {
	let isSelected = wrappedIndex === index;
	if (isInverted) {
		isSelected = Math.abs(wrappedIndexInverted) === index;
	}
	const inlinePadding = gap / 2;
	const top = !isHorizontal && index > 0 ? inlinePadding : padding;
	const bottom = !isHorizontal && index !== total - 1 ? inlinePadding : padding;
	const right = isHorizontal && index !== total - 1 ? inlinePadding : padding;
	const left = isHorizontal && index > 0 ? inlinePadding : padding;
	return (
		<button
			aria-label={`Scroll to page ${index + 1}`}
			type={"button"}
			{...props}
			style={{
				...buttonStyle,
				padding: `${top}px ${right}px ${bottom}px ${left}px`,
			}}
		>
			<motion.div
				style={{
					...dotStyle2,
				}}
				initial={false}
				animate={{
					opacity: isSelected ? selectedOpacity : opacity,
				}}
				transition={{
					duration: 0.3,
				}}
			/>
		</button>
	);
});
var dotsContainerStyle = {
	display: "flex",
	placeContent: "center",
	placeItems: "center",
	overflow: "hidden",
	position: "absolute",
	pointerEvents: "auto",
};
var dotStyle = {
	borderRadius: "50%",
	background: "white",
	cursor: "pointer",
	border: "none",
	placeContent: "center",
	placeItems: "center",
	padding: 0,
};
function useWritingDirection() {
	const [writingDirection, setWritingDirection] = useState("ltr");
	useEffect(() => {
		if (__unframerWindow?.document?.documentElement?.dir === "rtl") {
			setWritingDirection("rtl");
		}
	}, []);
	return writingDirection;
}
function getSlideshowResolvedDirection(direction, writingDirection) {
	if (writingDirection !== "rtl") return direction;
	if (direction === "left") return "right";
	if (direction === "right") return "left";
	return direction;
}

// /:https://framerusercontent.com/modules/bkuGcwP39hk0pDUcbFrT/EBNjM6JVfBMtb0s4bA5Z/gvk807VK1.js
var TestimonialsCardFonts = getFonts(stdin_default);
var SlideshowFonts = getFonts(Slideshow);
var MotionDivWithFX = withFX(motion2.div);
var cycleOrder = ["UXteWuEcU", "DkVhX9cpt"];
var serializationHash = "framer-oFmnL";
var variantClassNames = {
	DkVhX9cpt: "framer-v-10yua2l",
	UXteWuEcU: "framer-v-vgjv0s",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 20,
};
var transition1 = {
	damping: 50,
	delay: 0.3,
	mass: 1,
	stiffness: 300,
	type: "spring",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 20,
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "UXteWuEcU",
	Phone: "DkVhX9cpt",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "UXteWuEcU",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "UXteWuEcU",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation}
						__framer__exit={animation1}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							scopingClassNames,
							"framer-vgjv0s",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"UXteWuEcU"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								DkVhX9cpt: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-sogkeq-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"t2swHfI_9-container"}
								nodeId={"t2swHfI_9"}
								rendersWithMotion={true}
								scopeId={"gvk807VK1"}
							>
								<Slideshow
									alignment={"center"}
									arrowOptions={{
										arrowFill: "rgba(255, 255, 255, 0.1)",
										arrowGap: 16,
										arrowPadding: 20,
										arrowPaddingBottom: 0,
										arrowPaddingLeft: 0,
										arrowPaddingRight: 0,
										arrowPaddingTop: -54,
										arrowPosition: "bottom-mid",
										arrowRadius: 40,
										arrowShouldFadeIn: false,
										arrowShouldSpace: false,
										arrowSize: 32,
										showMouseControls: true,
									}}
									autoPlayControl={false}
									borderRadius={0}
									direction={"left"}
									dragControl={true}
									effectsOptions={{
										effectsHover: true,
										effectsOpacity: 1,
										effectsPerspective: 1200,
										effectsRotate: 0,
										effectsScale: 1,
										playOffscreen: false,
									}}
									fadeOptions={{
										fadeAlpha: 0,
										fadeContent: false,
										fadeInset: 0,
										fadeWidth: 25,
										overflow: false,
									}}
									gap={20}
									height={"100%"}
									id={"t2swHfI_9"}
									intervalControl={5}
									itemAmount={1}
									layoutId={"t2swHfI_9"}
									padding={0}
									paddingBottom={0}
									paddingLeft={0}
									paddingPerSide={false}
									paddingRight={0}
									paddingTop={0}
									progressOptions={{
										dotsActiveOpacity: 1,
										dotsBackground: "rgba(0, 0, 0, 0)",
										dotsBlur: 0,
										dotsFill:
											"var(--token-39dc44c8-4f86-4c75-bdd3-35ba627edbdb, rgb(228, 228, 231))",
										dotsGap: 8,
										dotsInset: 16,
										dotSize: 8,
										dotsOpacity: 0.2,
										dotsPadding: 0,
										dotsRadius: 0,
										showProgressDots: false,
									}}
									slots={[
										<ComponentViewportProvider height={189} width={"800px"}>
											<SmartComponentScopedContainer
												className={"framer-136f18e-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"uN_LgRNd4-tLAvCEXeH-0-container"}
												nodeId={"tLAvCEXeH"}
												rendersWithMotion={true}
												scopeId={"gvk807VK1"}
											>
												{_jsx2(stdin_default, {
													height: "100%",
													Hmpib53N4: "Emma Reynolds",
													id: "tLAvCEXeH",
													iJmvqIGq2: "Visionary Agency",
													layoutId: "uN_LgRNd4-tLAvCEXeH-0",
													RDmJrJi7z: "Creative Director",
													style: {
														width: "100%",
													},
													vx01SgAfN: (
														<React.Fragment>
															<p>{`"Pure Visuals has an incredible eye for detail. Their ability to translate abstract ideas into stunning visuals is unmatched. Every project we've collaborated on has exceeded expectations."`}</p>
														</React.Fragment>
													),
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={189} width={"800px"}>
											<SmartComponentScopedContainer
												className={"framer-1at3tdl-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"gkytJQBIa-lZzHNFG8h-1-container"}
												nodeId={"lZzHNFG8h"}
												rendersWithMotion={true}
												scopeId={"gvk807VK1"}
											>
												{_jsx2(stdin_default, {
													height: "100%",
													Hmpib53N4: "Liam Carter",
													id: "lZzHNFG8h",
													iJmvqIGq2: "Carter & Co. Photography",
													layoutId: "gkytJQBIa-lZzHNFG8h-1",
													RDmJrJi7z: "Founder",
													style: {
														width: "100%",
													},
													vx01SgAfN: (
														<React.Fragment>
															<p>
																{
																	'"Working with Pure Visuals was a seamless experience. Their team is professional, creative, and truly understands how to bring a brand\u2019s vision to life through photography and videography."'
																}
															</p>
														</React.Fragment>
													),
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={189} width={"800px"}>
											<SmartComponentScopedContainer
												className={"framer-w98tip-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"vWONzA3Lq-vBdGeZrET-2-container"}
												nodeId={"vBdGeZrET"}
												rendersWithMotion={true}
												scopeId={"gvk807VK1"}
											>
												{_jsx2(stdin_default, {
													height: "100%",
													Hmpib53N4: "Sophia Nguyen",
													id: "vBdGeZrET",
													iJmvqIGq2: "Elevate Studios",
													layoutId: "vWONzA3Lq-vBdGeZrET-2",
													RDmJrJi7z: "Marketing Lead",
													style: {
														width: "100%",
													},
													vx01SgAfN: (
														<React.Fragment>
															<p>
																{
																	'"From concept to execution, Pure Visuals delivered beyond what we imagined. The visuals they created for our campaign not only looked beautiful but also drove engagement and conversions."'
																}
															</p>
														</React.Fragment>
													),
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
										<ComponentViewportProvider height={189} width={"800px"}>
											<SmartComponentScopedContainer
												className={"framer-1jov39l-container"}
												inComponentSlot={true}
												layoutDependency={layoutDependency}
												layoutId={"o2B3AcxoM-wYu_5urHY-3-container"}
												nodeId={"wYu_5urHY"}
												rendersWithMotion={true}
												scopeId={"gvk807VK1"}
											>
												{_jsx2(stdin_default, {
													height: "100%",
													Hmpib53N4: "Daniel Foster",
													id: "wYu_5urHY",
													iJmvqIGq2: "Flux Media",
													layoutId: "o2B3AcxoM-wYu_5urHY-3",
													RDmJrJi7z: "Head of Branding",
													style: {
														width: "100%",
													},
													vx01SgAfN: (
														<React.Fragment>
															<p>
																{
																	'"Pure Visuals is a powerhouse of creativity. They don\u2019t just capture moments; they tell compelling visual stories. We look forward to working with them again!"'
																}
															</p>
														</React.Fragment>
													),
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>,
									]}
									startFrom={0}
									style={{
										height: "100%",
										width: "100%",
									}}
									transitionControl={{
										damping: 40,
										delay: 0,
										mass: 1,
										stiffness: 200,
										type: "spring",
									}}
									width={"100%"}
									{...addPropertyOverrides(
										{
											DkVhX9cpt: {
												arrowOptions: {
													arrowFill: "rgba(255, 255, 255, 0.1)",
													arrowGap: 10,
													arrowPadding: 20,
													arrowPaddingBottom: 0,
													arrowPaddingLeft: 0,
													arrowPaddingRight: 0,
													arrowPaddingTop: -54,
													arrowPosition: "bottom-mid",
													arrowRadius: 40,
													arrowShouldFadeIn: false,
													arrowShouldSpace: false,
													arrowSize: 24,
													showMouseControls: true,
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup2>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-oFmnL.framer-bn7xrp, .framer-oFmnL .framer-bn7xrp { display: block; }",
	".framer-oFmnL.framer-vgjv0s { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 300px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1240px; }",
	".framer-oFmnL .framer-sogkeq-container { flex: 1 0 0px; height: 100%; position: relative; width: 1px; }",
	".framer-oFmnL .framer-136f18e-container, .framer-oFmnL .framer-1at3tdl-container, .framer-oFmnL .framer-w98tip-container, .framer-oFmnL .framer-1jov39l-container { height: auto; position: relative; width: 800px; }",
];
var Framergvk807VK1 = withCSS(Component2, css, "framer-oFmnL");
var stdin_default2 = Framergvk807VK1;
Framergvk807VK1.displayName = "Testimonials";
Framergvk807VK1.defaultProps = {
	height: 300,
	width: 1240,
};
addPropertyControls2(Framergvk807VK1, {
	variant: {
		options: ["UXteWuEcU", "DkVhX9cpt"],
		optionTitles: ["Desktop", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts(
	Framergvk807VK1,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...TestimonialsCardFonts,
		...SlideshowFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:testimonials
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "DkVhX9cpt",
	xl: "UXteWuEcU",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TestimonialsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e9f968b120b46161279fa64a0edc8e4d5553b011c7305ab1c4f7dc8d0bf37f64"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var testimonials_default = ComponentWithRoot;
export { testimonials_default as default };
